package com.hero.wireless.web.entity.business;

import com.hero.wireless.web.entity.base.BaseExample;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ChargeOrderExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table charge_order
     *
     * @mbg.generated Thu May 14 16:45:43 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table charge_order
     *
     * @mbg.generated Thu May 14 16:45:43 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table charge_order
     *
     * @mbg.generated Thu May 14 16:45:43 CST 2020
     */
    protected String dataLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table charge_order
     *
     * @mbg.generated Thu May 14 16:45:43 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Thu May 14 16:45:43 CST 2020
     */
    public ChargeOrderExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Thu May 14 16:45:43 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Thu May 14 16:45:43 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Thu May 14 16:45:43 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Thu May 14 16:45:43 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Thu May 14 16:45:43 CST 2020
     */
    public void setDataLock(String dataLock) {
        this.dataLock = dataLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Thu May 14 16:45:43 CST 2020
     */
    public String getDataLock() {
        return dataLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Thu May 14 16:45:43 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Thu May 14 16:45:43 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Thu May 14 16:45:43 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Thu May 14 16:45:43 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Thu May 14 16:45:43 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Thu May 14 16:45:43 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table charge_order
     *
     * @mbg.generated Thu May 14 16:45:43 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoIsNull() {
            addCriterion("Enterprise_No is null");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoIsNotNull() {
            addCriterion("Enterprise_No is not null");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoEqualTo(String value) {
            addCriterion("Enterprise_No =", value, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoNotEqualTo(String value) {
            addCriterion("Enterprise_No <>", value, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoGreaterThan(String value) {
            addCriterion("Enterprise_No >", value, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoGreaterThanOrEqualTo(String value) {
            addCriterion("Enterprise_No >=", value, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoLessThan(String value) {
            addCriterion("Enterprise_No <", value, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoLessThanOrEqualTo(String value) {
            addCriterion("Enterprise_No <=", value, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoLike(String value) {
            addCriterion("Enterprise_No like", value, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoNotLike(String value) {
            addCriterion("Enterprise_No not like", value, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoIn(List<String> values) {
            addCriterion("Enterprise_No in", values, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoNotIn(List<String> values) {
            addCriterion("Enterprise_No not in", values, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoBetween(String value1, String value2) {
            addCriterion("Enterprise_No between", value1, value2, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoNotBetween(String value1, String value2) {
            addCriterion("Enterprise_No not between", value1, value2, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdIsNull() {
            addCriterion("Enterprise_User_Id is null");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdIsNotNull() {
            addCriterion("Enterprise_User_Id is not null");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdEqualTo(Integer value) {
            addCriterion("Enterprise_User_Id =", value, "enterprise_User_Id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdNotEqualTo(Integer value) {
            addCriterion("Enterprise_User_Id <>", value, "enterprise_User_Id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdGreaterThan(Integer value) {
            addCriterion("Enterprise_User_Id >", value, "enterprise_User_Id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Enterprise_User_Id >=", value, "enterprise_User_Id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdLessThan(Integer value) {
            addCriterion("Enterprise_User_Id <", value, "enterprise_User_Id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdLessThanOrEqualTo(Integer value) {
            addCriterion("Enterprise_User_Id <=", value, "enterprise_User_Id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdIn(List<Integer> values) {
            addCriterion("Enterprise_User_Id in", values, "enterprise_User_Id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdNotIn(List<Integer> values) {
            addCriterion("Enterprise_User_Id not in", values, "enterprise_User_Id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdBetween(Integer value1, Integer value2) {
            addCriterion("Enterprise_User_Id between", value1, value2, "enterprise_User_Id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdNotBetween(Integer value1, Integer value2) {
            addCriterion("Enterprise_User_Id not between", value1, value2, "enterprise_User_Id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NameIsNull() {
            addCriterion("Enterprise_Name is null");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NameIsNotNull() {
            addCriterion("Enterprise_Name is not null");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NameEqualTo(String value) {
            addCriterion("Enterprise_Name =", value, "enterprise_Name");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NameNotEqualTo(String value) {
            addCriterion("Enterprise_Name <>", value, "enterprise_Name");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NameGreaterThan(String value) {
            addCriterion("Enterprise_Name >", value, "enterprise_Name");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NameGreaterThanOrEqualTo(String value) {
            addCriterion("Enterprise_Name >=", value, "enterprise_Name");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NameLessThan(String value) {
            addCriterion("Enterprise_Name <", value, "enterprise_Name");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NameLessThanOrEqualTo(String value) {
            addCriterion("Enterprise_Name <=", value, "enterprise_Name");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NameLike(String value) {
            addCriterion("Enterprise_Name like", value, "enterprise_Name");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NameNotLike(String value) {
            addCriterion("Enterprise_Name not like", value, "enterprise_Name");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NameIn(List<String> values) {
            addCriterion("Enterprise_Name in", values, "enterprise_Name");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NameNotIn(List<String> values) {
            addCriterion("Enterprise_Name not in", values, "enterprise_Name");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NameBetween(String value1, String value2) {
            addCriterion("Enterprise_Name between", value1, value2, "enterprise_Name");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NameNotBetween(String value1, String value2) {
            addCriterion("Enterprise_Name not between", value1, value2, "enterprise_Name");
            return (Criteria) this;
        }

        public Criteria andOrder_NoIsNull() {
            addCriterion("Order_No is null");
            return (Criteria) this;
        }

        public Criteria andOrder_NoIsNotNull() {
            addCriterion("Order_No is not null");
            return (Criteria) this;
        }

        public Criteria andOrder_NoEqualTo(String value) {
            addCriterion("Order_No =", value, "order_No");
            return (Criteria) this;
        }

        public Criteria andOrder_NoNotEqualTo(String value) {
            addCriterion("Order_No <>", value, "order_No");
            return (Criteria) this;
        }

        public Criteria andOrder_NoGreaterThan(String value) {
            addCriterion("Order_No >", value, "order_No");
            return (Criteria) this;
        }

        public Criteria andOrder_NoGreaterThanOrEqualTo(String value) {
            addCriterion("Order_No >=", value, "order_No");
            return (Criteria) this;
        }

        public Criteria andOrder_NoLessThan(String value) {
            addCriterion("Order_No <", value, "order_No");
            return (Criteria) this;
        }

        public Criteria andOrder_NoLessThanOrEqualTo(String value) {
            addCriterion("Order_No <=", value, "order_No");
            return (Criteria) this;
        }

        public Criteria andOrder_NoLike(String value) {
            addCriterion("Order_No like", value, "order_No");
            return (Criteria) this;
        }

        public Criteria andOrder_NoNotLike(String value) {
            addCriterion("Order_No not like", value, "order_No");
            return (Criteria) this;
        }

        public Criteria andOrder_NoIn(List<String> values) {
            addCriterion("Order_No in", values, "order_No");
            return (Criteria) this;
        }

        public Criteria andOrder_NoNotIn(List<String> values) {
            addCriterion("Order_No not in", values, "order_No");
            return (Criteria) this;
        }

        public Criteria andOrder_NoBetween(String value1, String value2) {
            addCriterion("Order_No between", value1, value2, "order_No");
            return (Criteria) this;
        }

        public Criteria andOrder_NoNotBetween(String value1, String value2) {
            addCriterion("Order_No not between", value1, value2, "order_No");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNull() {
            addCriterion("Money is null");
            return (Criteria) this;
        }

        public Criteria andMoneyIsNotNull() {
            addCriterion("Money is not null");
            return (Criteria) this;
        }

        public Criteria andMoneyEqualTo(BigDecimal value) {
            addCriterion("Money =", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotEqualTo(BigDecimal value) {
            addCriterion("Money <>", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThan(BigDecimal value) {
            addCriterion("Money >", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Money >=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThan(BigDecimal value) {
            addCriterion("Money <", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Money <=", value, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyIn(List<BigDecimal> values) {
            addCriterion("Money in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotIn(List<BigDecimal> values) {
            addCriterion("Money not in", values, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Money between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Money not between", value1, value2, "money");
            return (Criteria) this;
        }

        public Criteria andBefore_MoneyIsNull() {
            addCriterion("Before_Money is null");
            return (Criteria) this;
        }

        public Criteria andBefore_MoneyIsNotNull() {
            addCriterion("Before_Money is not null");
            return (Criteria) this;
        }

        public Criteria andBefore_MoneyEqualTo(BigDecimal value) {
            addCriterion("Before_Money =", value, "before_Money");
            return (Criteria) this;
        }

        public Criteria andBefore_MoneyNotEqualTo(BigDecimal value) {
            addCriterion("Before_Money <>", value, "before_Money");
            return (Criteria) this;
        }

        public Criteria andBefore_MoneyGreaterThan(BigDecimal value) {
            addCriterion("Before_Money >", value, "before_Money");
            return (Criteria) this;
        }

        public Criteria andBefore_MoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Before_Money >=", value, "before_Money");
            return (Criteria) this;
        }

        public Criteria andBefore_MoneyLessThan(BigDecimal value) {
            addCriterion("Before_Money <", value, "before_Money");
            return (Criteria) this;
        }

        public Criteria andBefore_MoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Before_Money <=", value, "before_Money");
            return (Criteria) this;
        }

        public Criteria andBefore_MoneyIn(List<BigDecimal> values) {
            addCriterion("Before_Money in", values, "before_Money");
            return (Criteria) this;
        }

        public Criteria andBefore_MoneyNotIn(List<BigDecimal> values) {
            addCriterion("Before_Money not in", values, "before_Money");
            return (Criteria) this;
        }

        public Criteria andBefore_MoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Before_Money between", value1, value2, "before_Money");
            return (Criteria) this;
        }

        public Criteria andBefore_MoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Before_Money not between", value1, value2, "before_Money");
            return (Criteria) this;
        }

        public Criteria andUnit_PriceIsNull() {
            addCriterion("Unit_Price is null");
            return (Criteria) this;
        }

        public Criteria andUnit_PriceIsNotNull() {
            addCriterion("Unit_Price is not null");
            return (Criteria) this;
        }

        public Criteria andUnit_PriceEqualTo(BigDecimal value) {
            addCriterion("Unit_Price =", value, "unit_Price");
            return (Criteria) this;
        }

        public Criteria andUnit_PriceNotEqualTo(BigDecimal value) {
            addCriterion("Unit_Price <>", value, "unit_Price");
            return (Criteria) this;
        }

        public Criteria andUnit_PriceGreaterThan(BigDecimal value) {
            addCriterion("Unit_Price >", value, "unit_Price");
            return (Criteria) this;
        }

        public Criteria andUnit_PriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Unit_Price >=", value, "unit_Price");
            return (Criteria) this;
        }

        public Criteria andUnit_PriceLessThan(BigDecimal value) {
            addCriterion("Unit_Price <", value, "unit_Price");
            return (Criteria) this;
        }

        public Criteria andUnit_PriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Unit_Price <=", value, "unit_Price");
            return (Criteria) this;
        }

        public Criteria andUnit_PriceIn(List<BigDecimal> values) {
            addCriterion("Unit_Price in", values, "unit_Price");
            return (Criteria) this;
        }

        public Criteria andUnit_PriceNotIn(List<BigDecimal> values) {
            addCriterion("Unit_Price not in", values, "unit_Price");
            return (Criteria) this;
        }

        public Criteria andUnit_PriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Unit_Price between", value1, value2, "unit_Price");
            return (Criteria) this;
        }

        public Criteria andUnit_PriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Unit_Price not between", value1, value2, "unit_Price");
            return (Criteria) this;
        }

        public Criteria andMoney_LetterIsNull() {
            addCriterion("Money_Letter is null");
            return (Criteria) this;
        }

        public Criteria andMoney_LetterIsNotNull() {
            addCriterion("Money_Letter is not null");
            return (Criteria) this;
        }

        public Criteria andMoney_LetterEqualTo(String value) {
            addCriterion("Money_Letter =", value, "money_Letter");
            return (Criteria) this;
        }

        public Criteria andMoney_LetterNotEqualTo(String value) {
            addCriterion("Money_Letter <>", value, "money_Letter");
            return (Criteria) this;
        }

        public Criteria andMoney_LetterGreaterThan(String value) {
            addCriterion("Money_Letter >", value, "money_Letter");
            return (Criteria) this;
        }

        public Criteria andMoney_LetterGreaterThanOrEqualTo(String value) {
            addCriterion("Money_Letter >=", value, "money_Letter");
            return (Criteria) this;
        }

        public Criteria andMoney_LetterLessThan(String value) {
            addCriterion("Money_Letter <", value, "money_Letter");
            return (Criteria) this;
        }

        public Criteria andMoney_LetterLessThanOrEqualTo(String value) {
            addCriterion("Money_Letter <=", value, "money_Letter");
            return (Criteria) this;
        }

        public Criteria andMoney_LetterLike(String value) {
            addCriterion("Money_Letter like", value, "money_Letter");
            return (Criteria) this;
        }

        public Criteria andMoney_LetterNotLike(String value) {
            addCriterion("Money_Letter not like", value, "money_Letter");
            return (Criteria) this;
        }

        public Criteria andMoney_LetterIn(List<String> values) {
            addCriterion("Money_Letter in", values, "money_Letter");
            return (Criteria) this;
        }

        public Criteria andMoney_LetterNotIn(List<String> values) {
            addCriterion("Money_Letter not in", values, "money_Letter");
            return (Criteria) this;
        }

        public Criteria andMoney_LetterBetween(String value1, String value2) {
            addCriterion("Money_Letter between", value1, value2, "money_Letter");
            return (Criteria) this;
        }

        public Criteria andMoney_LetterNotBetween(String value1, String value2) {
            addCriterion("Money_Letter not between", value1, value2, "money_Letter");
            return (Criteria) this;
        }

        public Criteria andPay_Type_CodeIsNull() {
            addCriterion("Pay_Type_Code is null");
            return (Criteria) this;
        }

        public Criteria andPay_Type_CodeIsNotNull() {
            addCriterion("Pay_Type_Code is not null");
            return (Criteria) this;
        }

        public Criteria andPay_Type_CodeEqualTo(String value) {
            addCriterion("Pay_Type_Code =", value, "pay_Type_Code");
            return (Criteria) this;
        }

        public Criteria andPay_Type_CodeNotEqualTo(String value) {
            addCriterion("Pay_Type_Code <>", value, "pay_Type_Code");
            return (Criteria) this;
        }

        public Criteria andPay_Type_CodeGreaterThan(String value) {
            addCriterion("Pay_Type_Code >", value, "pay_Type_Code");
            return (Criteria) this;
        }

        public Criteria andPay_Type_CodeGreaterThanOrEqualTo(String value) {
            addCriterion("Pay_Type_Code >=", value, "pay_Type_Code");
            return (Criteria) this;
        }

        public Criteria andPay_Type_CodeLessThan(String value) {
            addCriterion("Pay_Type_Code <", value, "pay_Type_Code");
            return (Criteria) this;
        }

        public Criteria andPay_Type_CodeLessThanOrEqualTo(String value) {
            addCriterion("Pay_Type_Code <=", value, "pay_Type_Code");
            return (Criteria) this;
        }

        public Criteria andPay_Type_CodeLike(String value) {
            addCriterion("Pay_Type_Code like", value, "pay_Type_Code");
            return (Criteria) this;
        }

        public Criteria andPay_Type_CodeNotLike(String value) {
            addCriterion("Pay_Type_Code not like", value, "pay_Type_Code");
            return (Criteria) this;
        }

        public Criteria andPay_Type_CodeIn(List<String> values) {
            addCriterion("Pay_Type_Code in", values, "pay_Type_Code");
            return (Criteria) this;
        }

        public Criteria andPay_Type_CodeNotIn(List<String> values) {
            addCriterion("Pay_Type_Code not in", values, "pay_Type_Code");
            return (Criteria) this;
        }

        public Criteria andPay_Type_CodeBetween(String value1, String value2) {
            addCriterion("Pay_Type_Code between", value1, value2, "pay_Type_Code");
            return (Criteria) this;
        }

        public Criteria andPay_Type_CodeNotBetween(String value1, String value2) {
            addCriterion("Pay_Type_Code not between", value1, value2, "pay_Type_Code");
            return (Criteria) this;
        }

        public Criteria andPay_StatusIsNull() {
            addCriterion("Pay_Status is null");
            return (Criteria) this;
        }

        public Criteria andPay_StatusIsNotNull() {
            addCriterion("Pay_Status is not null");
            return (Criteria) this;
        }

        public Criteria andPay_StatusEqualTo(String value) {
            addCriterion("Pay_Status =", value, "pay_Status");
            return (Criteria) this;
        }

        public Criteria andPay_StatusNotEqualTo(String value) {
            addCriterion("Pay_Status <>", value, "pay_Status");
            return (Criteria) this;
        }

        public Criteria andPay_StatusGreaterThan(String value) {
            addCriterion("Pay_Status >", value, "pay_Status");
            return (Criteria) this;
        }

        public Criteria andPay_StatusGreaterThanOrEqualTo(String value) {
            addCriterion("Pay_Status >=", value, "pay_Status");
            return (Criteria) this;
        }

        public Criteria andPay_StatusLessThan(String value) {
            addCriterion("Pay_Status <", value, "pay_Status");
            return (Criteria) this;
        }

        public Criteria andPay_StatusLessThanOrEqualTo(String value) {
            addCriterion("Pay_Status <=", value, "pay_Status");
            return (Criteria) this;
        }

        public Criteria andPay_StatusLike(String value) {
            addCriterion("Pay_Status like", value, "pay_Status");
            return (Criteria) this;
        }

        public Criteria andPay_StatusNotLike(String value) {
            addCriterion("Pay_Status not like", value, "pay_Status");
            return (Criteria) this;
        }

        public Criteria andPay_StatusIn(List<String> values) {
            addCriterion("Pay_Status in", values, "pay_Status");
            return (Criteria) this;
        }

        public Criteria andPay_StatusNotIn(List<String> values) {
            addCriterion("Pay_Status not in", values, "pay_Status");
            return (Criteria) this;
        }

        public Criteria andPay_StatusBetween(String value1, String value2) {
            addCriterion("Pay_Status between", value1, value2, "pay_Status");
            return (Criteria) this;
        }

        public Criteria andPay_StatusNotBetween(String value1, String value2) {
            addCriterion("Pay_Status not between", value1, value2, "pay_Status");
            return (Criteria) this;
        }

        public Criteria andVoucher_UrlIsNull() {
            addCriterion("Voucher_Url is null");
            return (Criteria) this;
        }

        public Criteria andVoucher_UrlIsNotNull() {
            addCriterion("Voucher_Url is not null");
            return (Criteria) this;
        }

        public Criteria andVoucher_UrlEqualTo(String value) {
            addCriterion("Voucher_Url =", value, "voucher_Url");
            return (Criteria) this;
        }

        public Criteria andVoucher_UrlNotEqualTo(String value) {
            addCriterion("Voucher_Url <>", value, "voucher_Url");
            return (Criteria) this;
        }

        public Criteria andVoucher_UrlGreaterThan(String value) {
            addCriterion("Voucher_Url >", value, "voucher_Url");
            return (Criteria) this;
        }

        public Criteria andVoucher_UrlGreaterThanOrEqualTo(String value) {
            addCriterion("Voucher_Url >=", value, "voucher_Url");
            return (Criteria) this;
        }

        public Criteria andVoucher_UrlLessThan(String value) {
            addCriterion("Voucher_Url <", value, "voucher_Url");
            return (Criteria) this;
        }

        public Criteria andVoucher_UrlLessThanOrEqualTo(String value) {
            addCriterion("Voucher_Url <=", value, "voucher_Url");
            return (Criteria) this;
        }

        public Criteria andVoucher_UrlLike(String value) {
            addCriterion("Voucher_Url like", value, "voucher_Url");
            return (Criteria) this;
        }

        public Criteria andVoucher_UrlNotLike(String value) {
            addCriterion("Voucher_Url not like", value, "voucher_Url");
            return (Criteria) this;
        }

        public Criteria andVoucher_UrlIn(List<String> values) {
            addCriterion("Voucher_Url in", values, "voucher_Url");
            return (Criteria) this;
        }

        public Criteria andVoucher_UrlNotIn(List<String> values) {
            addCriterion("Voucher_Url not in", values, "voucher_Url");
            return (Criteria) this;
        }

        public Criteria andVoucher_UrlBetween(String value1, String value2) {
            addCriterion("Voucher_Url between", value1, value2, "voucher_Url");
            return (Criteria) this;
        }

        public Criteria andVoucher_UrlNotBetween(String value1, String value2) {
            addCriterion("Voucher_Url not between", value1, value2, "voucher_Url");
            return (Criteria) this;
        }

        public Criteria andTransfer_ImgIsNull() {
            addCriterion("Transfer_Img is null");
            return (Criteria) this;
        }

        public Criteria andTransfer_ImgIsNotNull() {
            addCriterion("Transfer_Img is not null");
            return (Criteria) this;
        }

        public Criteria andTransfer_ImgEqualTo(String value) {
            addCriterion("Transfer_Img =", value, "transfer_Img");
            return (Criteria) this;
        }

        public Criteria andTransfer_ImgNotEqualTo(String value) {
            addCriterion("Transfer_Img <>", value, "transfer_Img");
            return (Criteria) this;
        }

        public Criteria andTransfer_ImgGreaterThan(String value) {
            addCriterion("Transfer_Img >", value, "transfer_Img");
            return (Criteria) this;
        }

        public Criteria andTransfer_ImgGreaterThanOrEqualTo(String value) {
            addCriterion("Transfer_Img >=", value, "transfer_Img");
            return (Criteria) this;
        }

        public Criteria andTransfer_ImgLessThan(String value) {
            addCriterion("Transfer_Img <", value, "transfer_Img");
            return (Criteria) this;
        }

        public Criteria andTransfer_ImgLessThanOrEqualTo(String value) {
            addCriterion("Transfer_Img <=", value, "transfer_Img");
            return (Criteria) this;
        }

        public Criteria andTransfer_ImgLike(String value) {
            addCriterion("Transfer_Img like", value, "transfer_Img");
            return (Criteria) this;
        }

        public Criteria andTransfer_ImgNotLike(String value) {
            addCriterion("Transfer_Img not like", value, "transfer_Img");
            return (Criteria) this;
        }

        public Criteria andTransfer_ImgIn(List<String> values) {
            addCriterion("Transfer_Img in", values, "transfer_Img");
            return (Criteria) this;
        }

        public Criteria andTransfer_ImgNotIn(List<String> values) {
            addCriterion("Transfer_Img not in", values, "transfer_Img");
            return (Criteria) this;
        }

        public Criteria andTransfer_ImgBetween(String value1, String value2) {
            addCriterion("Transfer_Img between", value1, value2, "transfer_Img");
            return (Criteria) this;
        }

        public Criteria andTransfer_ImgNotBetween(String value1, String value2) {
            addCriterion("Transfer_Img not between", value1, value2, "transfer_Img");
            return (Criteria) this;
        }

        public Criteria andInput_DateIsNull() {
            addCriterion("Input_Date is null");
            return (Criteria) this;
        }

        public Criteria andInput_DateIsNotNull() {
            addCriterion("Input_Date is not null");
            return (Criteria) this;
        }

        public Criteria andInput_DateEqualTo(Date value) {
            addCriterion("Input_Date =", value, "input_Date");
            return (Criteria) this;
        }

        public Criteria andInput_DateNotEqualTo(Date value) {
            addCriterion("Input_Date <>", value, "input_Date");
            return (Criteria) this;
        }

        public Criteria andInput_DateGreaterThan(Date value) {
            addCriterion("Input_Date >", value, "input_Date");
            return (Criteria) this;
        }

        public Criteria andInput_DateGreaterThanOrEqualTo(Date value) {
            addCriterion("Input_Date >=", value, "input_Date");
            return (Criteria) this;
        }

        public Criteria andInput_DateLessThan(Date value) {
            addCriterion("Input_Date <", value, "input_Date");
            return (Criteria) this;
        }

        public Criteria andInput_DateLessThanOrEqualTo(Date value) {
            addCriterion("Input_Date <=", value, "input_Date");
            return (Criteria) this;
        }

        public Criteria andInput_DateIn(List<Date> values) {
            addCriterion("Input_Date in", values, "input_Date");
            return (Criteria) this;
        }

        public Criteria andInput_DateNotIn(List<Date> values) {
            addCriterion("Input_Date not in", values, "input_Date");
            return (Criteria) this;
        }

        public Criteria andInput_DateBetween(Date value1, Date value2) {
            addCriterion("Input_Date between", value1, value2, "input_Date");
            return (Criteria) this;
        }

        public Criteria andInput_DateNotBetween(Date value1, Date value2) {
            addCriterion("Input_Date not between", value1, value2, "input_Date");
            return (Criteria) this;
        }

        public Criteria andInput_UserIsNull() {
            addCriterion("Input_User is null");
            return (Criteria) this;
        }

        public Criteria andInput_UserIsNotNull() {
            addCriterion("Input_User is not null");
            return (Criteria) this;
        }

        public Criteria andInput_UserEqualTo(String value) {
            addCriterion("Input_User =", value, "input_User");
            return (Criteria) this;
        }

        public Criteria andInput_UserNotEqualTo(String value) {
            addCriterion("Input_User <>", value, "input_User");
            return (Criteria) this;
        }

        public Criteria andInput_UserGreaterThan(String value) {
            addCriterion("Input_User >", value, "input_User");
            return (Criteria) this;
        }

        public Criteria andInput_UserGreaterThanOrEqualTo(String value) {
            addCriterion("Input_User >=", value, "input_User");
            return (Criteria) this;
        }

        public Criteria andInput_UserLessThan(String value) {
            addCriterion("Input_User <", value, "input_User");
            return (Criteria) this;
        }

        public Criteria andInput_UserLessThanOrEqualTo(String value) {
            addCriterion("Input_User <=", value, "input_User");
            return (Criteria) this;
        }

        public Criteria andInput_UserLike(String value) {
            addCriterion("Input_User like", value, "input_User");
            return (Criteria) this;
        }

        public Criteria andInput_UserNotLike(String value) {
            addCriterion("Input_User not like", value, "input_User");
            return (Criteria) this;
        }

        public Criteria andInput_UserIn(List<String> values) {
            addCriterion("Input_User in", values, "input_User");
            return (Criteria) this;
        }

        public Criteria andInput_UserNotIn(List<String> values) {
            addCriterion("Input_User not in", values, "input_User");
            return (Criteria) this;
        }

        public Criteria andInput_UserBetween(String value1, String value2) {
            addCriterion("Input_User between", value1, value2, "input_User");
            return (Criteria) this;
        }

        public Criteria andInput_UserNotBetween(String value1, String value2) {
            addCriterion("Input_User not between", value1, value2, "input_User");
            return (Criteria) this;
        }

        public Criteria andInput_User_IdIsNull() {
            addCriterion("Input_User_Id is null");
            return (Criteria) this;
        }

        public Criteria andInput_User_IdIsNotNull() {
            addCriterion("Input_User_Id is not null");
            return (Criteria) this;
        }

        public Criteria andInput_User_IdEqualTo(Integer value) {
            addCriterion("Input_User_Id =", value, "input_User_Id");
            return (Criteria) this;
        }

        public Criteria andInput_User_IdNotEqualTo(Integer value) {
            addCriterion("Input_User_Id <>", value, "input_User_Id");
            return (Criteria) this;
        }

        public Criteria andInput_User_IdGreaterThan(Integer value) {
            addCriterion("Input_User_Id >", value, "input_User_Id");
            return (Criteria) this;
        }

        public Criteria andInput_User_IdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Input_User_Id >=", value, "input_User_Id");
            return (Criteria) this;
        }

        public Criteria andInput_User_IdLessThan(Integer value) {
            addCriterion("Input_User_Id <", value, "input_User_Id");
            return (Criteria) this;
        }

        public Criteria andInput_User_IdLessThanOrEqualTo(Integer value) {
            addCriterion("Input_User_Id <=", value, "input_User_Id");
            return (Criteria) this;
        }

        public Criteria andInput_User_IdIn(List<Integer> values) {
            addCriterion("Input_User_Id in", values, "input_User_Id");
            return (Criteria) this;
        }

        public Criteria andInput_User_IdNotIn(List<Integer> values) {
            addCriterion("Input_User_Id not in", values, "input_User_Id");
            return (Criteria) this;
        }

        public Criteria andInput_User_IdBetween(Integer value1, Integer value2) {
            addCriterion("Input_User_Id between", value1, value2, "input_User_Id");
            return (Criteria) this;
        }

        public Criteria andInput_User_IdNotBetween(Integer value1, Integer value2) {
            addCriterion("Input_User_Id not between", value1, value2, "input_User_Id");
            return (Criteria) this;
        }

        public Criteria andInput_RemarkIsNull() {
            addCriterion("Input_Remark is null");
            return (Criteria) this;
        }

        public Criteria andInput_RemarkIsNotNull() {
            addCriterion("Input_Remark is not null");
            return (Criteria) this;
        }

        public Criteria andInput_RemarkEqualTo(String value) {
            addCriterion("Input_Remark =", value, "input_Remark");
            return (Criteria) this;
        }

        public Criteria andInput_RemarkNotEqualTo(String value) {
            addCriterion("Input_Remark <>", value, "input_Remark");
            return (Criteria) this;
        }

        public Criteria andInput_RemarkGreaterThan(String value) {
            addCriterion("Input_Remark >", value, "input_Remark");
            return (Criteria) this;
        }

        public Criteria andInput_RemarkGreaterThanOrEqualTo(String value) {
            addCriterion("Input_Remark >=", value, "input_Remark");
            return (Criteria) this;
        }

        public Criteria andInput_RemarkLessThan(String value) {
            addCriterion("Input_Remark <", value, "input_Remark");
            return (Criteria) this;
        }

        public Criteria andInput_RemarkLessThanOrEqualTo(String value) {
            addCriterion("Input_Remark <=", value, "input_Remark");
            return (Criteria) this;
        }

        public Criteria andInput_RemarkLike(String value) {
            addCriterion("Input_Remark like", value, "input_Remark");
            return (Criteria) this;
        }

        public Criteria andInput_RemarkNotLike(String value) {
            addCriterion("Input_Remark not like", value, "input_Remark");
            return (Criteria) this;
        }

        public Criteria andInput_RemarkIn(List<String> values) {
            addCriterion("Input_Remark in", values, "input_Remark");
            return (Criteria) this;
        }

        public Criteria andInput_RemarkNotIn(List<String> values) {
            addCriterion("Input_Remark not in", values, "input_Remark");
            return (Criteria) this;
        }

        public Criteria andInput_RemarkBetween(String value1, String value2) {
            addCriterion("Input_Remark between", value1, value2, "input_Remark");
            return (Criteria) this;
        }

        public Criteria andInput_RemarkNotBetween(String value1, String value2) {
            addCriterion("Input_Remark not between", value1, value2, "input_Remark");
            return (Criteria) this;
        }

        public Criteria andApprove_DateIsNull() {
            addCriterion("Approve_Date is null");
            return (Criteria) this;
        }

        public Criteria andApprove_DateIsNotNull() {
            addCriterion("Approve_Date is not null");
            return (Criteria) this;
        }

        public Criteria andApprove_DateEqualTo(Date value) {
            addCriterion("Approve_Date =", value, "approve_Date");
            return (Criteria) this;
        }

        public Criteria andApprove_DateNotEqualTo(Date value) {
            addCriterion("Approve_Date <>", value, "approve_Date");
            return (Criteria) this;
        }

        public Criteria andApprove_DateGreaterThan(Date value) {
            addCriterion("Approve_Date >", value, "approve_Date");
            return (Criteria) this;
        }

        public Criteria andApprove_DateGreaterThanOrEqualTo(Date value) {
            addCriterion("Approve_Date >=", value, "approve_Date");
            return (Criteria) this;
        }

        public Criteria andApprove_DateLessThan(Date value) {
            addCriterion("Approve_Date <", value, "approve_Date");
            return (Criteria) this;
        }

        public Criteria andApprove_DateLessThanOrEqualTo(Date value) {
            addCriterion("Approve_Date <=", value, "approve_Date");
            return (Criteria) this;
        }

        public Criteria andApprove_DateIn(List<Date> values) {
            addCriterion("Approve_Date in", values, "approve_Date");
            return (Criteria) this;
        }

        public Criteria andApprove_DateNotIn(List<Date> values) {
            addCriterion("Approve_Date not in", values, "approve_Date");
            return (Criteria) this;
        }

        public Criteria andApprove_DateBetween(Date value1, Date value2) {
            addCriterion("Approve_Date between", value1, value2, "approve_Date");
            return (Criteria) this;
        }

        public Criteria andApprove_DateNotBetween(Date value1, Date value2) {
            addCriterion("Approve_Date not between", value1, value2, "approve_Date");
            return (Criteria) this;
        }

        public Criteria andApprove_UserIsNull() {
            addCriterion("Approve_User is null");
            return (Criteria) this;
        }

        public Criteria andApprove_UserIsNotNull() {
            addCriterion("Approve_User is not null");
            return (Criteria) this;
        }

        public Criteria andApprove_UserEqualTo(String value) {
            addCriterion("Approve_User =", value, "approve_User");
            return (Criteria) this;
        }

        public Criteria andApprove_UserNotEqualTo(String value) {
            addCriterion("Approve_User <>", value, "approve_User");
            return (Criteria) this;
        }

        public Criteria andApprove_UserGreaterThan(String value) {
            addCriterion("Approve_User >", value, "approve_User");
            return (Criteria) this;
        }

        public Criteria andApprove_UserGreaterThanOrEqualTo(String value) {
            addCriterion("Approve_User >=", value, "approve_User");
            return (Criteria) this;
        }

        public Criteria andApprove_UserLessThan(String value) {
            addCriterion("Approve_User <", value, "approve_User");
            return (Criteria) this;
        }

        public Criteria andApprove_UserLessThanOrEqualTo(String value) {
            addCriterion("Approve_User <=", value, "approve_User");
            return (Criteria) this;
        }

        public Criteria andApprove_UserLike(String value) {
            addCriterion("Approve_User like", value, "approve_User");
            return (Criteria) this;
        }

        public Criteria andApprove_UserNotLike(String value) {
            addCriterion("Approve_User not like", value, "approve_User");
            return (Criteria) this;
        }

        public Criteria andApprove_UserIn(List<String> values) {
            addCriterion("Approve_User in", values, "approve_User");
            return (Criteria) this;
        }

        public Criteria andApprove_UserNotIn(List<String> values) {
            addCriterion("Approve_User not in", values, "approve_User");
            return (Criteria) this;
        }

        public Criteria andApprove_UserBetween(String value1, String value2) {
            addCriterion("Approve_User between", value1, value2, "approve_User");
            return (Criteria) this;
        }

        public Criteria andApprove_UserNotBetween(String value1, String value2) {
            addCriterion("Approve_User not between", value1, value2, "approve_User");
            return (Criteria) this;
        }

        public Criteria andApprove_Status_CodeIsNull() {
            addCriterion("Approve_Status_Code is null");
            return (Criteria) this;
        }

        public Criteria andApprove_Status_CodeIsNotNull() {
            addCriterion("Approve_Status_Code is not null");
            return (Criteria) this;
        }

        public Criteria andApprove_Status_CodeEqualTo(String value) {
            addCriterion("Approve_Status_Code =", value, "approve_Status_Code");
            return (Criteria) this;
        }

        public Criteria andApprove_Status_CodeNotEqualTo(String value) {
            addCriterion("Approve_Status_Code <>", value, "approve_Status_Code");
            return (Criteria) this;
        }

        public Criteria andApprove_Status_CodeGreaterThan(String value) {
            addCriterion("Approve_Status_Code >", value, "approve_Status_Code");
            return (Criteria) this;
        }

        public Criteria andApprove_Status_CodeGreaterThanOrEqualTo(String value) {
            addCriterion("Approve_Status_Code >=", value, "approve_Status_Code");
            return (Criteria) this;
        }

        public Criteria andApprove_Status_CodeLessThan(String value) {
            addCriterion("Approve_Status_Code <", value, "approve_Status_Code");
            return (Criteria) this;
        }

        public Criteria andApprove_Status_CodeLessThanOrEqualTo(String value) {
            addCriterion("Approve_Status_Code <=", value, "approve_Status_Code");
            return (Criteria) this;
        }

        public Criteria andApprove_Status_CodeLike(String value) {
            addCriterion("Approve_Status_Code like", value, "approve_Status_Code");
            return (Criteria) this;
        }

        public Criteria andApprove_Status_CodeNotLike(String value) {
            addCriterion("Approve_Status_Code not like", value, "approve_Status_Code");
            return (Criteria) this;
        }

        public Criteria andApprove_Status_CodeIn(List<String> values) {
            addCriterion("Approve_Status_Code in", values, "approve_Status_Code");
            return (Criteria) this;
        }

        public Criteria andApprove_Status_CodeNotIn(List<String> values) {
            addCriterion("Approve_Status_Code not in", values, "approve_Status_Code");
            return (Criteria) this;
        }

        public Criteria andApprove_Status_CodeBetween(String value1, String value2) {
            addCriterion("Approve_Status_Code between", value1, value2, "approve_Status_Code");
            return (Criteria) this;
        }

        public Criteria andApprove_Status_CodeNotBetween(String value1, String value2) {
            addCriterion("Approve_Status_Code not between", value1, value2, "approve_Status_Code");
            return (Criteria) this;
        }

        public Criteria andApprove_RemarkIsNull() {
            addCriterion("Approve_Remark is null");
            return (Criteria) this;
        }

        public Criteria andApprove_RemarkIsNotNull() {
            addCriterion("Approve_Remark is not null");
            return (Criteria) this;
        }

        public Criteria andApprove_RemarkEqualTo(String value) {
            addCriterion("Approve_Remark =", value, "approve_Remark");
            return (Criteria) this;
        }

        public Criteria andApprove_RemarkNotEqualTo(String value) {
            addCriterion("Approve_Remark <>", value, "approve_Remark");
            return (Criteria) this;
        }

        public Criteria andApprove_RemarkGreaterThan(String value) {
            addCriterion("Approve_Remark >", value, "approve_Remark");
            return (Criteria) this;
        }

        public Criteria andApprove_RemarkGreaterThanOrEqualTo(String value) {
            addCriterion("Approve_Remark >=", value, "approve_Remark");
            return (Criteria) this;
        }

        public Criteria andApprove_RemarkLessThan(String value) {
            addCriterion("Approve_Remark <", value, "approve_Remark");
            return (Criteria) this;
        }

        public Criteria andApprove_RemarkLessThanOrEqualTo(String value) {
            addCriterion("Approve_Remark <=", value, "approve_Remark");
            return (Criteria) this;
        }

        public Criteria andApprove_RemarkLike(String value) {
            addCriterion("Approve_Remark like", value, "approve_Remark");
            return (Criteria) this;
        }

        public Criteria andApprove_RemarkNotLike(String value) {
            addCriterion("Approve_Remark not like", value, "approve_Remark");
            return (Criteria) this;
        }

        public Criteria andApprove_RemarkIn(List<String> values) {
            addCriterion("Approve_Remark in", values, "approve_Remark");
            return (Criteria) this;
        }

        public Criteria andApprove_RemarkNotIn(List<String> values) {
            addCriterion("Approve_Remark not in", values, "approve_Remark");
            return (Criteria) this;
        }

        public Criteria andApprove_RemarkBetween(String value1, String value2) {
            addCriterion("Approve_Remark between", value1, value2, "approve_Remark");
            return (Criteria) this;
        }

        public Criteria andApprove_RemarkNotBetween(String value1, String value2) {
            addCriterion("Approve_Remark not between", value1, value2, "approve_Remark");
            return (Criteria) this;
        }

        public Criteria andOpen_DateIsNull() {
            addCriterion("Open_Date is null");
            return (Criteria) this;
        }

        public Criteria andOpen_DateIsNotNull() {
            addCriterion("Open_Date is not null");
            return (Criteria) this;
        }

        public Criteria andOpen_DateEqualTo(Date value) {
            addCriterion("Open_Date =", value, "open_Date");
            return (Criteria) this;
        }

        public Criteria andOpen_DateNotEqualTo(Date value) {
            addCriterion("Open_Date <>", value, "open_Date");
            return (Criteria) this;
        }

        public Criteria andOpen_DateGreaterThan(Date value) {
            addCriterion("Open_Date >", value, "open_Date");
            return (Criteria) this;
        }

        public Criteria andOpen_DateGreaterThanOrEqualTo(Date value) {
            addCriterion("Open_Date >=", value, "open_Date");
            return (Criteria) this;
        }

        public Criteria andOpen_DateLessThan(Date value) {
            addCriterion("Open_Date <", value, "open_Date");
            return (Criteria) this;
        }

        public Criteria andOpen_DateLessThanOrEqualTo(Date value) {
            addCriterion("Open_Date <=", value, "open_Date");
            return (Criteria) this;
        }

        public Criteria andOpen_DateIn(List<Date> values) {
            addCriterion("Open_Date in", values, "open_Date");
            return (Criteria) this;
        }

        public Criteria andOpen_DateNotIn(List<Date> values) {
            addCriterion("Open_Date not in", values, "open_Date");
            return (Criteria) this;
        }

        public Criteria andOpen_DateBetween(Date value1, Date value2) {
            addCriterion("Open_Date between", value1, value2, "open_Date");
            return (Criteria) this;
        }

        public Criteria andOpen_DateNotBetween(Date value1, Date value2) {
            addCriterion("Open_Date not between", value1, value2, "open_Date");
            return (Criteria) this;
        }

        public Criteria andOpen_UserIsNull() {
            addCriterion("Open_User is null");
            return (Criteria) this;
        }

        public Criteria andOpen_UserIsNotNull() {
            addCriterion("Open_User is not null");
            return (Criteria) this;
        }

        public Criteria andOpen_UserEqualTo(String value) {
            addCriterion("Open_User =", value, "open_User");
            return (Criteria) this;
        }

        public Criteria andOpen_UserNotEqualTo(String value) {
            addCriterion("Open_User <>", value, "open_User");
            return (Criteria) this;
        }

        public Criteria andOpen_UserGreaterThan(String value) {
            addCriterion("Open_User >", value, "open_User");
            return (Criteria) this;
        }

        public Criteria andOpen_UserGreaterThanOrEqualTo(String value) {
            addCriterion("Open_User >=", value, "open_User");
            return (Criteria) this;
        }

        public Criteria andOpen_UserLessThan(String value) {
            addCriterion("Open_User <", value, "open_User");
            return (Criteria) this;
        }

        public Criteria andOpen_UserLessThanOrEqualTo(String value) {
            addCriterion("Open_User <=", value, "open_User");
            return (Criteria) this;
        }

        public Criteria andOpen_UserLike(String value) {
            addCriterion("Open_User like", value, "open_User");
            return (Criteria) this;
        }

        public Criteria andOpen_UserNotLike(String value) {
            addCriterion("Open_User not like", value, "open_User");
            return (Criteria) this;
        }

        public Criteria andOpen_UserIn(List<String> values) {
            addCriterion("Open_User in", values, "open_User");
            return (Criteria) this;
        }

        public Criteria andOpen_UserNotIn(List<String> values) {
            addCriterion("Open_User not in", values, "open_User");
            return (Criteria) this;
        }

        public Criteria andOpen_UserBetween(String value1, String value2) {
            addCriterion("Open_User between", value1, value2, "open_User");
            return (Criteria) this;
        }

        public Criteria andOpen_UserNotBetween(String value1, String value2) {
            addCriterion("Open_User not between", value1, value2, "open_User");
            return (Criteria) this;
        }

        public Criteria andOpen_Status_CodeIsNull() {
            addCriterion("Open_Status_Code is null");
            return (Criteria) this;
        }

        public Criteria andOpen_Status_CodeIsNotNull() {
            addCriterion("Open_Status_Code is not null");
            return (Criteria) this;
        }

        public Criteria andOpen_Status_CodeEqualTo(String value) {
            addCriterion("Open_Status_Code =", value, "open_Status_Code");
            return (Criteria) this;
        }

        public Criteria andOpen_Status_CodeNotEqualTo(String value) {
            addCriterion("Open_Status_Code <>", value, "open_Status_Code");
            return (Criteria) this;
        }

        public Criteria andOpen_Status_CodeGreaterThan(String value) {
            addCriterion("Open_Status_Code >", value, "open_Status_Code");
            return (Criteria) this;
        }

        public Criteria andOpen_Status_CodeGreaterThanOrEqualTo(String value) {
            addCriterion("Open_Status_Code >=", value, "open_Status_Code");
            return (Criteria) this;
        }

        public Criteria andOpen_Status_CodeLessThan(String value) {
            addCriterion("Open_Status_Code <", value, "open_Status_Code");
            return (Criteria) this;
        }

        public Criteria andOpen_Status_CodeLessThanOrEqualTo(String value) {
            addCriterion("Open_Status_Code <=", value, "open_Status_Code");
            return (Criteria) this;
        }

        public Criteria andOpen_Status_CodeLike(String value) {
            addCriterion("Open_Status_Code like", value, "open_Status_Code");
            return (Criteria) this;
        }

        public Criteria andOpen_Status_CodeNotLike(String value) {
            addCriterion("Open_Status_Code not like", value, "open_Status_Code");
            return (Criteria) this;
        }

        public Criteria andOpen_Status_CodeIn(List<String> values) {
            addCriterion("Open_Status_Code in", values, "open_Status_Code");
            return (Criteria) this;
        }

        public Criteria andOpen_Status_CodeNotIn(List<String> values) {
            addCriterion("Open_Status_Code not in", values, "open_Status_Code");
            return (Criteria) this;
        }

        public Criteria andOpen_Status_CodeBetween(String value1, String value2) {
            addCriterion("Open_Status_Code between", value1, value2, "open_Status_Code");
            return (Criteria) this;
        }

        public Criteria andOpen_Status_CodeNotBetween(String value1, String value2) {
            addCriterion("Open_Status_Code not between", value1, value2, "open_Status_Code");
            return (Criteria) this;
        }

        public Criteria andOpen_RemarkIsNull() {
            addCriterion("Open_Remark is null");
            return (Criteria) this;
        }

        public Criteria andOpen_RemarkIsNotNull() {
            addCriterion("Open_Remark is not null");
            return (Criteria) this;
        }

        public Criteria andOpen_RemarkEqualTo(String value) {
            addCriterion("Open_Remark =", value, "open_Remark");
            return (Criteria) this;
        }

        public Criteria andOpen_RemarkNotEqualTo(String value) {
            addCriterion("Open_Remark <>", value, "open_Remark");
            return (Criteria) this;
        }

        public Criteria andOpen_RemarkGreaterThan(String value) {
            addCriterion("Open_Remark >", value, "open_Remark");
            return (Criteria) this;
        }

        public Criteria andOpen_RemarkGreaterThanOrEqualTo(String value) {
            addCriterion("Open_Remark >=", value, "open_Remark");
            return (Criteria) this;
        }

        public Criteria andOpen_RemarkLessThan(String value) {
            addCriterion("Open_Remark <", value, "open_Remark");
            return (Criteria) this;
        }

        public Criteria andOpen_RemarkLessThanOrEqualTo(String value) {
            addCriterion("Open_Remark <=", value, "open_Remark");
            return (Criteria) this;
        }

        public Criteria andOpen_RemarkLike(String value) {
            addCriterion("Open_Remark like", value, "open_Remark");
            return (Criteria) this;
        }

        public Criteria andOpen_RemarkNotLike(String value) {
            addCriterion("Open_Remark not like", value, "open_Remark");
            return (Criteria) this;
        }

        public Criteria andOpen_RemarkIn(List<String> values) {
            addCriterion("Open_Remark in", values, "open_Remark");
            return (Criteria) this;
        }

        public Criteria andOpen_RemarkNotIn(List<String> values) {
            addCriterion("Open_Remark not in", values, "open_Remark");
            return (Criteria) this;
        }

        public Criteria andOpen_RemarkBetween(String value1, String value2) {
            addCriterion("Open_Remark between", value1, value2, "open_Remark");
            return (Criteria) this;
        }

        public Criteria andOpen_RemarkNotBetween(String value1, String value2) {
            addCriterion("Open_Remark not between", value1, value2, "open_Remark");
            return (Criteria) this;
        }

        public Criteria andFinancial_ConfirmIsNull() {
            addCriterion("Financial_Confirm is null");
            return (Criteria) this;
        }

        public Criteria andFinancial_ConfirmIsNotNull() {
            addCriterion("Financial_Confirm is not null");
            return (Criteria) this;
        }

        public Criteria andFinancial_ConfirmEqualTo(Integer value) {
            addCriterion("Financial_Confirm =", value, "financial_Confirm");
            return (Criteria) this;
        }

        public Criteria andFinancial_ConfirmNotEqualTo(Integer value) {
            addCriterion("Financial_Confirm <>", value, "financial_Confirm");
            return (Criteria) this;
        }

        public Criteria andFinancial_ConfirmGreaterThan(Integer value) {
            addCriterion("Financial_Confirm >", value, "financial_Confirm");
            return (Criteria) this;
        }

        public Criteria andFinancial_ConfirmGreaterThanOrEqualTo(Integer value) {
            addCriterion("Financial_Confirm >=", value, "financial_Confirm");
            return (Criteria) this;
        }

        public Criteria andFinancial_ConfirmLessThan(Integer value) {
            addCriterion("Financial_Confirm <", value, "financial_Confirm");
            return (Criteria) this;
        }

        public Criteria andFinancial_ConfirmLessThanOrEqualTo(Integer value) {
            addCriterion("Financial_Confirm <=", value, "financial_Confirm");
            return (Criteria) this;
        }

        public Criteria andFinancial_ConfirmIn(List<Integer> values) {
            addCriterion("Financial_Confirm in", values, "financial_Confirm");
            return (Criteria) this;
        }

        public Criteria andFinancial_ConfirmNotIn(List<Integer> values) {
            addCriterion("Financial_Confirm not in", values, "financial_Confirm");
            return (Criteria) this;
        }

        public Criteria andFinancial_ConfirmBetween(Integer value1, Integer value2) {
            addCriterion("Financial_Confirm between", value1, value2, "financial_Confirm");
            return (Criteria) this;
        }

        public Criteria andFinancial_ConfirmNotBetween(Integer value1, Integer value2) {
            addCriterion("Financial_Confirm not between", value1, value2, "financial_Confirm");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("Description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("Description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("Description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("Description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("Description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("Description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("Description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("Description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("Description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("Description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("Description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("Description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("Description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("Description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("Remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("Remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("Remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("Remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("Remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("Remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("Remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("Remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("Remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("Remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("Remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("Remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("Remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("Remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreate_DateIsNull() {
            addCriterion("Create_Date is null");
            return (Criteria) this;
        }

        public Criteria andCreate_DateIsNotNull() {
            addCriterion("Create_Date is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_DateEqualTo(Date value) {
            addCriterion("Create_Date =", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateNotEqualTo(Date value) {
            addCriterion("Create_Date <>", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateGreaterThan(Date value) {
            addCriterion("Create_Date >", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateGreaterThanOrEqualTo(Date value) {
            addCriterion("Create_Date >=", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateLessThan(Date value) {
            addCriterion("Create_Date <", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateLessThanOrEqualTo(Date value) {
            addCriterion("Create_Date <=", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateIn(List<Date> values) {
            addCriterion("Create_Date in", values, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateNotIn(List<Date> values) {
            addCriterion("Create_Date not in", values, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateBetween(Date value1, Date value2) {
            addCriterion("Create_Date between", value1, value2, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateNotBetween(Date value1, Date value2) {
            addCriterion("Create_Date not between", value1, value2, "create_Date");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table charge_order
     *
     * @mbg.generated do_not_delete_during_merge Thu May 14 16:45:43 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table charge_order
     *
     * @mbg.generated Thu May 14 16:45:43 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}