package com.hero.wireless.web.entity.business;

import com.hero.wireless.web.entity.base.BaseExample;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class EnterpriseLimitExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise_limit
     *
     * @mbg.generated Tue Sep 01 09:50:56 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise_limit
     *
     * @mbg.generated Tue Sep 01 09:50:56 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise_limit
     *
     * @mbg.generated Tue Sep 01 09:50:56 CST 2020
     */
    protected String dataLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table enterprise_limit
     *
     * @mbg.generated Tue Sep 01 09:50:56 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Tue Sep 01 09:50:56 CST 2020
     */
    public EnterpriseLimitExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Tue Sep 01 09:50:56 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Tue Sep 01 09:50:56 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Tue Sep 01 09:50:56 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Tue Sep 01 09:50:56 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Tue Sep 01 09:50:56 CST 2020
     */
    public void setDataLock(String dataLock) {
        this.dataLock = dataLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Tue Sep 01 09:50:56 CST 2020
     */
    public String getDataLock() {
        return dataLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Tue Sep 01 09:50:56 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Tue Sep 01 09:50:56 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Tue Sep 01 09:50:56 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Tue Sep 01 09:50:56 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Tue Sep 01 09:50:56 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Tue Sep 01 09:50:56 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enterprise_limit
     *
     * @mbg.generated Tue Sep 01 09:50:56 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("Name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("Name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("Name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("Name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("Name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("Name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("Name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("Name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("Name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("Name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("Name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("Name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("Name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("Name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andCodeIsNull() {
            addCriterion("Code is null");
            return (Criteria) this;
        }

        public Criteria andCodeIsNotNull() {
            addCriterion("Code is not null");
            return (Criteria) this;
        }

        public Criteria andCodeEqualTo(String value) {
            addCriterion("Code =", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotEqualTo(String value) {
            addCriterion("Code <>", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThan(String value) {
            addCriterion("Code >", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeGreaterThanOrEqualTo(String value) {
            addCriterion("Code >=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThan(String value) {
            addCriterion("Code <", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLessThanOrEqualTo(String value) {
            addCriterion("Code <=", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeLike(String value) {
            addCriterion("Code like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotLike(String value) {
            addCriterion("Code not like", value, "code");
            return (Criteria) this;
        }

        public Criteria andCodeIn(List<String> values) {
            addCriterion("Code in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotIn(List<String> values) {
            addCriterion("Code not in", values, "code");
            return (Criteria) this;
        }

        public Criteria andCodeBetween(String value1, String value2) {
            addCriterion("Code between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andCodeNotBetween(String value1, String value2) {
            addCriterion("Code not between", value1, value2, "code");
            return (Criteria) this;
        }

        public Criteria andUp_CodeIsNull() {
            addCriterion("Up_Code is null");
            return (Criteria) this;
        }

        public Criteria andUp_CodeIsNotNull() {
            addCriterion("Up_Code is not null");
            return (Criteria) this;
        }

        public Criteria andUp_CodeEqualTo(String value) {
            addCriterion("Up_Code =", value, "up_Code");
            return (Criteria) this;
        }

        public Criteria andUp_CodeNotEqualTo(String value) {
            addCriterion("Up_Code <>", value, "up_Code");
            return (Criteria) this;
        }

        public Criteria andUp_CodeGreaterThan(String value) {
            addCriterion("Up_Code >", value, "up_Code");
            return (Criteria) this;
        }

        public Criteria andUp_CodeGreaterThanOrEqualTo(String value) {
            addCriterion("Up_Code >=", value, "up_Code");
            return (Criteria) this;
        }

        public Criteria andUp_CodeLessThan(String value) {
            addCriterion("Up_Code <", value, "up_Code");
            return (Criteria) this;
        }

        public Criteria andUp_CodeLessThanOrEqualTo(String value) {
            addCriterion("Up_Code <=", value, "up_Code");
            return (Criteria) this;
        }

        public Criteria andUp_CodeLike(String value) {
            addCriterion("Up_Code like", value, "up_Code");
            return (Criteria) this;
        }

        public Criteria andUp_CodeNotLike(String value) {
            addCriterion("Up_Code not like", value, "up_Code");
            return (Criteria) this;
        }

        public Criteria andUp_CodeIn(List<String> values) {
            addCriterion("Up_Code in", values, "up_Code");
            return (Criteria) this;
        }

        public Criteria andUp_CodeNotIn(List<String> values) {
            addCriterion("Up_Code not in", values, "up_Code");
            return (Criteria) this;
        }

        public Criteria andUp_CodeBetween(String value1, String value2) {
            addCriterion("Up_Code between", value1, value2, "up_Code");
            return (Criteria) this;
        }

        public Criteria andUp_CodeNotBetween(String value1, String value2) {
            addCriterion("Up_Code not between", value1, value2, "up_Code");
            return (Criteria) this;
        }

        public Criteria andUrlIsNull() {
            addCriterion("Url is null");
            return (Criteria) this;
        }

        public Criteria andUrlIsNotNull() {
            addCriterion("Url is not null");
            return (Criteria) this;
        }

        public Criteria andUrlEqualTo(String value) {
            addCriterion("Url =", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotEqualTo(String value) {
            addCriterion("Url <>", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThan(String value) {
            addCriterion("Url >", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlGreaterThanOrEqualTo(String value) {
            addCriterion("Url >=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThan(String value) {
            addCriterion("Url <", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLessThanOrEqualTo(String value) {
            addCriterion("Url <=", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlLike(String value) {
            addCriterion("Url like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotLike(String value) {
            addCriterion("Url not like", value, "url");
            return (Criteria) this;
        }

        public Criteria andUrlIn(List<String> values) {
            addCriterion("Url in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotIn(List<String> values) {
            addCriterion("Url not in", values, "url");
            return (Criteria) this;
        }

        public Criteria andUrlBetween(String value1, String value2) {
            addCriterion("Url between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrlNotBetween(String value1, String value2) {
            addCriterion("Url not between", value1, value2, "url");
            return (Criteria) this;
        }

        public Criteria andUrl_ParamIsNull() {
            addCriterion("Url_Param is null");
            return (Criteria) this;
        }

        public Criteria andUrl_ParamIsNotNull() {
            addCriterion("Url_Param is not null");
            return (Criteria) this;
        }

        public Criteria andUrl_ParamEqualTo(String value) {
            addCriterion("Url_Param =", value, "url_Param");
            return (Criteria) this;
        }

        public Criteria andUrl_ParamNotEqualTo(String value) {
            addCriterion("Url_Param <>", value, "url_Param");
            return (Criteria) this;
        }

        public Criteria andUrl_ParamGreaterThan(String value) {
            addCriterion("Url_Param >", value, "url_Param");
            return (Criteria) this;
        }

        public Criteria andUrl_ParamGreaterThanOrEqualTo(String value) {
            addCriterion("Url_Param >=", value, "url_Param");
            return (Criteria) this;
        }

        public Criteria andUrl_ParamLessThan(String value) {
            addCriterion("Url_Param <", value, "url_Param");
            return (Criteria) this;
        }

        public Criteria andUrl_ParamLessThanOrEqualTo(String value) {
            addCriterion("Url_Param <=", value, "url_Param");
            return (Criteria) this;
        }

        public Criteria andUrl_ParamLike(String value) {
            addCriterion("Url_Param like", value, "url_Param");
            return (Criteria) this;
        }

        public Criteria andUrl_ParamNotLike(String value) {
            addCriterion("Url_Param not like", value, "url_Param");
            return (Criteria) this;
        }

        public Criteria andUrl_ParamIn(List<String> values) {
            addCriterion("Url_Param in", values, "url_Param");
            return (Criteria) this;
        }

        public Criteria andUrl_ParamNotIn(List<String> values) {
            addCriterion("Url_Param not in", values, "url_Param");
            return (Criteria) this;
        }

        public Criteria andUrl_ParamBetween(String value1, String value2) {
            addCriterion("Url_Param between", value1, value2, "url_Param");
            return (Criteria) this;
        }

        public Criteria andUrl_ParamNotBetween(String value1, String value2) {
            addCriterion("Url_Param not between", value1, value2, "url_Param");
            return (Criteria) this;
        }

        public Criteria andButton_ActionIsNull() {
            addCriterion("Button_Action is null");
            return (Criteria) this;
        }

        public Criteria andButton_ActionIsNotNull() {
            addCriterion("Button_Action is not null");
            return (Criteria) this;
        }

        public Criteria andButton_ActionEqualTo(String value) {
            addCriterion("Button_Action =", value, "button_Action");
            return (Criteria) this;
        }

        public Criteria andButton_ActionNotEqualTo(String value) {
            addCriterion("Button_Action <>", value, "button_Action");
            return (Criteria) this;
        }

        public Criteria andButton_ActionGreaterThan(String value) {
            addCriterion("Button_Action >", value, "button_Action");
            return (Criteria) this;
        }

        public Criteria andButton_ActionGreaterThanOrEqualTo(String value) {
            addCriterion("Button_Action >=", value, "button_Action");
            return (Criteria) this;
        }

        public Criteria andButton_ActionLessThan(String value) {
            addCriterion("Button_Action <", value, "button_Action");
            return (Criteria) this;
        }

        public Criteria andButton_ActionLessThanOrEqualTo(String value) {
            addCriterion("Button_Action <=", value, "button_Action");
            return (Criteria) this;
        }

        public Criteria andButton_ActionLike(String value) {
            addCriterion("Button_Action like", value, "button_Action");
            return (Criteria) this;
        }

        public Criteria andButton_ActionNotLike(String value) {
            addCriterion("Button_Action not like", value, "button_Action");
            return (Criteria) this;
        }

        public Criteria andButton_ActionIn(List<String> values) {
            addCriterion("Button_Action in", values, "button_Action");
            return (Criteria) this;
        }

        public Criteria andButton_ActionNotIn(List<String> values) {
            addCriterion("Button_Action not in", values, "button_Action");
            return (Criteria) this;
        }

        public Criteria andButton_ActionBetween(String value1, String value2) {
            addCriterion("Button_Action between", value1, value2, "button_Action");
            return (Criteria) this;
        }

        public Criteria andButton_ActionNotBetween(String value1, String value2) {
            addCriterion("Button_Action not between", value1, value2, "button_Action");
            return (Criteria) this;
        }

        public Criteria andIconIsNull() {
            addCriterion("Icon is null");
            return (Criteria) this;
        }

        public Criteria andIconIsNotNull() {
            addCriterion("Icon is not null");
            return (Criteria) this;
        }

        public Criteria andIconEqualTo(String value) {
            addCriterion("Icon =", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotEqualTo(String value) {
            addCriterion("Icon <>", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconGreaterThan(String value) {
            addCriterion("Icon >", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconGreaterThanOrEqualTo(String value) {
            addCriterion("Icon >=", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLessThan(String value) {
            addCriterion("Icon <", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLessThanOrEqualTo(String value) {
            addCriterion("Icon <=", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconLike(String value) {
            addCriterion("Icon like", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotLike(String value) {
            addCriterion("Icon not like", value, "icon");
            return (Criteria) this;
        }

        public Criteria andIconIn(List<String> values) {
            addCriterion("Icon in", values, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotIn(List<String> values) {
            addCriterion("Icon not in", values, "icon");
            return (Criteria) this;
        }

        public Criteria andIconBetween(String value1, String value2) {
            addCriterion("Icon between", value1, value2, "icon");
            return (Criteria) this;
        }

        public Criteria andIconNotBetween(String value1, String value2) {
            addCriterion("Icon not between", value1, value2, "icon");
            return (Criteria) this;
        }

        public Criteria andCreate_UserIsNull() {
            addCriterion("Create_User is null");
            return (Criteria) this;
        }

        public Criteria andCreate_UserIsNotNull() {
            addCriterion("Create_User is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_UserEqualTo(String value) {
            addCriterion("Create_User =", value, "create_User");
            return (Criteria) this;
        }

        public Criteria andCreate_UserNotEqualTo(String value) {
            addCriterion("Create_User <>", value, "create_User");
            return (Criteria) this;
        }

        public Criteria andCreate_UserGreaterThan(String value) {
            addCriterion("Create_User >", value, "create_User");
            return (Criteria) this;
        }

        public Criteria andCreate_UserGreaterThanOrEqualTo(String value) {
            addCriterion("Create_User >=", value, "create_User");
            return (Criteria) this;
        }

        public Criteria andCreate_UserLessThan(String value) {
            addCriterion("Create_User <", value, "create_User");
            return (Criteria) this;
        }

        public Criteria andCreate_UserLessThanOrEqualTo(String value) {
            addCriterion("Create_User <=", value, "create_User");
            return (Criteria) this;
        }

        public Criteria andCreate_UserLike(String value) {
            addCriterion("Create_User like", value, "create_User");
            return (Criteria) this;
        }

        public Criteria andCreate_UserNotLike(String value) {
            addCriterion("Create_User not like", value, "create_User");
            return (Criteria) this;
        }

        public Criteria andCreate_UserIn(List<String> values) {
            addCriterion("Create_User in", values, "create_User");
            return (Criteria) this;
        }

        public Criteria andCreate_UserNotIn(List<String> values) {
            addCriterion("Create_User not in", values, "create_User");
            return (Criteria) this;
        }

        public Criteria andCreate_UserBetween(String value1, String value2) {
            addCriterion("Create_User between", value1, value2, "create_User");
            return (Criteria) this;
        }

        public Criteria andCreate_UserNotBetween(String value1, String value2) {
            addCriterion("Create_User not between", value1, value2, "create_User");
            return (Criteria) this;
        }

        public Criteria andOrder_IdIsNull() {
            addCriterion("Order_Id is null");
            return (Criteria) this;
        }

        public Criteria andOrder_IdIsNotNull() {
            addCriterion("Order_Id is not null");
            return (Criteria) this;
        }

        public Criteria andOrder_IdEqualTo(Integer value) {
            addCriterion("Order_Id =", value, "order_Id");
            return (Criteria) this;
        }

        public Criteria andOrder_IdNotEqualTo(Integer value) {
            addCriterion("Order_Id <>", value, "order_Id");
            return (Criteria) this;
        }

        public Criteria andOrder_IdGreaterThan(Integer value) {
            addCriterion("Order_Id >", value, "order_Id");
            return (Criteria) this;
        }

        public Criteria andOrder_IdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Order_Id >=", value, "order_Id");
            return (Criteria) this;
        }

        public Criteria andOrder_IdLessThan(Integer value) {
            addCriterion("Order_Id <", value, "order_Id");
            return (Criteria) this;
        }

        public Criteria andOrder_IdLessThanOrEqualTo(Integer value) {
            addCriterion("Order_Id <=", value, "order_Id");
            return (Criteria) this;
        }

        public Criteria andOrder_IdIn(List<Integer> values) {
            addCriterion("Order_Id in", values, "order_Id");
            return (Criteria) this;
        }

        public Criteria andOrder_IdNotIn(List<Integer> values) {
            addCriterion("Order_Id not in", values, "order_Id");
            return (Criteria) this;
        }

        public Criteria andOrder_IdBetween(Integer value1, Integer value2) {
            addCriterion("Order_Id between", value1, value2, "order_Id");
            return (Criteria) this;
        }

        public Criteria andOrder_IdNotBetween(Integer value1, Integer value2) {
            addCriterion("Order_Id not between", value1, value2, "order_Id");
            return (Criteria) this;
        }

        public Criteria andType_CodeIsNull() {
            addCriterion("Type_Code is null");
            return (Criteria) this;
        }

        public Criteria andType_CodeIsNotNull() {
            addCriterion("Type_Code is not null");
            return (Criteria) this;
        }

        public Criteria andType_CodeEqualTo(String value) {
            addCriterion("Type_Code =", value, "type_Code");
            return (Criteria) this;
        }

        public Criteria andType_CodeNotEqualTo(String value) {
            addCriterion("Type_Code <>", value, "type_Code");
            return (Criteria) this;
        }

        public Criteria andType_CodeGreaterThan(String value) {
            addCriterion("Type_Code >", value, "type_Code");
            return (Criteria) this;
        }

        public Criteria andType_CodeGreaterThanOrEqualTo(String value) {
            addCriterion("Type_Code >=", value, "type_Code");
            return (Criteria) this;
        }

        public Criteria andType_CodeLessThan(String value) {
            addCriterion("Type_Code <", value, "type_Code");
            return (Criteria) this;
        }

        public Criteria andType_CodeLessThanOrEqualTo(String value) {
            addCriterion("Type_Code <=", value, "type_Code");
            return (Criteria) this;
        }

        public Criteria andType_CodeLike(String value) {
            addCriterion("Type_Code like", value, "type_Code");
            return (Criteria) this;
        }

        public Criteria andType_CodeNotLike(String value) {
            addCriterion("Type_Code not like", value, "type_Code");
            return (Criteria) this;
        }

        public Criteria andType_CodeIn(List<String> values) {
            addCriterion("Type_Code in", values, "type_Code");
            return (Criteria) this;
        }

        public Criteria andType_CodeNotIn(List<String> values) {
            addCriterion("Type_Code not in", values, "type_Code");
            return (Criteria) this;
        }

        public Criteria andType_CodeBetween(String value1, String value2) {
            addCriterion("Type_Code between", value1, value2, "type_Code");
            return (Criteria) this;
        }

        public Criteria andType_CodeNotBetween(String value1, String value2) {
            addCriterion("Type_Code not between", value1, value2, "type_Code");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("Description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("Description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("Description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("Description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("Description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("Description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("Description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("Description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("Description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("Description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("Description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("Description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("Description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("Description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("Remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("Remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("Remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("Remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("Remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("Remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("Remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("Remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("Remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("Remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("Remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("Remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("Remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("Remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreate_DateIsNull() {
            addCriterion("Create_Date is null");
            return (Criteria) this;
        }

        public Criteria andCreate_DateIsNotNull() {
            addCriterion("Create_Date is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_DateEqualTo(Date value) {
            addCriterion("Create_Date =", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateNotEqualTo(Date value) {
            addCriterion("Create_Date <>", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateGreaterThan(Date value) {
            addCriterion("Create_Date >", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateGreaterThanOrEqualTo(Date value) {
            addCriterion("Create_Date >=", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateLessThan(Date value) {
            addCriterion("Create_Date <", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateLessThanOrEqualTo(Date value) {
            addCriterion("Create_Date <=", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateIn(List<Date> values) {
            addCriterion("Create_Date in", values, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateNotIn(List<Date> values) {
            addCriterion("Create_Date not in", values, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateBetween(Date value1, Date value2) {
            addCriterion("Create_Date between", value1, value2, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateNotBetween(Date value1, Date value2) {
            addCriterion("Create_Date not between", value1, value2, "create_Date");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enterprise_limit
     *
     * @mbg.generated do_not_delete_during_merge Tue Sep 01 09:50:56 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table enterprise_limit
     *
     * @mbg.generated Tue Sep 01 09:50:56 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}