package com.hero.wireless.web.entity.business;

import com.hero.wireless.web.entity.base.BaseEntity;

import java.math.BigDecimal;
import java.util.Date;

public class Enterprise extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String no;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Agent_No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String agent_No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Business_User_Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private Integer business_User_Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Name
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Status
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Data_Source
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String data_Source;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Authentication_State_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String authentication_State_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Contract
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String contract;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Phone_No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String phone_No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Address
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Email
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Business_License_Picture_Url
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String business_License_Picture_Url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Id_Card_Back_Picture_Url
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String id_Card_Back_Picture_Url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Id_Card_Before_Picture_Url
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String id_Card_Before_Picture_Url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Sent_Count
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private Integer sent_Count;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Used_Amount
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private BigDecimal used_Amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Available_Amount
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private BigDecimal available_Amount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Domain
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String domain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Login_Url
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String login_Url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Description
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Remark
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise.Create_Date
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private Date create_Date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Id
     *
     * @return the value of enterprise.Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Id
     *
     * @param id the value for enterprise.Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.No
     *
     * @return the value of enterprise.No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.No
     *
     * @param no the value for enterprise.No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setNo(String no) {
        this.no = no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Agent_No
     *
     * @return the value of enterprise.Agent_No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getAgent_No() {
        return agent_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Agent_No
     *
     * @param agent_No the value for enterprise.Agent_No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setAgent_No(String agent_No) {
        this.agent_No = agent_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Business_User_Id
     *
     * @return the value of enterprise.Business_User_Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public Integer getBusiness_User_Id() {
        return business_User_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Business_User_Id
     *
     * @param business_User_Id the value for enterprise.Business_User_Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setBusiness_User_Id(Integer business_User_Id) {
        this.business_User_Id = business_User_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Name
     *
     * @return the value of enterprise.Name
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Name
     *
     * @param name the value for enterprise.Name
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Status
     *
     * @return the value of enterprise.Status
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Status
     *
     * @param status the value for enterprise.Status
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Data_Source
     *
     * @return the value of enterprise.Data_Source
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getData_Source() {
        return data_Source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Data_Source
     *
     * @param data_Source the value for enterprise.Data_Source
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setData_Source(String data_Source) {
        this.data_Source = data_Source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Authentication_State_Code
     *
     * @return the value of enterprise.Authentication_State_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getAuthentication_State_Code() {
        return authentication_State_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Authentication_State_Code
     *
     * @param authentication_State_Code the value for enterprise.Authentication_State_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setAuthentication_State_Code(String authentication_State_Code) {
        this.authentication_State_Code = authentication_State_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Contract
     *
     * @return the value of enterprise.Contract
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getContract() {
        return contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Contract
     *
     * @param contract the value for enterprise.Contract
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setContract(String contract) {
        this.contract = contract;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Phone_No
     *
     * @return the value of enterprise.Phone_No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getPhone_No() {
        return phone_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Phone_No
     *
     * @param phone_No the value for enterprise.Phone_No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setPhone_No(String phone_No) {
        this.phone_No = phone_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Address
     *
     * @return the value of enterprise.Address
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Address
     *
     * @param address the value for enterprise.Address
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Email
     *
     * @return the value of enterprise.Email
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Email
     *
     * @param email the value for enterprise.Email
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Business_License_Picture_Url
     *
     * @return the value of enterprise.Business_License_Picture_Url
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getBusiness_License_Picture_Url() {
        return business_License_Picture_Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Business_License_Picture_Url
     *
     * @param business_License_Picture_Url the value for enterprise.Business_License_Picture_Url
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setBusiness_License_Picture_Url(String business_License_Picture_Url) {
        this.business_License_Picture_Url = business_License_Picture_Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Id_Card_Back_Picture_Url
     *
     * @return the value of enterprise.Id_Card_Back_Picture_Url
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getId_Card_Back_Picture_Url() {
        return id_Card_Back_Picture_Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Id_Card_Back_Picture_Url
     *
     * @param id_Card_Back_Picture_Url the value for enterprise.Id_Card_Back_Picture_Url
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setId_Card_Back_Picture_Url(String id_Card_Back_Picture_Url) {
        this.id_Card_Back_Picture_Url = id_Card_Back_Picture_Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Id_Card_Before_Picture_Url
     *
     * @return the value of enterprise.Id_Card_Before_Picture_Url
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getId_Card_Before_Picture_Url() {
        return id_Card_Before_Picture_Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Id_Card_Before_Picture_Url
     *
     * @param id_Card_Before_Picture_Url the value for enterprise.Id_Card_Before_Picture_Url
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setId_Card_Before_Picture_Url(String id_Card_Before_Picture_Url) {
        this.id_Card_Before_Picture_Url = id_Card_Before_Picture_Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Sent_Count
     *
     * @return the value of enterprise.Sent_Count
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public Integer getSent_Count() {
        return sent_Count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Sent_Count
     *
     * @param sent_Count the value for enterprise.Sent_Count
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setSent_Count(Integer sent_Count) {
        this.sent_Count = sent_Count;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Used_Amount
     *
     * @return the value of enterprise.Used_Amount
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public BigDecimal getUsed_Amount() {
        return used_Amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Used_Amount
     *
     * @param used_Amount the value for enterprise.Used_Amount
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setUsed_Amount(BigDecimal used_Amount) {
        this.used_Amount = used_Amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Available_Amount
     *
     * @return the value of enterprise.Available_Amount
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public BigDecimal getAvailable_Amount() {
        return available_Amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Available_Amount
     *
     * @param available_Amount the value for enterprise.Available_Amount
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setAvailable_Amount(BigDecimal available_Amount) {
        this.available_Amount = available_Amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Domain
     *
     * @return the value of enterprise.Domain
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getDomain() {
        return domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Domain
     *
     * @param domain the value for enterprise.Domain
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setDomain(String domain) {
        this.domain = domain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Login_Url
     *
     * @return the value of enterprise.Login_Url
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getLogin_Url() {
        return login_Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Login_Url
     *
     * @param login_Url the value for enterprise.Login_Url
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setLogin_Url(String login_Url) {
        this.login_Url = login_Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Description
     *
     * @return the value of enterprise.Description
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Description
     *
     * @param description the value for enterprise.Description
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Remark
     *
     * @return the value of enterprise.Remark
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Remark
     *
     * @param remark the value for enterprise.Remark
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise.Create_Date
     *
     * @return the value of enterprise.Create_Date
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public Date getCreate_Date() {
        return create_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise.Create_Date
     *
     * @param create_Date the value for enterprise.Create_Date
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setCreate_Date(Date create_Date) {
        this.create_Date = create_Date;
    }
}