package com.hero.wireless.web.entity.business;

import com.hero.wireless.web.entity.base.BaseEntity;

import java.util.Date;

public class ExportFile extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_file.Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_file.File_Url
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String file_Url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_file.FIle_Name
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String FIle_Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_file.Batch_Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String batch_Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_file.Enterprise_No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String enterprise_No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_file.Agent_No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String agent_No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_file.User_Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private Integer user_Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column export_file.Create_Date
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private Date create_Date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_file.Id
     *
     * @return the value of export_file.Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_file.Id
     *
     * @param id the value for export_file.Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_file.File_Url
     *
     * @return the value of export_file.File_Url
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getFile_Url() {
        return file_Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_file.File_Url
     *
     * @param file_Url the value for export_file.File_Url
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setFile_Url(String file_Url) {
        this.file_Url = file_Url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_file.FIle_Name
     *
     * @return the value of export_file.FIle_Name
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getFIle_Name() {
        return FIle_Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_file.FIle_Name
     *
     * @param FIle_Name the value for export_file.FIle_Name
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setFIle_Name(String FIle_Name) {
        this.FIle_Name = FIle_Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_file.Batch_Id
     *
     * @return the value of export_file.Batch_Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getBatch_Id() {
        return batch_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_file.Batch_Id
     *
     * @param batch_Id the value for export_file.Batch_Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setBatch_Id(String batch_Id) {
        this.batch_Id = batch_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_file.Enterprise_No
     *
     * @return the value of export_file.Enterprise_No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getEnterprise_No() {
        return enterprise_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_file.Enterprise_No
     *
     * @param enterprise_No the value for export_file.Enterprise_No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setEnterprise_No(String enterprise_No) {
        this.enterprise_No = enterprise_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_file.Agent_No
     *
     * @return the value of export_file.Agent_No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getAgent_No() {
        return agent_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_file.Agent_No
     *
     * @param agent_No the value for export_file.Agent_No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setAgent_No(String agent_No) {
        this.agent_No = agent_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_file.User_Id
     *
     * @return the value of export_file.User_Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public Integer getUser_Id() {
        return user_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_file.User_Id
     *
     * @param user_Id the value for export_file.User_Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setUser_Id(Integer user_Id) {
        this.user_Id = user_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column export_file.Create_Date
     *
     * @return the value of export_file.Create_Date
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public Date getCreate_Date() {
        return create_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column export_file.Create_Date
     *
     * @param create_Date the value for export_file.Create_Date
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setCreate_Date(Date create_Date) {
        this.create_Date = create_Date;
    }
}