package com.hero.wireless.web.entity.business;

import com.hero.wireless.web.entity.base.BaseEntity;

import java.util.Date;

public class MmsMaterial extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_material.Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_material.Enterprise_No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String enterprise_No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_material.Enterprise_User_Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private Integer enterprise_User_Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_material.Material_Name
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String material_Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_material.Material_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String material_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_material.Material_Type_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String material_Type_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_material.Format
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String format;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_material.Size
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String size;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_material.Url
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String url;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_material.Approve_Status
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String approve_Status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_material.Description
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_material.Remark
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mms_material.Create_Date
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private Date create_Date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_material.Id
     *
     * @return the value of mms_material.Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_material.Id
     *
     * @param id the value for mms_material.Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_material.Enterprise_No
     *
     * @return the value of mms_material.Enterprise_No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getEnterprise_No() {
        return enterprise_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_material.Enterprise_No
     *
     * @param enterprise_No the value for mms_material.Enterprise_No
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setEnterprise_No(String enterprise_No) {
        this.enterprise_No = enterprise_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_material.Enterprise_User_Id
     *
     * @return the value of mms_material.Enterprise_User_Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public Integer getEnterprise_User_Id() {
        return enterprise_User_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_material.Enterprise_User_Id
     *
     * @param enterprise_User_Id the value for mms_material.Enterprise_User_Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setEnterprise_User_Id(Integer enterprise_User_Id) {
        this.enterprise_User_Id = enterprise_User_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_material.Material_Name
     *
     * @return the value of mms_material.Material_Name
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getMaterial_Name() {
        return material_Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_material.Material_Name
     *
     * @param material_Name the value for mms_material.Material_Name
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setMaterial_Name(String material_Name) {
        this.material_Name = material_Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_material.Material_Code
     *
     * @return the value of mms_material.Material_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getMaterial_Code() {
        return material_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_material.Material_Code
     *
     * @param material_Code the value for mms_material.Material_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setMaterial_Code(String material_Code) {
        this.material_Code = material_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_material.Material_Type_Code
     *
     * @return the value of mms_material.Material_Type_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getMaterial_Type_Code() {
        return material_Type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_material.Material_Type_Code
     *
     * @param material_Type_Code the value for mms_material.Material_Type_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setMaterial_Type_Code(String material_Type_Code) {
        this.material_Type_Code = material_Type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_material.Format
     *
     * @return the value of mms_material.Format
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getFormat() {
        return format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_material.Format
     *
     * @param format the value for mms_material.Format
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setFormat(String format) {
        this.format = format;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_material.Size
     *
     * @return the value of mms_material.Size
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getSize() {
        return size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_material.Size
     *
     * @param size the value for mms_material.Size
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setSize(String size) {
        this.size = size;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_material.Url
     *
     * @return the value of mms_material.Url
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_material.Url
     *
     * @param url the value for mms_material.Url
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setUrl(String url) {
        this.url = url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_material.Approve_Status
     *
     * @return the value of mms_material.Approve_Status
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getApprove_Status() {
        return approve_Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_material.Approve_Status
     *
     * @param approve_Status the value for mms_material.Approve_Status
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setApprove_Status(String approve_Status) {
        this.approve_Status = approve_Status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_material.Description
     *
     * @return the value of mms_material.Description
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_material.Description
     *
     * @param description the value for mms_material.Description
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_material.Remark
     *
     * @return the value of mms_material.Remark
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_material.Remark
     *
     * @param remark the value for mms_material.Remark
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mms_material.Create_Date
     *
     * @return the value of mms_material.Create_Date
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public Date getCreate_Date() {
        return create_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mms_material.Create_Date
     *
     * @param create_Date the value for mms_material.Create_Date
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setCreate_Date(Date create_Date) {
        this.create_Date = create_Date;
    }
}