package com.hero.wireless.web.entity.business;

import com.hero.wireless.web.entity.base.BaseExample;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PlatformSmsStatisticsExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    protected String dataLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    public PlatformSmsStatisticsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    public void setDataLock(String dataLock) {
        this.dataLock = dataLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    public String getDataLock() {
        return dataLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPlatform_NoIsNull() {
            addCriterion("Platform_No is null");
            return (Criteria) this;
        }

        public Criteria andPlatform_NoIsNotNull() {
            addCriterion("Platform_No is not null");
            return (Criteria) this;
        }

        public Criteria andPlatform_NoEqualTo(String value) {
            addCriterion("Platform_No =", value, "platform_No");
            return (Criteria) this;
        }

        public Criteria andPlatform_NoNotEqualTo(String value) {
            addCriterion("Platform_No <>", value, "platform_No");
            return (Criteria) this;
        }

        public Criteria andPlatform_NoGreaterThan(String value) {
            addCriterion("Platform_No >", value, "platform_No");
            return (Criteria) this;
        }

        public Criteria andPlatform_NoGreaterThanOrEqualTo(String value) {
            addCriterion("Platform_No >=", value, "platform_No");
            return (Criteria) this;
        }

        public Criteria andPlatform_NoLessThan(String value) {
            addCriterion("Platform_No <", value, "platform_No");
            return (Criteria) this;
        }

        public Criteria andPlatform_NoLessThanOrEqualTo(String value) {
            addCriterion("Platform_No <=", value, "platform_No");
            return (Criteria) this;
        }

        public Criteria andPlatform_NoLike(String value) {
            addCriterion("Platform_No like", value, "platform_No");
            return (Criteria) this;
        }

        public Criteria andPlatform_NoNotLike(String value) {
            addCriterion("Platform_No not like", value, "platform_No");
            return (Criteria) this;
        }

        public Criteria andPlatform_NoIn(List<String> values) {
            addCriterion("Platform_No in", values, "platform_No");
            return (Criteria) this;
        }

        public Criteria andPlatform_NoNotIn(List<String> values) {
            addCriterion("Platform_No not in", values, "platform_No");
            return (Criteria) this;
        }

        public Criteria andPlatform_NoBetween(String value1, String value2) {
            addCriterion("Platform_No between", value1, value2, "platform_No");
            return (Criteria) this;
        }

        public Criteria andPlatform_NoNotBetween(String value1, String value2) {
            addCriterion("Platform_No not between", value1, value2, "platform_No");
            return (Criteria) this;
        }

        public Criteria andPlatform_NameIsNull() {
            addCriterion("Platform_Name is null");
            return (Criteria) this;
        }

        public Criteria andPlatform_NameIsNotNull() {
            addCriterion("Platform_Name is not null");
            return (Criteria) this;
        }

        public Criteria andPlatform_NameEqualTo(String value) {
            addCriterion("Platform_Name =", value, "platform_Name");
            return (Criteria) this;
        }

        public Criteria andPlatform_NameNotEqualTo(String value) {
            addCriterion("Platform_Name <>", value, "platform_Name");
            return (Criteria) this;
        }

        public Criteria andPlatform_NameGreaterThan(String value) {
            addCriterion("Platform_Name >", value, "platform_Name");
            return (Criteria) this;
        }

        public Criteria andPlatform_NameGreaterThanOrEqualTo(String value) {
            addCriterion("Platform_Name >=", value, "platform_Name");
            return (Criteria) this;
        }

        public Criteria andPlatform_NameLessThan(String value) {
            addCriterion("Platform_Name <", value, "platform_Name");
            return (Criteria) this;
        }

        public Criteria andPlatform_NameLessThanOrEqualTo(String value) {
            addCriterion("Platform_Name <=", value, "platform_Name");
            return (Criteria) this;
        }

        public Criteria andPlatform_NameLike(String value) {
            addCriterion("Platform_Name like", value, "platform_Name");
            return (Criteria) this;
        }

        public Criteria andPlatform_NameNotLike(String value) {
            addCriterion("Platform_Name not like", value, "platform_Name");
            return (Criteria) this;
        }

        public Criteria andPlatform_NameIn(List<String> values) {
            addCriterion("Platform_Name in", values, "platform_Name");
            return (Criteria) this;
        }

        public Criteria andPlatform_NameNotIn(List<String> values) {
            addCriterion("Platform_Name not in", values, "platform_Name");
            return (Criteria) this;
        }

        public Criteria andPlatform_NameBetween(String value1, String value2) {
            addCriterion("Platform_Name between", value1, value2, "platform_Name");
            return (Criteria) this;
        }

        public Criteria andPlatform_NameNotBetween(String value1, String value2) {
            addCriterion("Platform_Name not between", value1, value2, "platform_Name");
            return (Criteria) this;
        }

        public Criteria andStatistics_Type_CodeIsNull() {
            addCriterion("Statistics_Type_Code is null");
            return (Criteria) this;
        }

        public Criteria andStatistics_Type_CodeIsNotNull() {
            addCriterion("Statistics_Type_Code is not null");
            return (Criteria) this;
        }

        public Criteria andStatistics_Type_CodeEqualTo(String value) {
            addCriterion("Statistics_Type_Code =", value, "statistics_Type_Code");
            return (Criteria) this;
        }

        public Criteria andStatistics_Type_CodeNotEqualTo(String value) {
            addCriterion("Statistics_Type_Code <>", value, "statistics_Type_Code");
            return (Criteria) this;
        }

        public Criteria andStatistics_Type_CodeGreaterThan(String value) {
            addCriterion("Statistics_Type_Code >", value, "statistics_Type_Code");
            return (Criteria) this;
        }

        public Criteria andStatistics_Type_CodeGreaterThanOrEqualTo(String value) {
            addCriterion("Statistics_Type_Code >=", value, "statistics_Type_Code");
            return (Criteria) this;
        }

        public Criteria andStatistics_Type_CodeLessThan(String value) {
            addCriterion("Statistics_Type_Code <", value, "statistics_Type_Code");
            return (Criteria) this;
        }

        public Criteria andStatistics_Type_CodeLessThanOrEqualTo(String value) {
            addCriterion("Statistics_Type_Code <=", value, "statistics_Type_Code");
            return (Criteria) this;
        }

        public Criteria andStatistics_Type_CodeLike(String value) {
            addCriterion("Statistics_Type_Code like", value, "statistics_Type_Code");
            return (Criteria) this;
        }

        public Criteria andStatistics_Type_CodeNotLike(String value) {
            addCriterion("Statistics_Type_Code not like", value, "statistics_Type_Code");
            return (Criteria) this;
        }

        public Criteria andStatistics_Type_CodeIn(List<String> values) {
            addCriterion("Statistics_Type_Code in", values, "statistics_Type_Code");
            return (Criteria) this;
        }

        public Criteria andStatistics_Type_CodeNotIn(List<String> values) {
            addCriterion("Statistics_Type_Code not in", values, "statistics_Type_Code");
            return (Criteria) this;
        }

        public Criteria andStatistics_Type_CodeBetween(String value1, String value2) {
            addCriterion("Statistics_Type_Code between", value1, value2, "statistics_Type_Code");
            return (Criteria) this;
        }

        public Criteria andStatistics_Type_CodeNotBetween(String value1, String value2) {
            addCriterion("Statistics_Type_Code not between", value1, value2, "statistics_Type_Code");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalIsNull() {
            addCriterion("Submit_Total is null");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalIsNotNull() {
            addCriterion("Submit_Total is not null");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalEqualTo(Integer value) {
            addCriterion("Submit_Total =", value, "submit_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalNotEqualTo(Integer value) {
            addCriterion("Submit_Total <>", value, "submit_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalGreaterThan(Integer value) {
            addCriterion("Submit_Total >", value, "submit_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("Submit_Total >=", value, "submit_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalLessThan(Integer value) {
            addCriterion("Submit_Total <", value, "submit_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalLessThanOrEqualTo(Integer value) {
            addCriterion("Submit_Total <=", value, "submit_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalIn(List<Integer> values) {
            addCriterion("Submit_Total in", values, "submit_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalNotIn(List<Integer> values) {
            addCriterion("Submit_Total not in", values, "submit_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalBetween(Integer value1, Integer value2) {
            addCriterion("Submit_Total between", value1, value2, "submit_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalNotBetween(Integer value1, Integer value2) {
            addCriterion("Submit_Total not between", value1, value2, "submit_Total");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalIsNull() {
            addCriterion("Sort_Faild_Total is null");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalIsNotNull() {
            addCriterion("Sort_Faild_Total is not null");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalEqualTo(Integer value) {
            addCriterion("Sort_Faild_Total =", value, "sort_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalNotEqualTo(Integer value) {
            addCriterion("Sort_Faild_Total <>", value, "sort_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalGreaterThan(Integer value) {
            addCriterion("Sort_Faild_Total >", value, "sort_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("Sort_Faild_Total >=", value, "sort_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalLessThan(Integer value) {
            addCriterion("Sort_Faild_Total <", value, "sort_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalLessThanOrEqualTo(Integer value) {
            addCriterion("Sort_Faild_Total <=", value, "sort_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalIn(List<Integer> values) {
            addCriterion("Sort_Faild_Total in", values, "sort_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalNotIn(List<Integer> values) {
            addCriterion("Sort_Faild_Total not in", values, "sort_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalBetween(Integer value1, Integer value2) {
            addCriterion("Sort_Faild_Total between", value1, value2, "sort_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalNotBetween(Integer value1, Integer value2) {
            addCriterion("Sort_Faild_Total not between", value1, value2, "sort_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalIsNull() {
            addCriterion("Submit_Success_Total is null");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalIsNotNull() {
            addCriterion("Submit_Success_Total is not null");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalEqualTo(Integer value) {
            addCriterion("Submit_Success_Total =", value, "submit_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalNotEqualTo(Integer value) {
            addCriterion("Submit_Success_Total <>", value, "submit_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalGreaterThan(Integer value) {
            addCriterion("Submit_Success_Total >", value, "submit_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("Submit_Success_Total >=", value, "submit_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalLessThan(Integer value) {
            addCriterion("Submit_Success_Total <", value, "submit_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalLessThanOrEqualTo(Integer value) {
            addCriterion("Submit_Success_Total <=", value, "submit_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalIn(List<Integer> values) {
            addCriterion("Submit_Success_Total in", values, "submit_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalNotIn(List<Integer> values) {
            addCriterion("Submit_Success_Total not in", values, "submit_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalBetween(Integer value1, Integer value2) {
            addCriterion("Submit_Success_Total between", value1, value2, "submit_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalNotBetween(Integer value1, Integer value2) {
            addCriterion("Submit_Success_Total not between", value1, value2, "submit_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalIsNull() {
            addCriterion("Submit_Faild_Total is null");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalIsNotNull() {
            addCriterion("Submit_Faild_Total is not null");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalEqualTo(Integer value) {
            addCriterion("Submit_Faild_Total =", value, "submit_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalNotEqualTo(Integer value) {
            addCriterion("Submit_Faild_Total <>", value, "submit_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalGreaterThan(Integer value) {
            addCriterion("Submit_Faild_Total >", value, "submit_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("Submit_Faild_Total >=", value, "submit_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalLessThan(Integer value) {
            addCriterion("Submit_Faild_Total <", value, "submit_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalLessThanOrEqualTo(Integer value) {
            addCriterion("Submit_Faild_Total <=", value, "submit_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalIn(List<Integer> values) {
            addCriterion("Submit_Faild_Total in", values, "submit_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalNotIn(List<Integer> values) {
            addCriterion("Submit_Faild_Total not in", values, "submit_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalBetween(Integer value1, Integer value2) {
            addCriterion("Submit_Faild_Total between", value1, value2, "submit_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalNotBetween(Integer value1, Integer value2) {
            addCriterion("Submit_Faild_Total not between", value1, value2, "submit_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalIsNull() {
            addCriterion("Send_Success_Total is null");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalIsNotNull() {
            addCriterion("Send_Success_Total is not null");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalEqualTo(Integer value) {
            addCriterion("Send_Success_Total =", value, "send_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalNotEqualTo(Integer value) {
            addCriterion("Send_Success_Total <>", value, "send_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalGreaterThan(Integer value) {
            addCriterion("Send_Success_Total >", value, "send_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("Send_Success_Total >=", value, "send_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalLessThan(Integer value) {
            addCriterion("Send_Success_Total <", value, "send_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalLessThanOrEqualTo(Integer value) {
            addCriterion("Send_Success_Total <=", value, "send_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalIn(List<Integer> values) {
            addCriterion("Send_Success_Total in", values, "send_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalNotIn(List<Integer> values) {
            addCriterion("Send_Success_Total not in", values, "send_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalBetween(Integer value1, Integer value2) {
            addCriterion("Send_Success_Total between", value1, value2, "send_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalNotBetween(Integer value1, Integer value2) {
            addCriterion("Send_Success_Total not between", value1, value2, "send_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalIsNull() {
            addCriterion("Send_Faild_Total is null");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalIsNotNull() {
            addCriterion("Send_Faild_Total is not null");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalEqualTo(Integer value) {
            addCriterion("Send_Faild_Total =", value, "send_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalNotEqualTo(Integer value) {
            addCriterion("Send_Faild_Total <>", value, "send_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalGreaterThan(Integer value) {
            addCriterion("Send_Faild_Total >", value, "send_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("Send_Faild_Total >=", value, "send_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalLessThan(Integer value) {
            addCriterion("Send_Faild_Total <", value, "send_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalLessThanOrEqualTo(Integer value) {
            addCriterion("Send_Faild_Total <=", value, "send_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalIn(List<Integer> values) {
            addCriterion("Send_Faild_Total in", values, "send_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalNotIn(List<Integer> values) {
            addCriterion("Send_Faild_Total not in", values, "send_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalBetween(Integer value1, Integer value2) {
            addCriterion("Send_Faild_Total between", value1, value2, "send_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalNotBetween(Integer value1, Integer value2) {
            addCriterion("Send_Faild_Total not between", value1, value2, "send_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalIsNull() {
            addCriterion("Send_Unknown_Total is null");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalIsNotNull() {
            addCriterion("Send_Unknown_Total is not null");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalEqualTo(Integer value) {
            addCriterion("Send_Unknown_Total =", value, "send_Unknown_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalNotEqualTo(Integer value) {
            addCriterion("Send_Unknown_Total <>", value, "send_Unknown_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalGreaterThan(Integer value) {
            addCriterion("Send_Unknown_Total >", value, "send_Unknown_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("Send_Unknown_Total >=", value, "send_Unknown_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalLessThan(Integer value) {
            addCriterion("Send_Unknown_Total <", value, "send_Unknown_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalLessThanOrEqualTo(Integer value) {
            addCriterion("Send_Unknown_Total <=", value, "send_Unknown_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalIn(List<Integer> values) {
            addCriterion("Send_Unknown_Total in", values, "send_Unknown_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalNotIn(List<Integer> values) {
            addCriterion("Send_Unknown_Total not in", values, "send_Unknown_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalBetween(Integer value1, Integer value2) {
            addCriterion("Send_Unknown_Total between", value1, value2, "send_Unknown_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalNotBetween(Integer value1, Integer value2) {
            addCriterion("Send_Unknown_Total not between", value1, value2, "send_Unknown_Total");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateIsNull() {
            addCriterion("Statistics_Date is null");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateIsNotNull() {
            addCriterion("Statistics_Date is not null");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateEqualTo(Date value) {
            addCriterionForJDBCDate("Statistics_Date =", value, "statistics_Date");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateNotEqualTo(Date value) {
            addCriterionForJDBCDate("Statistics_Date <>", value, "statistics_Date");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateGreaterThan(Date value) {
            addCriterionForJDBCDate("Statistics_Date >", value, "statistics_Date");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("Statistics_Date >=", value, "statistics_Date");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateLessThan(Date value) {
            addCriterionForJDBCDate("Statistics_Date <", value, "statistics_Date");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("Statistics_Date <=", value, "statistics_Date");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateIn(List<Date> values) {
            addCriterionForJDBCDate("Statistics_Date in", values, "statistics_Date");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateNotIn(List<Date> values) {
            addCriterionForJDBCDate("Statistics_Date not in", values, "statistics_Date");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("Statistics_Date between", value1, value2, "statistics_Date");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("Statistics_Date not between", value1, value2, "statistics_Date");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNull() {
            addCriterion("Description is null");
            return (Criteria) this;
        }

        public Criteria andDescriptionIsNotNull() {
            addCriterion("Description is not null");
            return (Criteria) this;
        }

        public Criteria andDescriptionEqualTo(String value) {
            addCriterion("Description =", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotEqualTo(String value) {
            addCriterion("Description <>", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThan(String value) {
            addCriterion("Description >", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionGreaterThanOrEqualTo(String value) {
            addCriterion("Description >=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThan(String value) {
            addCriterion("Description <", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLessThanOrEqualTo(String value) {
            addCriterion("Description <=", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionLike(String value) {
            addCriterion("Description like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotLike(String value) {
            addCriterion("Description not like", value, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionIn(List<String> values) {
            addCriterion("Description in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotIn(List<String> values) {
            addCriterion("Description not in", values, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionBetween(String value1, String value2) {
            addCriterion("Description between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andDescriptionNotBetween(String value1, String value2) {
            addCriterion("Description not between", value1, value2, "description");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("Remark is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("Remark is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("Remark =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("Remark <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("Remark >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("Remark >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("Remark <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("Remark <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("Remark like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("Remark not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("Remark in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("Remark not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("Remark between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("Remark not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCreate_DateIsNull() {
            addCriterion("Create_Date is null");
            return (Criteria) this;
        }

        public Criteria andCreate_DateIsNotNull() {
            addCriterion("Create_Date is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_DateEqualTo(Date value) {
            addCriterion("Create_Date =", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateNotEqualTo(Date value) {
            addCriterion("Create_Date <>", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateGreaterThan(Date value) {
            addCriterion("Create_Date >", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateGreaterThanOrEqualTo(Date value) {
            addCriterion("Create_Date >=", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateLessThan(Date value) {
            addCriterion("Create_Date <", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateLessThanOrEqualTo(Date value) {
            addCriterion("Create_Date <=", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateIn(List<Date> values) {
            addCriterion("Create_Date in", values, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateNotIn(List<Date> values) {
            addCriterion("Create_Date not in", values, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateBetween(Date value1, Date value2) {
            addCriterion("Create_Date between", value1, value2, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateNotBetween(Date value1, Date value2) {
            addCriterion("Create_Date not between", value1, value2, "create_Date");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated do_not_delete_during_merge Wed Jun 10 18:52:20 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}