package com.hero.wireless.web.entity.business;

import com.hero.wireless.web.entity.base.BaseExample;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ProductExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    protected String dataLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setDataLock(String dataLock) {
        this.dataLock = dataLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getDataLock() {
        return dataLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("Name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("Name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("Name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("Name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("Name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("Name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("Name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("Name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("Name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("Name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("Name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("Name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("Name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("Name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNoIsNull() {
            addCriterion("No is null");
            return (Criteria) this;
        }

        public Criteria andNoIsNotNull() {
            addCriterion("No is not null");
            return (Criteria) this;
        }

        public Criteria andNoEqualTo(String value) {
            addCriterion("No =", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotEqualTo(String value) {
            addCriterion("No <>", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoGreaterThan(String value) {
            addCriterion("No >", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoGreaterThanOrEqualTo(String value) {
            addCriterion("No >=", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLessThan(String value) {
            addCriterion("No <", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLessThanOrEqualTo(String value) {
            addCriterion("No <=", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLike(String value) {
            addCriterion("No like", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotLike(String value) {
            addCriterion("No not like", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoIn(List<String> values) {
            addCriterion("No in", values, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotIn(List<String> values) {
            addCriterion("No not in", values, "no");
            return (Criteria) this;
        }

        public Criteria andNoBetween(String value1, String value2) {
            addCriterion("No between", value1, value2, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotBetween(String value1, String value2) {
            addCriterion("No not between", value1, value2, "no");
            return (Criteria) this;
        }

        public Criteria andTrade_Type_CodeIsNull() {
            addCriterion("Trade_Type_Code is null");
            return (Criteria) this;
        }

        public Criteria andTrade_Type_CodeIsNotNull() {
            addCriterion("Trade_Type_Code is not null");
            return (Criteria) this;
        }

        public Criteria andTrade_Type_CodeEqualTo(String value) {
            addCriterion("Trade_Type_Code =", value, "trade_Type_Code");
            return (Criteria) this;
        }

        public Criteria andTrade_Type_CodeNotEqualTo(String value) {
            addCriterion("Trade_Type_Code <>", value, "trade_Type_Code");
            return (Criteria) this;
        }

        public Criteria andTrade_Type_CodeGreaterThan(String value) {
            addCriterion("Trade_Type_Code >", value, "trade_Type_Code");
            return (Criteria) this;
        }

        public Criteria andTrade_Type_CodeGreaterThanOrEqualTo(String value) {
            addCriterion("Trade_Type_Code >=", value, "trade_Type_Code");
            return (Criteria) this;
        }

        public Criteria andTrade_Type_CodeLessThan(String value) {
            addCriterion("Trade_Type_Code <", value, "trade_Type_Code");
            return (Criteria) this;
        }

        public Criteria andTrade_Type_CodeLessThanOrEqualTo(String value) {
            addCriterion("Trade_Type_Code <=", value, "trade_Type_Code");
            return (Criteria) this;
        }

        public Criteria andTrade_Type_CodeLike(String value) {
            addCriterion("Trade_Type_Code like", value, "trade_Type_Code");
            return (Criteria) this;
        }

        public Criteria andTrade_Type_CodeNotLike(String value) {
            addCriterion("Trade_Type_Code not like", value, "trade_Type_Code");
            return (Criteria) this;
        }

        public Criteria andTrade_Type_CodeIn(List<String> values) {
            addCriterion("Trade_Type_Code in", values, "trade_Type_Code");
            return (Criteria) this;
        }

        public Criteria andTrade_Type_CodeNotIn(List<String> values) {
            addCriterion("Trade_Type_Code not in", values, "trade_Type_Code");
            return (Criteria) this;
        }

        public Criteria andTrade_Type_CodeBetween(String value1, String value2) {
            addCriterion("Trade_Type_Code between", value1, value2, "trade_Type_Code");
            return (Criteria) this;
        }

        public Criteria andTrade_Type_CodeNotBetween(String value1, String value2) {
            addCriterion("Trade_Type_Code not between", value1, value2, "trade_Type_Code");
            return (Criteria) this;
        }

        public Criteria andStatus_CodeIsNull() {
            addCriterion("Status_Code is null");
            return (Criteria) this;
        }

        public Criteria andStatus_CodeIsNotNull() {
            addCriterion("Status_Code is not null");
            return (Criteria) this;
        }

        public Criteria andStatus_CodeEqualTo(String value) {
            addCriterion("Status_Code =", value, "status_Code");
            return (Criteria) this;
        }

        public Criteria andStatus_CodeNotEqualTo(String value) {
            addCriterion("Status_Code <>", value, "status_Code");
            return (Criteria) this;
        }

        public Criteria andStatus_CodeGreaterThan(String value) {
            addCriterion("Status_Code >", value, "status_Code");
            return (Criteria) this;
        }

        public Criteria andStatus_CodeGreaterThanOrEqualTo(String value) {
            addCriterion("Status_Code >=", value, "status_Code");
            return (Criteria) this;
        }

        public Criteria andStatus_CodeLessThan(String value) {
            addCriterion("Status_Code <", value, "status_Code");
            return (Criteria) this;
        }

        public Criteria andStatus_CodeLessThanOrEqualTo(String value) {
            addCriterion("Status_Code <=", value, "status_Code");
            return (Criteria) this;
        }

        public Criteria andStatus_CodeLike(String value) {
            addCriterion("Status_Code like", value, "status_Code");
            return (Criteria) this;
        }

        public Criteria andStatus_CodeNotLike(String value) {
            addCriterion("Status_Code not like", value, "status_Code");
            return (Criteria) this;
        }

        public Criteria andStatus_CodeIn(List<String> values) {
            addCriterion("Status_Code in", values, "status_Code");
            return (Criteria) this;
        }

        public Criteria andStatus_CodeNotIn(List<String> values) {
            addCriterion("Status_Code not in", values, "status_Code");
            return (Criteria) this;
        }

        public Criteria andStatus_CodeBetween(String value1, String value2) {
            addCriterion("Status_Code between", value1, value2, "status_Code");
            return (Criteria) this;
        }

        public Criteria andStatus_CodeNotBetween(String value1, String value2) {
            addCriterion("Status_Code not between", value1, value2, "status_Code");
            return (Criteria) this;
        }

        public Criteria andIntercept_Strategy_IdIsNull() {
            addCriterion("Intercept_Strategy_Id is null");
            return (Criteria) this;
        }

        public Criteria andIntercept_Strategy_IdIsNotNull() {
            addCriterion("Intercept_Strategy_Id is not null");
            return (Criteria) this;
        }

        public Criteria andIntercept_Strategy_IdEqualTo(Integer value) {
            addCriterion("Intercept_Strategy_Id =", value, "intercept_Strategy_Id");
            return (Criteria) this;
        }

        public Criteria andIntercept_Strategy_IdNotEqualTo(Integer value) {
            addCriterion("Intercept_Strategy_Id <>", value, "intercept_Strategy_Id");
            return (Criteria) this;
        }

        public Criteria andIntercept_Strategy_IdGreaterThan(Integer value) {
            addCriterion("Intercept_Strategy_Id >", value, "intercept_Strategy_Id");
            return (Criteria) this;
        }

        public Criteria andIntercept_Strategy_IdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Intercept_Strategy_Id >=", value, "intercept_Strategy_Id");
            return (Criteria) this;
        }

        public Criteria andIntercept_Strategy_IdLessThan(Integer value) {
            addCriterion("Intercept_Strategy_Id <", value, "intercept_Strategy_Id");
            return (Criteria) this;
        }

        public Criteria andIntercept_Strategy_IdLessThanOrEqualTo(Integer value) {
            addCriterion("Intercept_Strategy_Id <=", value, "intercept_Strategy_Id");
            return (Criteria) this;
        }

        public Criteria andIntercept_Strategy_IdIn(List<Integer> values) {
            addCriterion("Intercept_Strategy_Id in", values, "intercept_Strategy_Id");
            return (Criteria) this;
        }

        public Criteria andIntercept_Strategy_IdNotIn(List<Integer> values) {
            addCriterion("Intercept_Strategy_Id not in", values, "intercept_Strategy_Id");
            return (Criteria) this;
        }

        public Criteria andIntercept_Strategy_IdBetween(Integer value1, Integer value2) {
            addCriterion("Intercept_Strategy_Id between", value1, value2, "intercept_Strategy_Id");
            return (Criteria) this;
        }

        public Criteria andIntercept_Strategy_IdNotBetween(Integer value1, Integer value2) {
            addCriterion("Intercept_Strategy_Id not between", value1, value2, "intercept_Strategy_Id");
            return (Criteria) this;
        }

        public Criteria andCreate_DateIsNull() {
            addCriterion("Create_Date is null");
            return (Criteria) this;
        }

        public Criteria andCreate_DateIsNotNull() {
            addCriterion("Create_Date is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_DateEqualTo(Date value) {
            addCriterion("Create_Date =", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateNotEqualTo(Date value) {
            addCriterion("Create_Date <>", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateGreaterThan(Date value) {
            addCriterion("Create_Date >", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateGreaterThanOrEqualTo(Date value) {
            addCriterion("Create_Date >=", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateLessThan(Date value) {
            addCriterion("Create_Date <", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateLessThanOrEqualTo(Date value) {
            addCriterion("Create_Date <=", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateIn(List<Date> values) {
            addCriterion("Create_Date in", values, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateNotIn(List<Date> values) {
            addCriterion("Create_Date not in", values, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateBetween(Date value1, Date value2) {
            addCriterion("Create_Date between", value1, value2, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateNotBetween(Date value1, Date value2) {
            addCriterion("Create_Date not between", value1, value2, "create_Date");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated do_not_delete_during_merge Thu May 14 09:56:20 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table product
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}