package com.hero.wireless.web.entity.business;

import com.hero.wireless.web.entity.base.BaseEntity;

import java.util.Date;

public class Properties extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column properties.Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column properties.Type_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String type_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column properties.Type_Code_Num
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String type_Code_Num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column properties.Property_Name
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String property_Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column properties.Property_Value
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String property_Value;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column properties.Extended_Field
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String extended_Field;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column properties.Remark
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column properties.Description
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column properties.Create_Date
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private Date create_Date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column properties.Id
     *
     * @return the value of properties.Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column properties.Id
     *
     * @param id the value for properties.Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column properties.Type_Code
     *
     * @return the value of properties.Type_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getType_Code() {
        return type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column properties.Type_Code
     *
     * @param type_Code the value for properties.Type_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setType_Code(String type_Code) {
        this.type_Code = type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column properties.Type_Code_Num
     *
     * @return the value of properties.Type_Code_Num
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getType_Code_Num() {
        return type_Code_Num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column properties.Type_Code_Num
     *
     * @param type_Code_Num the value for properties.Type_Code_Num
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setType_Code_Num(String type_Code_Num) {
        this.type_Code_Num = type_Code_Num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column properties.Property_Name
     *
     * @return the value of properties.Property_Name
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getProperty_Name() {
        return property_Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column properties.Property_Name
     *
     * @param property_Name the value for properties.Property_Name
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setProperty_Name(String property_Name) {
        this.property_Name = property_Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column properties.Property_Value
     *
     * @return the value of properties.Property_Value
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getProperty_Value() {
        return property_Value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column properties.Property_Value
     *
     * @param property_Value the value for properties.Property_Value
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setProperty_Value(String property_Value) {
        this.property_Value = property_Value;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column properties.Extended_Field
     *
     * @return the value of properties.Extended_Field
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getExtended_Field() {
        return extended_Field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column properties.Extended_Field
     *
     * @param extended_Field the value for properties.Extended_Field
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setExtended_Field(String extended_Field) {
        this.extended_Field = extended_Field;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column properties.Remark
     *
     * @return the value of properties.Remark
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column properties.Remark
     *
     * @param remark the value for properties.Remark
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column properties.Description
     *
     * @return the value of properties.Description
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column properties.Description
     *
     * @param description the value for properties.Description
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column properties.Create_Date
     *
     * @return the value of properties.Create_Date
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public Date getCreate_Date() {
        return create_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column properties.Create_Date
     *
     * @param create_Date the value for properties.Create_Date
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setCreate_Date(Date create_Date) {
        this.create_Date = create_Date;
    }
}