package com.hero.wireless.web.entity.business;

import com.hero.wireless.web.entity.base.BaseEntity;

import java.util.Date;

public class SensitiveWord extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.Pool_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String pool_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.Word
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String word;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.Trade_Type_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String trade_Type_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.Create_User
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String create_User;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.Description
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.Remark
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sensitive_word.Create_Date
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    private Date create_Date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.Id
     *
     * @return the value of sensitive_word.Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.Id
     *
     * @param id the value for sensitive_word.Id
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.Pool_Code
     *
     * @return the value of sensitive_word.Pool_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getPool_Code() {
        return pool_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.Pool_Code
     *
     * @param pool_Code the value for sensitive_word.Pool_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setPool_Code(String pool_Code) {
        this.pool_Code = pool_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.Word
     *
     * @return the value of sensitive_word.Word
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getWord() {
        return word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.Word
     *
     * @param word the value for sensitive_word.Word
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setWord(String word) {
        this.word = word;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.Trade_Type_Code
     *
     * @return the value of sensitive_word.Trade_Type_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getTrade_Type_Code() {
        return trade_Type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.Trade_Type_Code
     *
     * @param trade_Type_Code the value for sensitive_word.Trade_Type_Code
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setTrade_Type_Code(String trade_Type_Code) {
        this.trade_Type_Code = trade_Type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.Create_User
     *
     * @return the value of sensitive_word.Create_User
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getCreate_User() {
        return create_User;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.Create_User
     *
     * @param create_User the value for sensitive_word.Create_User
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setCreate_User(String create_User) {
        this.create_User = create_User;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.Description
     *
     * @return the value of sensitive_word.Description
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.Description
     *
     * @param description the value for sensitive_word.Description
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.Remark
     *
     * @return the value of sensitive_word.Remark
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.Remark
     *
     * @param remark the value for sensitive_word.Remark
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sensitive_word.Create_Date
     *
     * @return the value of sensitive_word.Create_Date
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public Date getCreate_Date() {
        return create_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sensitive_word.Create_Date
     *
     * @param create_Date the value for sensitive_word.Create_Date
     *
     * @mbg.generated Thu May 14 09:56:20 CST 2020
     */
    public void setCreate_Date(Date create_Date) {
        this.create_Date = create_Date;
    }
}