package com.hero.wireless.web.entity.business;

import com.hero.wireless.web.entity.base.BaseExample;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class SmsStatisticsExample extends BaseExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    protected String dataLock;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public SmsStatisticsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setDataLock(String dataLock) {
        this.dataLock = dataLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public String getDataLock() {
        return dataLock;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        public void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        public void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        public void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("Id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("Id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("Id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("Id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("Id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("Id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("Id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("Id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("Id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("Id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("Id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andChannel_NoIsNull() {
            addCriterion("Channel_No is null");
            return (Criteria) this;
        }

        public Criteria andChannel_NoIsNotNull() {
            addCriterion("Channel_No is not null");
            return (Criteria) this;
        }

        public Criteria andChannel_NoEqualTo(String value) {
            addCriterion("Channel_No =", value, "channel_No");
            return (Criteria) this;
        }

        public Criteria andChannel_NoNotEqualTo(String value) {
            addCriterion("Channel_No <>", value, "channel_No");
            return (Criteria) this;
        }

        public Criteria andChannel_NoGreaterThan(String value) {
            addCriterion("Channel_No >", value, "channel_No");
            return (Criteria) this;
        }

        public Criteria andChannel_NoGreaterThanOrEqualTo(String value) {
            addCriterion("Channel_No >=", value, "channel_No");
            return (Criteria) this;
        }

        public Criteria andChannel_NoLessThan(String value) {
            addCriterion("Channel_No <", value, "channel_No");
            return (Criteria) this;
        }

        public Criteria andChannel_NoLessThanOrEqualTo(String value) {
            addCriterion("Channel_No <=", value, "channel_No");
            return (Criteria) this;
        }

        public Criteria andChannel_NoLike(String value) {
            addCriterion("Channel_No like", value, "channel_No");
            return (Criteria) this;
        }

        public Criteria andChannel_NoNotLike(String value) {
            addCriterion("Channel_No not like", value, "channel_No");
            return (Criteria) this;
        }

        public Criteria andChannel_NoIn(List<String> values) {
            addCriterion("Channel_No in", values, "channel_No");
            return (Criteria) this;
        }

        public Criteria andChannel_NoNotIn(List<String> values) {
            addCriterion("Channel_No not in", values, "channel_No");
            return (Criteria) this;
        }

        public Criteria andChannel_NoBetween(String value1, String value2) {
            addCriterion("Channel_No between", value1, value2, "channel_No");
            return (Criteria) this;
        }

        public Criteria andChannel_NoNotBetween(String value1, String value2) {
            addCriterion("Channel_No not between", value1, value2, "channel_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoIsNull() {
            addCriterion("Enterprise_No is null");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoIsNotNull() {
            addCriterion("Enterprise_No is not null");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoEqualTo(String value) {
            addCriterion("Enterprise_No =", value, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoNotEqualTo(String value) {
            addCriterion("Enterprise_No <>", value, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoGreaterThan(String value) {
            addCriterion("Enterprise_No >", value, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoGreaterThanOrEqualTo(String value) {
            addCriterion("Enterprise_No >=", value, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoLessThan(String value) {
            addCriterion("Enterprise_No <", value, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoLessThanOrEqualTo(String value) {
            addCriterion("Enterprise_No <=", value, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoLike(String value) {
            addCriterion("Enterprise_No like", value, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoNotLike(String value) {
            addCriterion("Enterprise_No not like", value, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoIn(List<String> values) {
            addCriterion("Enterprise_No in", values, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoNotIn(List<String> values) {
            addCriterion("Enterprise_No not in", values, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoBetween(String value1, String value2) {
            addCriterion("Enterprise_No between", value1, value2, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_NoNotBetween(String value1, String value2) {
            addCriterion("Enterprise_No not between", value1, value2, "enterprise_No");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdIsNull() {
            addCriterion("Enterprise_User_Id is null");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdIsNotNull() {
            addCriterion("Enterprise_User_Id is not null");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdEqualTo(Integer value) {
            addCriterion("Enterprise_User_Id =", value, "enterprise_User_Id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdNotEqualTo(Integer value) {
            addCriterion("Enterprise_User_Id <>", value, "enterprise_User_Id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdGreaterThan(Integer value) {
            addCriterion("Enterprise_User_Id >", value, "enterprise_User_Id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Enterprise_User_Id >=", value, "enterprise_User_Id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdLessThan(Integer value) {
            addCriterion("Enterprise_User_Id <", value, "enterprise_User_Id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdLessThanOrEqualTo(Integer value) {
            addCriterion("Enterprise_User_Id <=", value, "enterprise_User_Id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdIn(List<Integer> values) {
            addCriterion("Enterprise_User_Id in", values, "enterprise_User_Id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdNotIn(List<Integer> values) {
            addCriterion("Enterprise_User_Id not in", values, "enterprise_User_Id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdBetween(Integer value1, Integer value2) {
            addCriterion("Enterprise_User_Id between", value1, value2, "enterprise_User_Id");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_IdNotBetween(Integer value1, Integer value2) {
            addCriterion("Enterprise_User_Id not between", value1, value2, "enterprise_User_Id");
            return (Criteria) this;
        }

        public Criteria andCountry_NumberIsNull() {
            addCriterion("Country_Number is null");
            return (Criteria) this;
        }

        public Criteria andCountry_NumberIsNotNull() {
            addCriterion("Country_Number is not null");
            return (Criteria) this;
        }

        public Criteria andCountry_NumberEqualTo(String value) {
            addCriterion("Country_Number =", value, "country_Number");
            return (Criteria) this;
        }

        public Criteria andCountry_NumberNotEqualTo(String value) {
            addCriterion("Country_Number <>", value, "country_Number");
            return (Criteria) this;
        }

        public Criteria andCountry_NumberGreaterThan(String value) {
            addCriterion("Country_Number >", value, "country_Number");
            return (Criteria) this;
        }

        public Criteria andCountry_NumberGreaterThanOrEqualTo(String value) {
            addCriterion("Country_Number >=", value, "country_Number");
            return (Criteria) this;
        }

        public Criteria andCountry_NumberLessThan(String value) {
            addCriterion("Country_Number <", value, "country_Number");
            return (Criteria) this;
        }

        public Criteria andCountry_NumberLessThanOrEqualTo(String value) {
            addCriterion("Country_Number <=", value, "country_Number");
            return (Criteria) this;
        }

        public Criteria andCountry_NumberLike(String value) {
            addCriterion("Country_Number like", value, "country_Number");
            return (Criteria) this;
        }

        public Criteria andCountry_NumberNotLike(String value) {
            addCriterion("Country_Number not like", value, "country_Number");
            return (Criteria) this;
        }

        public Criteria andCountry_NumberIn(List<String> values) {
            addCriterion("Country_Number in", values, "country_Number");
            return (Criteria) this;
        }

        public Criteria andCountry_NumberNotIn(List<String> values) {
            addCriterion("Country_Number not in", values, "country_Number");
            return (Criteria) this;
        }

        public Criteria andCountry_NumberBetween(String value1, String value2) {
            addCriterion("Country_Number between", value1, value2, "country_Number");
            return (Criteria) this;
        }

        public Criteria andCountry_NumberNotBetween(String value1, String value2) {
            addCriterion("Country_Number not between", value1, value2, "country_Number");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNull() {
            addCriterion("Operator is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIsNotNull() {
            addCriterion("Operator is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorEqualTo(String value) {
            addCriterion("Operator =", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotEqualTo(String value) {
            addCriterion("Operator <>", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThan(String value) {
            addCriterion("Operator >", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorGreaterThanOrEqualTo(String value) {
            addCriterion("Operator >=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThan(String value) {
            addCriterion("Operator <", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLessThanOrEqualTo(String value) {
            addCriterion("Operator <=", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorLike(String value) {
            addCriterion("Operator like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotLike(String value) {
            addCriterion("Operator not like", value, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorIn(List<String> values) {
            addCriterion("Operator in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotIn(List<String> values) {
            addCriterion("Operator not in", values, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorBetween(String value1, String value2) {
            addCriterion("Operator between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andOperatorNotBetween(String value1, String value2) {
            addCriterion("Operator not between", value1, value2, "operator");
            return (Criteria) this;
        }

        public Criteria andAgent_NoIsNull() {
            addCriterion("Agent_No is null");
            return (Criteria) this;
        }

        public Criteria andAgent_NoIsNotNull() {
            addCriterion("Agent_No is not null");
            return (Criteria) this;
        }

        public Criteria andAgent_NoEqualTo(String value) {
            addCriterion("Agent_No =", value, "agent_No");
            return (Criteria) this;
        }

        public Criteria andAgent_NoNotEqualTo(String value) {
            addCriterion("Agent_No <>", value, "agent_No");
            return (Criteria) this;
        }

        public Criteria andAgent_NoGreaterThan(String value) {
            addCriterion("Agent_No >", value, "agent_No");
            return (Criteria) this;
        }

        public Criteria andAgent_NoGreaterThanOrEqualTo(String value) {
            addCriterion("Agent_No >=", value, "agent_No");
            return (Criteria) this;
        }

        public Criteria andAgent_NoLessThan(String value) {
            addCriterion("Agent_No <", value, "agent_No");
            return (Criteria) this;
        }

        public Criteria andAgent_NoLessThanOrEqualTo(String value) {
            addCriterion("Agent_No <=", value, "agent_No");
            return (Criteria) this;
        }

        public Criteria andAgent_NoLike(String value) {
            addCriterion("Agent_No like", value, "agent_No");
            return (Criteria) this;
        }

        public Criteria andAgent_NoNotLike(String value) {
            addCriterion("Agent_No not like", value, "agent_No");
            return (Criteria) this;
        }

        public Criteria andAgent_NoIn(List<String> values) {
            addCriterion("Agent_No in", values, "agent_No");
            return (Criteria) this;
        }

        public Criteria andAgent_NoNotIn(List<String> values) {
            addCriterion("Agent_No not in", values, "agent_No");
            return (Criteria) this;
        }

        public Criteria andAgent_NoBetween(String value1, String value2) {
            addCriterion("Agent_No between", value1, value2, "agent_No");
            return (Criteria) this;
        }

        public Criteria andAgent_NoNotBetween(String value1, String value2) {
            addCriterion("Agent_No not between", value1, value2, "agent_No");
            return (Criteria) this;
        }

        public Criteria andProvince_CodeIsNull() {
            addCriterion("Province_Code is null");
            return (Criteria) this;
        }

        public Criteria andProvince_CodeIsNotNull() {
            addCriterion("Province_Code is not null");
            return (Criteria) this;
        }

        public Criteria andProvince_CodeEqualTo(String value) {
            addCriterion("Province_Code =", value, "province_Code");
            return (Criteria) this;
        }

        public Criteria andProvince_CodeNotEqualTo(String value) {
            addCriterion("Province_Code <>", value, "province_Code");
            return (Criteria) this;
        }

        public Criteria andProvince_CodeGreaterThan(String value) {
            addCriterion("Province_Code >", value, "province_Code");
            return (Criteria) this;
        }

        public Criteria andProvince_CodeGreaterThanOrEqualTo(String value) {
            addCriterion("Province_Code >=", value, "province_Code");
            return (Criteria) this;
        }

        public Criteria andProvince_CodeLessThan(String value) {
            addCriterion("Province_Code <", value, "province_Code");
            return (Criteria) this;
        }

        public Criteria andProvince_CodeLessThanOrEqualTo(String value) {
            addCriterion("Province_Code <=", value, "province_Code");
            return (Criteria) this;
        }

        public Criteria andProvince_CodeLike(String value) {
            addCriterion("Province_Code like", value, "province_Code");
            return (Criteria) this;
        }

        public Criteria andProvince_CodeNotLike(String value) {
            addCriterion("Province_Code not like", value, "province_Code");
            return (Criteria) this;
        }

        public Criteria andProvince_CodeIn(List<String> values) {
            addCriterion("Province_Code in", values, "province_Code");
            return (Criteria) this;
        }

        public Criteria andProvince_CodeNotIn(List<String> values) {
            addCriterion("Province_Code not in", values, "province_Code");
            return (Criteria) this;
        }

        public Criteria andProvince_CodeBetween(String value1, String value2) {
            addCriterion("Province_Code between", value1, value2, "province_Code");
            return (Criteria) this;
        }

        public Criteria andProvince_CodeNotBetween(String value1, String value2) {
            addCriterion("Province_Code not between", value1, value2, "province_Code");
            return (Criteria) this;
        }

        public Criteria andMessage_Type_CodeIsNull() {
            addCriterion("Message_Type_Code is null");
            return (Criteria) this;
        }

        public Criteria andMessage_Type_CodeIsNotNull() {
            addCriterion("Message_Type_Code is not null");
            return (Criteria) this;
        }

        public Criteria andMessage_Type_CodeEqualTo(String value) {
            addCriterion("Message_Type_Code =", value, "message_Type_Code");
            return (Criteria) this;
        }

        public Criteria andMessage_Type_CodeNotEqualTo(String value) {
            addCriterion("Message_Type_Code <>", value, "message_Type_Code");
            return (Criteria) this;
        }

        public Criteria andMessage_Type_CodeGreaterThan(String value) {
            addCriterion("Message_Type_Code >", value, "message_Type_Code");
            return (Criteria) this;
        }

        public Criteria andMessage_Type_CodeGreaterThanOrEqualTo(String value) {
            addCriterion("Message_Type_Code >=", value, "message_Type_Code");
            return (Criteria) this;
        }

        public Criteria andMessage_Type_CodeLessThan(String value) {
            addCriterion("Message_Type_Code <", value, "message_Type_Code");
            return (Criteria) this;
        }

        public Criteria andMessage_Type_CodeLessThanOrEqualTo(String value) {
            addCriterion("Message_Type_Code <=", value, "message_Type_Code");
            return (Criteria) this;
        }

        public Criteria andMessage_Type_CodeLike(String value) {
            addCriterion("Message_Type_Code like", value, "message_Type_Code");
            return (Criteria) this;
        }

        public Criteria andMessage_Type_CodeNotLike(String value) {
            addCriterion("Message_Type_Code not like", value, "message_Type_Code");
            return (Criteria) this;
        }

        public Criteria andMessage_Type_CodeIn(List<String> values) {
            addCriterion("Message_Type_Code in", values, "message_Type_Code");
            return (Criteria) this;
        }

        public Criteria andMessage_Type_CodeNotIn(List<String> values) {
            addCriterion("Message_Type_Code not in", values, "message_Type_Code");
            return (Criteria) this;
        }

        public Criteria andMessage_Type_CodeBetween(String value1, String value2) {
            addCriterion("Message_Type_Code between", value1, value2, "message_Type_Code");
            return (Criteria) this;
        }

        public Criteria andMessage_Type_CodeNotBetween(String value1, String value2) {
            addCriterion("Message_Type_Code not between", value1, value2, "message_Type_Code");
            return (Criteria) this;
        }

        public Criteria andProfitsIsNull() {
            addCriterion("Profits is null");
            return (Criteria) this;
        }

        public Criteria andProfitsIsNotNull() {
            addCriterion("Profits is not null");
            return (Criteria) this;
        }

        public Criteria andProfitsEqualTo(BigDecimal value) {
            addCriterion("Profits =", value, "profits");
            return (Criteria) this;
        }

        public Criteria andProfitsNotEqualTo(BigDecimal value) {
            addCriterion("Profits <>", value, "profits");
            return (Criteria) this;
        }

        public Criteria andProfitsGreaterThan(BigDecimal value) {
            addCriterion("Profits >", value, "profits");
            return (Criteria) this;
        }

        public Criteria andProfitsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Profits >=", value, "profits");
            return (Criteria) this;
        }

        public Criteria andProfitsLessThan(BigDecimal value) {
            addCriterion("Profits <", value, "profits");
            return (Criteria) this;
        }

        public Criteria andProfitsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Profits <=", value, "profits");
            return (Criteria) this;
        }

        public Criteria andProfitsIn(List<BigDecimal> values) {
            addCriterion("Profits in", values, "profits");
            return (Criteria) this;
        }

        public Criteria andProfitsNotIn(List<BigDecimal> values) {
            addCriterion("Profits not in", values, "profits");
            return (Criteria) this;
        }

        public Criteria andProfitsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Profits between", value1, value2, "profits");
            return (Criteria) this;
        }

        public Criteria andProfitsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Profits not between", value1, value2, "profits");
            return (Criteria) this;
        }

        public Criteria andAgent_ProfitsIsNull() {
            addCriterion("Agent_Profits is null");
            return (Criteria) this;
        }

        public Criteria andAgent_ProfitsIsNotNull() {
            addCriterion("Agent_Profits is not null");
            return (Criteria) this;
        }

        public Criteria andAgent_ProfitsEqualTo(BigDecimal value) {
            addCriterion("Agent_Profits =", value, "agent_Profits");
            return (Criteria) this;
        }

        public Criteria andAgent_ProfitsNotEqualTo(BigDecimal value) {
            addCriterion("Agent_Profits <>", value, "agent_Profits");
            return (Criteria) this;
        }

        public Criteria andAgent_ProfitsGreaterThan(BigDecimal value) {
            addCriterion("Agent_Profits >", value, "agent_Profits");
            return (Criteria) this;
        }

        public Criteria andAgent_ProfitsGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Agent_Profits >=", value, "agent_Profits");
            return (Criteria) this;
        }

        public Criteria andAgent_ProfitsLessThan(BigDecimal value) {
            addCriterion("Agent_Profits <", value, "agent_Profits");
            return (Criteria) this;
        }

        public Criteria andAgent_ProfitsLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Agent_Profits <=", value, "agent_Profits");
            return (Criteria) this;
        }

        public Criteria andAgent_ProfitsIn(List<BigDecimal> values) {
            addCriterion("Agent_Profits in", values, "agent_Profits");
            return (Criteria) this;
        }

        public Criteria andAgent_ProfitsNotIn(List<BigDecimal> values) {
            addCriterion("Agent_Profits not in", values, "agent_Profits");
            return (Criteria) this;
        }

        public Criteria andAgent_ProfitsBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Agent_Profits between", value1, value2, "agent_Profits");
            return (Criteria) this;
        }

        public Criteria andAgent_ProfitsNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Agent_Profits not between", value1, value2, "agent_Profits");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_TaxesIsNull() {
            addCriterion("Enterprise_User_Taxes is null");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_TaxesIsNotNull() {
            addCriterion("Enterprise_User_Taxes is not null");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_TaxesEqualTo(BigDecimal value) {
            addCriterion("Enterprise_User_Taxes =", value, "enterprise_User_Taxes");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_TaxesNotEqualTo(BigDecimal value) {
            addCriterion("Enterprise_User_Taxes <>", value, "enterprise_User_Taxes");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_TaxesGreaterThan(BigDecimal value) {
            addCriterion("Enterprise_User_Taxes >", value, "enterprise_User_Taxes");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_TaxesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Enterprise_User_Taxes >=", value, "enterprise_User_Taxes");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_TaxesLessThan(BigDecimal value) {
            addCriterion("Enterprise_User_Taxes <", value, "enterprise_User_Taxes");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_TaxesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Enterprise_User_Taxes <=", value, "enterprise_User_Taxes");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_TaxesIn(List<BigDecimal> values) {
            addCriterion("Enterprise_User_Taxes in", values, "enterprise_User_Taxes");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_TaxesNotIn(List<BigDecimal> values) {
            addCriterion("Enterprise_User_Taxes not in", values, "enterprise_User_Taxes");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_TaxesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Enterprise_User_Taxes between", value1, value2, "enterprise_User_Taxes");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_TaxesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Enterprise_User_Taxes not between", value1, value2, "enterprise_User_Taxes");
            return (Criteria) this;
        }

        public Criteria andChannel_TaxesIsNull() {
            addCriterion("Channel_Taxes is null");
            return (Criteria) this;
        }

        public Criteria andChannel_TaxesIsNotNull() {
            addCriterion("Channel_Taxes is not null");
            return (Criteria) this;
        }

        public Criteria andChannel_TaxesEqualTo(BigDecimal value) {
            addCriterion("Channel_Taxes =", value, "channel_Taxes");
            return (Criteria) this;
        }

        public Criteria andChannel_TaxesNotEqualTo(BigDecimal value) {
            addCriterion("Channel_Taxes <>", value, "channel_Taxes");
            return (Criteria) this;
        }

        public Criteria andChannel_TaxesGreaterThan(BigDecimal value) {
            addCriterion("Channel_Taxes >", value, "channel_Taxes");
            return (Criteria) this;
        }

        public Criteria andChannel_TaxesGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Channel_Taxes >=", value, "channel_Taxes");
            return (Criteria) this;
        }

        public Criteria andChannel_TaxesLessThan(BigDecimal value) {
            addCriterion("Channel_Taxes <", value, "channel_Taxes");
            return (Criteria) this;
        }

        public Criteria andChannel_TaxesLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Channel_Taxes <=", value, "channel_Taxes");
            return (Criteria) this;
        }

        public Criteria andChannel_TaxesIn(List<BigDecimal> values) {
            addCriterion("Channel_Taxes in", values, "channel_Taxes");
            return (Criteria) this;
        }

        public Criteria andChannel_TaxesNotIn(List<BigDecimal> values) {
            addCriterion("Channel_Taxes not in", values, "channel_Taxes");
            return (Criteria) this;
        }

        public Criteria andChannel_TaxesBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Channel_Taxes between", value1, value2, "channel_Taxes");
            return (Criteria) this;
        }

        public Criteria andChannel_TaxesNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Channel_Taxes not between", value1, value2, "channel_Taxes");
            return (Criteria) this;
        }

        public Criteria andUnit_CostIsNull() {
            addCriterion("Unit_Cost is null");
            return (Criteria) this;
        }

        public Criteria andUnit_CostIsNotNull() {
            addCriterion("Unit_Cost is not null");
            return (Criteria) this;
        }

        public Criteria andUnit_CostEqualTo(BigDecimal value) {
            addCriterion("Unit_Cost =", value, "unit_Cost");
            return (Criteria) this;
        }

        public Criteria andUnit_CostNotEqualTo(BigDecimal value) {
            addCriterion("Unit_Cost <>", value, "unit_Cost");
            return (Criteria) this;
        }

        public Criteria andUnit_CostGreaterThan(BigDecimal value) {
            addCriterion("Unit_Cost >", value, "unit_Cost");
            return (Criteria) this;
        }

        public Criteria andUnit_CostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Unit_Cost >=", value, "unit_Cost");
            return (Criteria) this;
        }

        public Criteria andUnit_CostLessThan(BigDecimal value) {
            addCriterion("Unit_Cost <", value, "unit_Cost");
            return (Criteria) this;
        }

        public Criteria andUnit_CostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Unit_Cost <=", value, "unit_Cost");
            return (Criteria) this;
        }

        public Criteria andUnit_CostIn(List<BigDecimal> values) {
            addCriterion("Unit_Cost in", values, "unit_Cost");
            return (Criteria) this;
        }

        public Criteria andUnit_CostNotIn(List<BigDecimal> values) {
            addCriterion("Unit_Cost not in", values, "unit_Cost");
            return (Criteria) this;
        }

        public Criteria andUnit_CostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Unit_Cost between", value1, value2, "unit_Cost");
            return (Criteria) this;
        }

        public Criteria andUnit_CostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Unit_Cost not between", value1, value2, "unit_Cost");
            return (Criteria) this;
        }

        public Criteria andSignatureIsNull() {
            addCriterion("Signature is null");
            return (Criteria) this;
        }

        public Criteria andSignatureIsNotNull() {
            addCriterion("Signature is not null");
            return (Criteria) this;
        }

        public Criteria andSignatureEqualTo(String value) {
            addCriterion("Signature =", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotEqualTo(String value) {
            addCriterion("Signature <>", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureGreaterThan(String value) {
            addCriterion("Signature >", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureGreaterThanOrEqualTo(String value) {
            addCriterion("Signature >=", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureLessThan(String value) {
            addCriterion("Signature <", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureLessThanOrEqualTo(String value) {
            addCriterion("Signature <=", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureLike(String value) {
            addCriterion("Signature like", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotLike(String value) {
            addCriterion("Signature not like", value, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureIn(List<String> values) {
            addCriterion("Signature in", values, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotIn(List<String> values) {
            addCriterion("Signature not in", values, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureBetween(String value1, String value2) {
            addCriterion("Signature between", value1, value2, "signature");
            return (Criteria) this;
        }

        public Criteria andSignatureNotBetween(String value1, String value2) {
            addCriterion("Signature not between", value1, value2, "signature");
            return (Criteria) this;
        }

        public Criteria andAgent_Unit_CostIsNull() {
            addCriterion("Agent_Unit_Cost is null");
            return (Criteria) this;
        }

        public Criteria andAgent_Unit_CostIsNotNull() {
            addCriterion("Agent_Unit_Cost is not null");
            return (Criteria) this;
        }

        public Criteria andAgent_Unit_CostEqualTo(BigDecimal value) {
            addCriterion("Agent_Unit_Cost =", value, "agent_Unit_Cost");
            return (Criteria) this;
        }

        public Criteria andAgent_Unit_CostNotEqualTo(BigDecimal value) {
            addCriterion("Agent_Unit_Cost <>", value, "agent_Unit_Cost");
            return (Criteria) this;
        }

        public Criteria andAgent_Unit_CostGreaterThan(BigDecimal value) {
            addCriterion("Agent_Unit_Cost >", value, "agent_Unit_Cost");
            return (Criteria) this;
        }

        public Criteria andAgent_Unit_CostGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Agent_Unit_Cost >=", value, "agent_Unit_Cost");
            return (Criteria) this;
        }

        public Criteria andAgent_Unit_CostLessThan(BigDecimal value) {
            addCriterion("Agent_Unit_Cost <", value, "agent_Unit_Cost");
            return (Criteria) this;
        }

        public Criteria andAgent_Unit_CostLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Agent_Unit_Cost <=", value, "agent_Unit_Cost");
            return (Criteria) this;
        }

        public Criteria andAgent_Unit_CostIn(List<BigDecimal> values) {
            addCriterion("Agent_Unit_Cost in", values, "agent_Unit_Cost");
            return (Criteria) this;
        }

        public Criteria andAgent_Unit_CostNotIn(List<BigDecimal> values) {
            addCriterion("Agent_Unit_Cost not in", values, "agent_Unit_Cost");
            return (Criteria) this;
        }

        public Criteria andAgent_Unit_CostBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Agent_Unit_Cost between", value1, value2, "agent_Unit_Cost");
            return (Criteria) this;
        }

        public Criteria andAgent_Unit_CostNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Agent_Unit_Cost not between", value1, value2, "agent_Unit_Cost");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_Unit_PriceIsNull() {
            addCriterion("Enterprise_User_Unit_Price is null");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_Unit_PriceIsNotNull() {
            addCriterion("Enterprise_User_Unit_Price is not null");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_Unit_PriceEqualTo(BigDecimal value) {
            addCriterion("Enterprise_User_Unit_Price =", value, "enterprise_User_Unit_Price");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_Unit_PriceNotEqualTo(BigDecimal value) {
            addCriterion("Enterprise_User_Unit_Price <>", value, "enterprise_User_Unit_Price");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_Unit_PriceGreaterThan(BigDecimal value) {
            addCriterion("Enterprise_User_Unit_Price >", value, "enterprise_User_Unit_Price");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_Unit_PriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Enterprise_User_Unit_Price >=", value, "enterprise_User_Unit_Price");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_Unit_PriceLessThan(BigDecimal value) {
            addCriterion("Enterprise_User_Unit_Price <", value, "enterprise_User_Unit_Price");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_Unit_PriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Enterprise_User_Unit_Price <=", value, "enterprise_User_Unit_Price");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_Unit_PriceIn(List<BigDecimal> values) {
            addCriterion("Enterprise_User_Unit_Price in", values, "enterprise_User_Unit_Price");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_Unit_PriceNotIn(List<BigDecimal> values) {
            addCriterion("Enterprise_User_Unit_Price not in", values, "enterprise_User_Unit_Price");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_Unit_PriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Enterprise_User_Unit_Price between", value1, value2, "enterprise_User_Unit_Price");
            return (Criteria) this;
        }

        public Criteria andEnterprise_User_Unit_PriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Enterprise_User_Unit_Price not between", value1, value2, "enterprise_User_Unit_Price");
            return (Criteria) this;
        }

        public Criteria andBusiness_User_IdIsNull() {
            addCriterion("Business_User_Id is null");
            return (Criteria) this;
        }

        public Criteria andBusiness_User_IdIsNotNull() {
            addCriterion("Business_User_Id is not null");
            return (Criteria) this;
        }

        public Criteria andBusiness_User_IdEqualTo(Integer value) {
            addCriterion("Business_User_Id =", value, "business_User_Id");
            return (Criteria) this;
        }

        public Criteria andBusiness_User_IdNotEqualTo(Integer value) {
            addCriterion("Business_User_Id <>", value, "business_User_Id");
            return (Criteria) this;
        }

        public Criteria andBusiness_User_IdGreaterThan(Integer value) {
            addCriterion("Business_User_Id >", value, "business_User_Id");
            return (Criteria) this;
        }

        public Criteria andBusiness_User_IdGreaterThanOrEqualTo(Integer value) {
            addCriterion("Business_User_Id >=", value, "business_User_Id");
            return (Criteria) this;
        }

        public Criteria andBusiness_User_IdLessThan(Integer value) {
            addCriterion("Business_User_Id <", value, "business_User_Id");
            return (Criteria) this;
        }

        public Criteria andBusiness_User_IdLessThanOrEqualTo(Integer value) {
            addCriterion("Business_User_Id <=", value, "business_User_Id");
            return (Criteria) this;
        }

        public Criteria andBusiness_User_IdIn(List<Integer> values) {
            addCriterion("Business_User_Id in", values, "business_User_Id");
            return (Criteria) this;
        }

        public Criteria andBusiness_User_IdNotIn(List<Integer> values) {
            addCriterion("Business_User_Id not in", values, "business_User_Id");
            return (Criteria) this;
        }

        public Criteria andBusiness_User_IdBetween(Integer value1, Integer value2) {
            addCriterion("Business_User_Id between", value1, value2, "business_User_Id");
            return (Criteria) this;
        }

        public Criteria andBusiness_User_IdNotBetween(Integer value1, Integer value2) {
            addCriterion("Business_User_Id not between", value1, value2, "business_User_Id");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalIsNull() {
            addCriterion("Submit_Total is null");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalIsNotNull() {
            addCriterion("Submit_Total is not null");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalEqualTo(Integer value) {
            addCriterion("Submit_Total =", value, "submit_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalNotEqualTo(Integer value) {
            addCriterion("Submit_Total <>", value, "submit_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalGreaterThan(Integer value) {
            addCriterion("Submit_Total >", value, "submit_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("Submit_Total >=", value, "submit_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalLessThan(Integer value) {
            addCriterion("Submit_Total <", value, "submit_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalLessThanOrEqualTo(Integer value) {
            addCriterion("Submit_Total <=", value, "submit_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalIn(List<Integer> values) {
            addCriterion("Submit_Total in", values, "submit_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalNotIn(List<Integer> values) {
            addCriterion("Submit_Total not in", values, "submit_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalBetween(Integer value1, Integer value2) {
            addCriterion("Submit_Total between", value1, value2, "submit_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_TotalNotBetween(Integer value1, Integer value2) {
            addCriterion("Submit_Total not between", value1, value2, "submit_Total");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalIsNull() {
            addCriterion("Sort_Faild_Total is null");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalIsNotNull() {
            addCriterion("Sort_Faild_Total is not null");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalEqualTo(Integer value) {
            addCriterion("Sort_Faild_Total =", value, "sort_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalNotEqualTo(Integer value) {
            addCriterion("Sort_Faild_Total <>", value, "sort_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalGreaterThan(Integer value) {
            addCriterion("Sort_Faild_Total >", value, "sort_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("Sort_Faild_Total >=", value, "sort_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalLessThan(Integer value) {
            addCriterion("Sort_Faild_Total <", value, "sort_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalLessThanOrEqualTo(Integer value) {
            addCriterion("Sort_Faild_Total <=", value, "sort_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalIn(List<Integer> values) {
            addCriterion("Sort_Faild_Total in", values, "sort_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalNotIn(List<Integer> values) {
            addCriterion("Sort_Faild_Total not in", values, "sort_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalBetween(Integer value1, Integer value2) {
            addCriterion("Sort_Faild_Total between", value1, value2, "sort_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSort_Faild_TotalNotBetween(Integer value1, Integer value2) {
            addCriterion("Sort_Faild_Total not between", value1, value2, "sort_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalIsNull() {
            addCriterion("Submit_Success_Total is null");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalIsNotNull() {
            addCriterion("Submit_Success_Total is not null");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalEqualTo(Integer value) {
            addCriterion("Submit_Success_Total =", value, "submit_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalNotEqualTo(Integer value) {
            addCriterion("Submit_Success_Total <>", value, "submit_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalGreaterThan(Integer value) {
            addCriterion("Submit_Success_Total >", value, "submit_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("Submit_Success_Total >=", value, "submit_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalLessThan(Integer value) {
            addCriterion("Submit_Success_Total <", value, "submit_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalLessThanOrEqualTo(Integer value) {
            addCriterion("Submit_Success_Total <=", value, "submit_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalIn(List<Integer> values) {
            addCriterion("Submit_Success_Total in", values, "submit_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalNotIn(List<Integer> values) {
            addCriterion("Submit_Success_Total not in", values, "submit_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalBetween(Integer value1, Integer value2) {
            addCriterion("Submit_Success_Total between", value1, value2, "submit_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Success_TotalNotBetween(Integer value1, Integer value2) {
            addCriterion("Submit_Success_Total not between", value1, value2, "submit_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalIsNull() {
            addCriterion("Submit_Faild_Total is null");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalIsNotNull() {
            addCriterion("Submit_Faild_Total is not null");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalEqualTo(Integer value) {
            addCriterion("Submit_Faild_Total =", value, "submit_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalNotEqualTo(Integer value) {
            addCriterion("Submit_Faild_Total <>", value, "submit_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalGreaterThan(Integer value) {
            addCriterion("Submit_Faild_Total >", value, "submit_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("Submit_Faild_Total >=", value, "submit_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalLessThan(Integer value) {
            addCriterion("Submit_Faild_Total <", value, "submit_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalLessThanOrEqualTo(Integer value) {
            addCriterion("Submit_Faild_Total <=", value, "submit_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalIn(List<Integer> values) {
            addCriterion("Submit_Faild_Total in", values, "submit_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalNotIn(List<Integer> values) {
            addCriterion("Submit_Faild_Total not in", values, "submit_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalBetween(Integer value1, Integer value2) {
            addCriterion("Submit_Faild_Total between", value1, value2, "submit_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSubmit_Faild_TotalNotBetween(Integer value1, Integer value2) {
            addCriterion("Submit_Faild_Total not between", value1, value2, "submit_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalIsNull() {
            addCriterion("Send_Success_Total is null");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalIsNotNull() {
            addCriterion("Send_Success_Total is not null");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalEqualTo(Integer value) {
            addCriterion("Send_Success_Total =", value, "send_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalNotEqualTo(Integer value) {
            addCriterion("Send_Success_Total <>", value, "send_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalGreaterThan(Integer value) {
            addCriterion("Send_Success_Total >", value, "send_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("Send_Success_Total >=", value, "send_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalLessThan(Integer value) {
            addCriterion("Send_Success_Total <", value, "send_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalLessThanOrEqualTo(Integer value) {
            addCriterion("Send_Success_Total <=", value, "send_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalIn(List<Integer> values) {
            addCriterion("Send_Success_Total in", values, "send_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalNotIn(List<Integer> values) {
            addCriterion("Send_Success_Total not in", values, "send_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalBetween(Integer value1, Integer value2) {
            addCriterion("Send_Success_Total between", value1, value2, "send_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Success_TotalNotBetween(Integer value1, Integer value2) {
            addCriterion("Send_Success_Total not between", value1, value2, "send_Success_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalIsNull() {
            addCriterion("Send_Faild_Total is null");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalIsNotNull() {
            addCriterion("Send_Faild_Total is not null");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalEqualTo(Integer value) {
            addCriterion("Send_Faild_Total =", value, "send_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalNotEqualTo(Integer value) {
            addCriterion("Send_Faild_Total <>", value, "send_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalGreaterThan(Integer value) {
            addCriterion("Send_Faild_Total >", value, "send_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("Send_Faild_Total >=", value, "send_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalLessThan(Integer value) {
            addCriterion("Send_Faild_Total <", value, "send_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalLessThanOrEqualTo(Integer value) {
            addCriterion("Send_Faild_Total <=", value, "send_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalIn(List<Integer> values) {
            addCriterion("Send_Faild_Total in", values, "send_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalNotIn(List<Integer> values) {
            addCriterion("Send_Faild_Total not in", values, "send_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalBetween(Integer value1, Integer value2) {
            addCriterion("Send_Faild_Total between", value1, value2, "send_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Faild_TotalNotBetween(Integer value1, Integer value2) {
            addCriterion("Send_Faild_Total not between", value1, value2, "send_Faild_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalIsNull() {
            addCriterion("Send_Unknown_Total is null");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalIsNotNull() {
            addCriterion("Send_Unknown_Total is not null");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalEqualTo(Integer value) {
            addCriterion("Send_Unknown_Total =", value, "send_Unknown_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalNotEqualTo(Integer value) {
            addCriterion("Send_Unknown_Total <>", value, "send_Unknown_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalGreaterThan(Integer value) {
            addCriterion("Send_Unknown_Total >", value, "send_Unknown_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalGreaterThanOrEqualTo(Integer value) {
            addCriterion("Send_Unknown_Total >=", value, "send_Unknown_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalLessThan(Integer value) {
            addCriterion("Send_Unknown_Total <", value, "send_Unknown_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalLessThanOrEqualTo(Integer value) {
            addCriterion("Send_Unknown_Total <=", value, "send_Unknown_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalIn(List<Integer> values) {
            addCriterion("Send_Unknown_Total in", values, "send_Unknown_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalNotIn(List<Integer> values) {
            addCriterion("Send_Unknown_Total not in", values, "send_Unknown_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalBetween(Integer value1, Integer value2) {
            addCriterion("Send_Unknown_Total between", value1, value2, "send_Unknown_Total");
            return (Criteria) this;
        }

        public Criteria andSend_Unknown_TotalNotBetween(Integer value1, Integer value2) {
            addCriterion("Send_Unknown_Total not between", value1, value2, "send_Unknown_Total");
            return (Criteria) this;
        }

        public Criteria andSuccess_RateIsNull() {
            addCriterion("Success_Rate is null");
            return (Criteria) this;
        }

        public Criteria andSuccess_RateIsNotNull() {
            addCriterion("Success_Rate is not null");
            return (Criteria) this;
        }

        public Criteria andSuccess_RateEqualTo(BigDecimal value) {
            addCriterion("Success_Rate =", value, "success_Rate");
            return (Criteria) this;
        }

        public Criteria andSuccess_RateNotEqualTo(BigDecimal value) {
            addCriterion("Success_Rate <>", value, "success_Rate");
            return (Criteria) this;
        }

        public Criteria andSuccess_RateGreaterThan(BigDecimal value) {
            addCriterion("Success_Rate >", value, "success_Rate");
            return (Criteria) this;
        }

        public Criteria andSuccess_RateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Success_Rate >=", value, "success_Rate");
            return (Criteria) this;
        }

        public Criteria andSuccess_RateLessThan(BigDecimal value) {
            addCriterion("Success_Rate <", value, "success_Rate");
            return (Criteria) this;
        }

        public Criteria andSuccess_RateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Success_Rate <=", value, "success_Rate");
            return (Criteria) this;
        }

        public Criteria andSuccess_RateIn(List<BigDecimal> values) {
            addCriterion("Success_Rate in", values, "success_Rate");
            return (Criteria) this;
        }

        public Criteria andSuccess_RateNotIn(List<BigDecimal> values) {
            addCriterion("Success_Rate not in", values, "success_Rate");
            return (Criteria) this;
        }

        public Criteria andSuccess_RateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Success_Rate between", value1, value2, "success_Rate");
            return (Criteria) this;
        }

        public Criteria andSuccess_RateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Success_Rate not between", value1, value2, "success_Rate");
            return (Criteria) this;
        }

        public Criteria andFailure_RateIsNull() {
            addCriterion("Failure_Rate is null");
            return (Criteria) this;
        }

        public Criteria andFailure_RateIsNotNull() {
            addCriterion("Failure_Rate is not null");
            return (Criteria) this;
        }

        public Criteria andFailure_RateEqualTo(BigDecimal value) {
            addCriterion("Failure_Rate =", value, "failure_Rate");
            return (Criteria) this;
        }

        public Criteria andFailure_RateNotEqualTo(BigDecimal value) {
            addCriterion("Failure_Rate <>", value, "failure_Rate");
            return (Criteria) this;
        }

        public Criteria andFailure_RateGreaterThan(BigDecimal value) {
            addCriterion("Failure_Rate >", value, "failure_Rate");
            return (Criteria) this;
        }

        public Criteria andFailure_RateGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("Failure_Rate >=", value, "failure_Rate");
            return (Criteria) this;
        }

        public Criteria andFailure_RateLessThan(BigDecimal value) {
            addCriterion("Failure_Rate <", value, "failure_Rate");
            return (Criteria) this;
        }

        public Criteria andFailure_RateLessThanOrEqualTo(BigDecimal value) {
            addCriterion("Failure_Rate <=", value, "failure_Rate");
            return (Criteria) this;
        }

        public Criteria andFailure_RateIn(List<BigDecimal> values) {
            addCriterion("Failure_Rate in", values, "failure_Rate");
            return (Criteria) this;
        }

        public Criteria andFailure_RateNotIn(List<BigDecimal> values) {
            addCriterion("Failure_Rate not in", values, "failure_Rate");
            return (Criteria) this;
        }

        public Criteria andFailure_RateBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Failure_Rate between", value1, value2, "failure_Rate");
            return (Criteria) this;
        }

        public Criteria andFailure_RateNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("Failure_Rate not between", value1, value2, "failure_Rate");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateIsNull() {
            addCriterion("Statistics_Date is null");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateIsNotNull() {
            addCriterion("Statistics_Date is not null");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateEqualTo(Date value) {
            addCriterionForJDBCDate("Statistics_Date =", value, "statistics_Date");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateNotEqualTo(Date value) {
            addCriterionForJDBCDate("Statistics_Date <>", value, "statistics_Date");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateGreaterThan(Date value) {
            addCriterionForJDBCDate("Statistics_Date >", value, "statistics_Date");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("Statistics_Date >=", value, "statistics_Date");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateLessThan(Date value) {
            addCriterionForJDBCDate("Statistics_Date <", value, "statistics_Date");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("Statistics_Date <=", value, "statistics_Date");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateIn(List<Date> values) {
            addCriterionForJDBCDate("Statistics_Date in", values, "statistics_Date");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateNotIn(List<Date> values) {
            addCriterionForJDBCDate("Statistics_Date not in", values, "statistics_Date");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("Statistics_Date between", value1, value2, "statistics_Date");
            return (Criteria) this;
        }

        public Criteria andStatistics_DateNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("Statistics_Date not between", value1, value2, "statistics_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateIsNull() {
            addCriterion("Create_Date is null");
            return (Criteria) this;
        }

        public Criteria andCreate_DateIsNotNull() {
            addCriterion("Create_Date is not null");
            return (Criteria) this;
        }

        public Criteria andCreate_DateEqualTo(Date value) {
            addCriterion("Create_Date =", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateNotEqualTo(Date value) {
            addCriterion("Create_Date <>", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateGreaterThan(Date value) {
            addCriterion("Create_Date >", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateGreaterThanOrEqualTo(Date value) {
            addCriterion("Create_Date >=", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateLessThan(Date value) {
            addCriterion("Create_Date <", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateLessThanOrEqualTo(Date value) {
            addCriterion("Create_Date <=", value, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateIn(List<Date> values) {
            addCriterion("Create_Date in", values, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateNotIn(List<Date> values) {
            addCriterion("Create_Date not in", values, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateBetween(Date value1, Date value2) {
            addCriterion("Create_Date between", value1, value2, "create_Date");
            return (Criteria) this;
        }

        public Criteria andCreate_DateNotBetween(Date value1, Date value2) {
            addCriterion("Create_Date not between", value1, value2, "create_Date");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sms_statistics
     *
     * @mbg.generated do_not_delete_during_merge Fri Jun 19 11:46:42 CST 2020
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}