package com.hero.wireless.web.entity.business;

import com.hero.wireless.web.entity.base.BaseEntity;

import java.math.BigDecimal;
import java.util.Date;

public class SmsStatistics extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Id
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Channel_No
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private String channel_No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Enterprise_No
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private String enterprise_No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Enterprise_User_Id
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private Integer enterprise_User_Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Country_Number
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private String country_Number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Operator
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Agent_No
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private String agent_No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Province_Code
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private String province_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Message_Type_Code
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private String message_Type_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Profits
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private BigDecimal profits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Agent_Profits
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private BigDecimal agent_Profits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Enterprise_User_Taxes
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private BigDecimal enterprise_User_Taxes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Channel_Taxes
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private BigDecimal channel_Taxes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Unit_Cost
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private BigDecimal unit_Cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Signature
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Agent_Unit_Cost
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private BigDecimal agent_Unit_Cost;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Enterprise_User_Unit_Price
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private BigDecimal enterprise_User_Unit_Price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Business_User_Id
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private Integer business_User_Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Submit_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private Integer submit_Total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Sort_Faild_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private Integer sort_Faild_Total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Submit_Success_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private Integer submit_Success_Total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Submit_Faild_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private Integer submit_Faild_Total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Send_Success_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private Integer send_Success_Total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Send_Faild_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private Integer send_Faild_Total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Send_Unknown_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private Integer send_Unknown_Total;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Success_Rate
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private BigDecimal success_Rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Failure_Rate
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private BigDecimal failure_Rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Statistics_Date
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private Date statistics_Date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_statistics.Create_Date
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    private Date create_Date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Id
     *
     * @return the value of sms_statistics.Id
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Id
     *
     * @param id the value for sms_statistics.Id
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Channel_No
     *
     * @return the value of sms_statistics.Channel_No
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public String getChannel_No() {
        return channel_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Channel_No
     *
     * @param channel_No the value for sms_statistics.Channel_No
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setChannel_No(String channel_No) {
        this.channel_No = channel_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Enterprise_No
     *
     * @return the value of sms_statistics.Enterprise_No
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public String getEnterprise_No() {
        return enterprise_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Enterprise_No
     *
     * @param enterprise_No the value for sms_statistics.Enterprise_No
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setEnterprise_No(String enterprise_No) {
        this.enterprise_No = enterprise_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Enterprise_User_Id
     *
     * @return the value of sms_statistics.Enterprise_User_Id
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public Integer getEnterprise_User_Id() {
        return enterprise_User_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Enterprise_User_Id
     *
     * @param enterprise_User_Id the value for sms_statistics.Enterprise_User_Id
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setEnterprise_User_Id(Integer enterprise_User_Id) {
        this.enterprise_User_Id = enterprise_User_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Country_Number
     *
     * @return the value of sms_statistics.Country_Number
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public String getCountry_Number() {
        return country_Number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Country_Number
     *
     * @param country_Number the value for sms_statistics.Country_Number
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setCountry_Number(String country_Number) {
        this.country_Number = country_Number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Operator
     *
     * @return the value of sms_statistics.Operator
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Operator
     *
     * @param operator the value for sms_statistics.Operator
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Agent_No
     *
     * @return the value of sms_statistics.Agent_No
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public String getAgent_No() {
        return agent_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Agent_No
     *
     * @param agent_No the value for sms_statistics.Agent_No
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setAgent_No(String agent_No) {
        this.agent_No = agent_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Province_Code
     *
     * @return the value of sms_statistics.Province_Code
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public String getProvince_Code() {
        return province_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Province_Code
     *
     * @param province_Code the value for sms_statistics.Province_Code
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setProvince_Code(String province_Code) {
        this.province_Code = province_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Message_Type_Code
     *
     * @return the value of sms_statistics.Message_Type_Code
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public String getMessage_Type_Code() {
        return message_Type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Message_Type_Code
     *
     * @param message_Type_Code the value for sms_statistics.Message_Type_Code
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setMessage_Type_Code(String message_Type_Code) {
        this.message_Type_Code = message_Type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Profits
     *
     * @return the value of sms_statistics.Profits
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public BigDecimal getProfits() {
        return profits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Profits
     *
     * @param profits the value for sms_statistics.Profits
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setProfits(BigDecimal profits) {
        this.profits = profits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Agent_Profits
     *
     * @return the value of sms_statistics.Agent_Profits
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public BigDecimal getAgent_Profits() {
        return agent_Profits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Agent_Profits
     *
     * @param agent_Profits the value for sms_statistics.Agent_Profits
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setAgent_Profits(BigDecimal agent_Profits) {
        this.agent_Profits = agent_Profits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Enterprise_User_Taxes
     *
     * @return the value of sms_statistics.Enterprise_User_Taxes
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public BigDecimal getEnterprise_User_Taxes() {
        return enterprise_User_Taxes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Enterprise_User_Taxes
     *
     * @param enterprise_User_Taxes the value for sms_statistics.Enterprise_User_Taxes
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setEnterprise_User_Taxes(BigDecimal enterprise_User_Taxes) {
        this.enterprise_User_Taxes = enterprise_User_Taxes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Channel_Taxes
     *
     * @return the value of sms_statistics.Channel_Taxes
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public BigDecimal getChannel_Taxes() {
        return channel_Taxes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Channel_Taxes
     *
     * @param channel_Taxes the value for sms_statistics.Channel_Taxes
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setChannel_Taxes(BigDecimal channel_Taxes) {
        this.channel_Taxes = channel_Taxes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Unit_Cost
     *
     * @return the value of sms_statistics.Unit_Cost
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public BigDecimal getUnit_Cost() {
        return unit_Cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Unit_Cost
     *
     * @param unit_Cost the value for sms_statistics.Unit_Cost
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setUnit_Cost(BigDecimal unit_Cost) {
        this.unit_Cost = unit_Cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Signature
     *
     * @return the value of sms_statistics.Signature
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Signature
     *
     * @param signature the value for sms_statistics.Signature
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Agent_Unit_Cost
     *
     * @return the value of sms_statistics.Agent_Unit_Cost
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public BigDecimal getAgent_Unit_Cost() {
        return agent_Unit_Cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Agent_Unit_Cost
     *
     * @param agent_Unit_Cost the value for sms_statistics.Agent_Unit_Cost
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setAgent_Unit_Cost(BigDecimal agent_Unit_Cost) {
        this.agent_Unit_Cost = agent_Unit_Cost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Enterprise_User_Unit_Price
     *
     * @return the value of sms_statistics.Enterprise_User_Unit_Price
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public BigDecimal getEnterprise_User_Unit_Price() {
        return enterprise_User_Unit_Price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Enterprise_User_Unit_Price
     *
     * @param enterprise_User_Unit_Price the value for sms_statistics.Enterprise_User_Unit_Price
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setEnterprise_User_Unit_Price(BigDecimal enterprise_User_Unit_Price) {
        this.enterprise_User_Unit_Price = enterprise_User_Unit_Price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Business_User_Id
     *
     * @return the value of sms_statistics.Business_User_Id
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public Integer getBusiness_User_Id() {
        return business_User_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Business_User_Id
     *
     * @param business_User_Id the value for sms_statistics.Business_User_Id
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setBusiness_User_Id(Integer business_User_Id) {
        this.business_User_Id = business_User_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Submit_Total
     *
     * @return the value of sms_statistics.Submit_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public Integer getSubmit_Total() {
        return submit_Total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Submit_Total
     *
     * @param submit_Total the value for sms_statistics.Submit_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setSubmit_Total(Integer submit_Total) {
        this.submit_Total = submit_Total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Sort_Faild_Total
     *
     * @return the value of sms_statistics.Sort_Faild_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public Integer getSort_Faild_Total() {
        return sort_Faild_Total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Sort_Faild_Total
     *
     * @param sort_Faild_Total the value for sms_statistics.Sort_Faild_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setSort_Faild_Total(Integer sort_Faild_Total) {
        this.sort_Faild_Total = sort_Faild_Total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Submit_Success_Total
     *
     * @return the value of sms_statistics.Submit_Success_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public Integer getSubmit_Success_Total() {
        return submit_Success_Total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Submit_Success_Total
     *
     * @param submit_Success_Total the value for sms_statistics.Submit_Success_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setSubmit_Success_Total(Integer submit_Success_Total) {
        this.submit_Success_Total = submit_Success_Total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Submit_Faild_Total
     *
     * @return the value of sms_statistics.Submit_Faild_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public Integer getSubmit_Faild_Total() {
        return submit_Faild_Total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Submit_Faild_Total
     *
     * @param submit_Faild_Total the value for sms_statistics.Submit_Faild_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setSubmit_Faild_Total(Integer submit_Faild_Total) {
        this.submit_Faild_Total = submit_Faild_Total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Send_Success_Total
     *
     * @return the value of sms_statistics.Send_Success_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public Integer getSend_Success_Total() {
        return send_Success_Total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Send_Success_Total
     *
     * @param send_Success_Total the value for sms_statistics.Send_Success_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setSend_Success_Total(Integer send_Success_Total) {
        this.send_Success_Total = send_Success_Total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Send_Faild_Total
     *
     * @return the value of sms_statistics.Send_Faild_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public Integer getSend_Faild_Total() {
        return send_Faild_Total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Send_Faild_Total
     *
     * @param send_Faild_Total the value for sms_statistics.Send_Faild_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setSend_Faild_Total(Integer send_Faild_Total) {
        this.send_Faild_Total = send_Faild_Total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Send_Unknown_Total
     *
     * @return the value of sms_statistics.Send_Unknown_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public Integer getSend_Unknown_Total() {
        return send_Unknown_Total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Send_Unknown_Total
     *
     * @param send_Unknown_Total the value for sms_statistics.Send_Unknown_Total
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setSend_Unknown_Total(Integer send_Unknown_Total) {
        this.send_Unknown_Total = send_Unknown_Total;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Success_Rate
     *
     * @return the value of sms_statistics.Success_Rate
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public BigDecimal getSuccess_Rate() {
        return success_Rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Success_Rate
     *
     * @param success_Rate the value for sms_statistics.Success_Rate
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setSuccess_Rate(BigDecimal success_Rate) {
        this.success_Rate = success_Rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Failure_Rate
     *
     * @return the value of sms_statistics.Failure_Rate
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public BigDecimal getFailure_Rate() {
        return failure_Rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Failure_Rate
     *
     * @param failure_Rate the value for sms_statistics.Failure_Rate
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setFailure_Rate(BigDecimal failure_Rate) {
        this.failure_Rate = failure_Rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Statistics_Date
     *
     * @return the value of sms_statistics.Statistics_Date
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public Date getStatistics_Date() {
        return statistics_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Statistics_Date
     *
     * @param statistics_Date the value for sms_statistics.Statistics_Date
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setStatistics_Date(Date statistics_Date) {
        this.statistics_Date = statistics_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_statistics.Create_Date
     *
     * @return the value of sms_statistics.Create_Date
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public Date getCreate_Date() {
        return create_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_statistics.Create_Date
     *
     * @param create_Date the value for sms_statistics.Create_Date
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    public void setCreate_Date(Date create_Date) {
        this.create_Date = create_Date;
    }
}