package com.hero.wireless.web.entity.send;

import com.hero.wireless.web.entity.base.BaseEntity;
import java.math.BigDecimal;
import java.util.Date;

public class SubmitAwait extends BaseEntity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Id
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Channel_No
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String channel_No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Enterprise_No
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String enterprise_No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Agent_No
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String agent_No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Business_User_Id
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private Integer business_User_Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Enterprise_User_Id
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private Integer enterprise_User_Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Product_No
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String product_No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Product_Channel_Id
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private Integer product_Channel_Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Priority_Level
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private Integer priority_Level;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Group_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String group_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Input_Sub_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String input_Sub_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Msg_Batch_No
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String msg_Batch_No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Enterprise_Msg_Id
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String enterprise_Msg_Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Channel_Msg_Id
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String channel_Msg_Id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.SP_Number
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String SP_Number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Sequence
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private Integer sequence;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Sub_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String sub_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Is_LMS
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private Boolean is_LMS;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Is_Deduct
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private Boolean is_Deduct;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Data_Status_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String data_Status_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Is_Show
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private Boolean is_Show;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Message_Type_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String message_Type_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Operator
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String operator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Content
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String content;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Charset
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String charset;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Signature
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String signature;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Content_Length
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private Integer content_Length;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Country_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String country_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Country_Number
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String country_Number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.MCC
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String MCC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.MNC
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String MNC;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Province_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String province_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Area_Name
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String area_Name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Phone_No
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String phone_No;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Protocol_Type_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String protocol_Type_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Submit_Status_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String submit_Status_Code;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Submit_Description
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String submit_Description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Submit_Date
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private Date submit_Date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Submit_Response_Date
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private Date submit_Response_Date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Sender_Local_IP
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String sender_Local_IP;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Sender_Local_Port
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String sender_Local_Port;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Gate_Ip
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String gate_Ip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Enterprise_User_Taxes
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private BigDecimal enterprise_User_Taxes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Channel_Taxes
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private BigDecimal channel_Taxes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Channel_Unit_Price
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private BigDecimal channel_Unit_Price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Agent_Unit_Price
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private BigDecimal agent_Unit_Price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Agent_Taxes
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private BigDecimal agent_Taxes;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Enterprise_User_Unit_Price
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private BigDecimal enterprise_User_Unit_Price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Agent_Profits
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private BigDecimal agent_Profits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Profits
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private BigDecimal profits;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Input_Log_Date
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private Date input_Log_Date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Description
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Remark
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private String remark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column submit_await.Create_Date
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    private Date create_Date;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Id
     *
     * @return the value of submit_await.Id
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Id
     *
     * @param id the value for submit_await.Id
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Channel_No
     *
     * @return the value of submit_await.Channel_No
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getChannel_No() {
        return channel_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Channel_No
     *
     * @param channel_No the value for submit_await.Channel_No
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setChannel_No(String channel_No) {
        this.channel_No = channel_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Enterprise_No
     *
     * @return the value of submit_await.Enterprise_No
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getEnterprise_No() {
        return enterprise_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Enterprise_No
     *
     * @param enterprise_No the value for submit_await.Enterprise_No
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setEnterprise_No(String enterprise_No) {
        this.enterprise_No = enterprise_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Agent_No
     *
     * @return the value of submit_await.Agent_No
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getAgent_No() {
        return agent_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Agent_No
     *
     * @param agent_No the value for submit_await.Agent_No
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setAgent_No(String agent_No) {
        this.agent_No = agent_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Business_User_Id
     *
     * @return the value of submit_await.Business_User_Id
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public Integer getBusiness_User_Id() {
        return business_User_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Business_User_Id
     *
     * @param business_User_Id the value for submit_await.Business_User_Id
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setBusiness_User_Id(Integer business_User_Id) {
        this.business_User_Id = business_User_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Enterprise_User_Id
     *
     * @return the value of submit_await.Enterprise_User_Id
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public Integer getEnterprise_User_Id() {
        return enterprise_User_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Enterprise_User_Id
     *
     * @param enterprise_User_Id the value for submit_await.Enterprise_User_Id
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setEnterprise_User_Id(Integer enterprise_User_Id) {
        this.enterprise_User_Id = enterprise_User_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Product_No
     *
     * @return the value of submit_await.Product_No
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getProduct_No() {
        return product_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Product_No
     *
     * @param product_No the value for submit_await.Product_No
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setProduct_No(String product_No) {
        this.product_No = product_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Product_Channel_Id
     *
     * @return the value of submit_await.Product_Channel_Id
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public Integer getProduct_Channel_Id() {
        return product_Channel_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Product_Channel_Id
     *
     * @param product_Channel_Id the value for submit_await.Product_Channel_Id
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setProduct_Channel_Id(Integer product_Channel_Id) {
        this.product_Channel_Id = product_Channel_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Priority_Level
     *
     * @return the value of submit_await.Priority_Level
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public Integer getPriority_Level() {
        return priority_Level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Priority_Level
     *
     * @param priority_Level the value for submit_await.Priority_Level
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setPriority_Level(Integer priority_Level) {
        this.priority_Level = priority_Level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Group_Code
     *
     * @return the value of submit_await.Group_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getGroup_Code() {
        return group_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Group_Code
     *
     * @param group_Code the value for submit_await.Group_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setGroup_Code(String group_Code) {
        this.group_Code = group_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Input_Sub_Code
     *
     * @return the value of submit_await.Input_Sub_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getInput_Sub_Code() {
        return input_Sub_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Input_Sub_Code
     *
     * @param input_Sub_Code the value for submit_await.Input_Sub_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setInput_Sub_Code(String input_Sub_Code) {
        this.input_Sub_Code = input_Sub_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Msg_Batch_No
     *
     * @return the value of submit_await.Msg_Batch_No
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getMsg_Batch_No() {
        return msg_Batch_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Msg_Batch_No
     *
     * @param msg_Batch_No the value for submit_await.Msg_Batch_No
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setMsg_Batch_No(String msg_Batch_No) {
        this.msg_Batch_No = msg_Batch_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Enterprise_Msg_Id
     *
     * @return the value of submit_await.Enterprise_Msg_Id
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getEnterprise_Msg_Id() {
        return enterprise_Msg_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Enterprise_Msg_Id
     *
     * @param enterprise_Msg_Id the value for submit_await.Enterprise_Msg_Id
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setEnterprise_Msg_Id(String enterprise_Msg_Id) {
        this.enterprise_Msg_Id = enterprise_Msg_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Channel_Msg_Id
     *
     * @return the value of submit_await.Channel_Msg_Id
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getChannel_Msg_Id() {
        return channel_Msg_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Channel_Msg_Id
     *
     * @param channel_Msg_Id the value for submit_await.Channel_Msg_Id
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setChannel_Msg_Id(String channel_Msg_Id) {
        this.channel_Msg_Id = channel_Msg_Id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.SP_Number
     *
     * @return the value of submit_await.SP_Number
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getSP_Number() {
        return SP_Number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.SP_Number
     *
     * @param SP_Number the value for submit_await.SP_Number
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setSP_Number(String SP_Number) {
        this.SP_Number = SP_Number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Sequence
     *
     * @return the value of submit_await.Sequence
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public Integer getSequence() {
        return sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Sequence
     *
     * @param sequence the value for submit_await.Sequence
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Sub_Code
     *
     * @return the value of submit_await.Sub_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getSub_Code() {
        return sub_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Sub_Code
     *
     * @param sub_Code the value for submit_await.Sub_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setSub_Code(String sub_Code) {
        this.sub_Code = sub_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Is_LMS
     *
     * @return the value of submit_await.Is_LMS
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public Boolean getIs_LMS() {
        return is_LMS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Is_LMS
     *
     * @param is_LMS the value for submit_await.Is_LMS
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setIs_LMS(Boolean is_LMS) {
        this.is_LMS = is_LMS;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Is_Deduct
     *
     * @return the value of submit_await.Is_Deduct
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public Boolean getIs_Deduct() {
        return is_Deduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Is_Deduct
     *
     * @param is_Deduct the value for submit_await.Is_Deduct
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setIs_Deduct(Boolean is_Deduct) {
        this.is_Deduct = is_Deduct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Data_Status_Code
     *
     * @return the value of submit_await.Data_Status_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getData_Status_Code() {
        return data_Status_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Data_Status_Code
     *
     * @param data_Status_Code the value for submit_await.Data_Status_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setData_Status_Code(String data_Status_Code) {
        this.data_Status_Code = data_Status_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Is_Show
     *
     * @return the value of submit_await.Is_Show
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public Boolean getIs_Show() {
        return is_Show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Is_Show
     *
     * @param is_Show the value for submit_await.Is_Show
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setIs_Show(Boolean is_Show) {
        this.is_Show = is_Show;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Message_Type_Code
     *
     * @return the value of submit_await.Message_Type_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getMessage_Type_Code() {
        return message_Type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Message_Type_Code
     *
     * @param message_Type_Code the value for submit_await.Message_Type_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setMessage_Type_Code(String message_Type_Code) {
        this.message_Type_Code = message_Type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Operator
     *
     * @return the value of submit_await.Operator
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Operator
     *
     * @param operator the value for submit_await.Operator
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setOperator(String operator) {
        this.operator = operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Content
     *
     * @return the value of submit_await.Content
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getContent() {
        return content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Content
     *
     * @param content the value for submit_await.Content
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setContent(String content) {
        this.content = content;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Charset
     *
     * @return the value of submit_await.Charset
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getCharset() {
        return charset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Charset
     *
     * @param charset the value for submit_await.Charset
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setCharset(String charset) {
        this.charset = charset;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Signature
     *
     * @return the value of submit_await.Signature
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getSignature() {
        return signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Signature
     *
     * @param signature the value for submit_await.Signature
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setSignature(String signature) {
        this.signature = signature;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Content_Length
     *
     * @return the value of submit_await.Content_Length
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public Integer getContent_Length() {
        return content_Length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Content_Length
     *
     * @param content_Length the value for submit_await.Content_Length
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setContent_Length(Integer content_Length) {
        this.content_Length = content_Length;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Country_Code
     *
     * @return the value of submit_await.Country_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getCountry_Code() {
        return country_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Country_Code
     *
     * @param country_Code the value for submit_await.Country_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setCountry_Code(String country_Code) {
        this.country_Code = country_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Country_Number
     *
     * @return the value of submit_await.Country_Number
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getCountry_Number() {
        return country_Number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Country_Number
     *
     * @param country_Number the value for submit_await.Country_Number
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setCountry_Number(String country_Number) {
        this.country_Number = country_Number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.MCC
     *
     * @return the value of submit_await.MCC
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getMCC() {
        return MCC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.MCC
     *
     * @param MCC the value for submit_await.MCC
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setMCC(String MCC) {
        this.MCC = MCC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.MNC
     *
     * @return the value of submit_await.MNC
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getMNC() {
        return MNC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.MNC
     *
     * @param MNC the value for submit_await.MNC
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setMNC(String MNC) {
        this.MNC = MNC;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Province_Code
     *
     * @return the value of submit_await.Province_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getProvince_Code() {
        return province_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Province_Code
     *
     * @param province_Code the value for submit_await.Province_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setProvince_Code(String province_Code) {
        this.province_Code = province_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Area_Name
     *
     * @return the value of submit_await.Area_Name
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getArea_Name() {
        return area_Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Area_Name
     *
     * @param area_Name the value for submit_await.Area_Name
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setArea_Name(String area_Name) {
        this.area_Name = area_Name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Phone_No
     *
     * @return the value of submit_await.Phone_No
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getPhone_No() {
        return phone_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Phone_No
     *
     * @param phone_No the value for submit_await.Phone_No
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setPhone_No(String phone_No) {
        this.phone_No = phone_No;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Protocol_Type_Code
     *
     * @return the value of submit_await.Protocol_Type_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getProtocol_Type_Code() {
        return protocol_Type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Protocol_Type_Code
     *
     * @param protocol_Type_Code the value for submit_await.Protocol_Type_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setProtocol_Type_Code(String protocol_Type_Code) {
        this.protocol_Type_Code = protocol_Type_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Submit_Status_Code
     *
     * @return the value of submit_await.Submit_Status_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getSubmit_Status_Code() {
        return submit_Status_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Submit_Status_Code
     *
     * @param submit_Status_Code the value for submit_await.Submit_Status_Code
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setSubmit_Status_Code(String submit_Status_Code) {
        this.submit_Status_Code = submit_Status_Code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Submit_Description
     *
     * @return the value of submit_await.Submit_Description
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getSubmit_Description() {
        return submit_Description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Submit_Description
     *
     * @param submit_Description the value for submit_await.Submit_Description
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setSubmit_Description(String submit_Description) {
        this.submit_Description = submit_Description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Submit_Date
     *
     * @return the value of submit_await.Submit_Date
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public Date getSubmit_Date() {
        return submit_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Submit_Date
     *
     * @param submit_Date the value for submit_await.Submit_Date
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setSubmit_Date(Date submit_Date) {
        this.submit_Date = submit_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Submit_Response_Date
     *
     * @return the value of submit_await.Submit_Response_Date
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public Date getSubmit_Response_Date() {
        return submit_Response_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Submit_Response_Date
     *
     * @param submit_Response_Date the value for submit_await.Submit_Response_Date
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setSubmit_Response_Date(Date submit_Response_Date) {
        this.submit_Response_Date = submit_Response_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Sender_Local_IP
     *
     * @return the value of submit_await.Sender_Local_IP
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getSender_Local_IP() {
        return sender_Local_IP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Sender_Local_IP
     *
     * @param sender_Local_IP the value for submit_await.Sender_Local_IP
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setSender_Local_IP(String sender_Local_IP) {
        this.sender_Local_IP = sender_Local_IP;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Sender_Local_Port
     *
     * @return the value of submit_await.Sender_Local_Port
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getSender_Local_Port() {
        return sender_Local_Port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Sender_Local_Port
     *
     * @param sender_Local_Port the value for submit_await.Sender_Local_Port
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setSender_Local_Port(String sender_Local_Port) {
        this.sender_Local_Port = sender_Local_Port;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Gate_Ip
     *
     * @return the value of submit_await.Gate_Ip
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getGate_Ip() {
        return gate_Ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Gate_Ip
     *
     * @param gate_Ip the value for submit_await.Gate_Ip
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setGate_Ip(String gate_Ip) {
        this.gate_Ip = gate_Ip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Enterprise_User_Taxes
     *
     * @return the value of submit_await.Enterprise_User_Taxes
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public BigDecimal getEnterprise_User_Taxes() {
        return enterprise_User_Taxes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Enterprise_User_Taxes
     *
     * @param enterprise_User_Taxes the value for submit_await.Enterprise_User_Taxes
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setEnterprise_User_Taxes(BigDecimal enterprise_User_Taxes) {
        this.enterprise_User_Taxes = enterprise_User_Taxes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Channel_Taxes
     *
     * @return the value of submit_await.Channel_Taxes
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public BigDecimal getChannel_Taxes() {
        return channel_Taxes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Channel_Taxes
     *
     * @param channel_Taxes the value for submit_await.Channel_Taxes
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setChannel_Taxes(BigDecimal channel_Taxes) {
        this.channel_Taxes = channel_Taxes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Channel_Unit_Price
     *
     * @return the value of submit_await.Channel_Unit_Price
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public BigDecimal getChannel_Unit_Price() {
        return channel_Unit_Price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Channel_Unit_Price
     *
     * @param channel_Unit_Price the value for submit_await.Channel_Unit_Price
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setChannel_Unit_Price(BigDecimal channel_Unit_Price) {
        this.channel_Unit_Price = channel_Unit_Price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Agent_Unit_Price
     *
     * @return the value of submit_await.Agent_Unit_Price
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public BigDecimal getAgent_Unit_Price() {
        return agent_Unit_Price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Agent_Unit_Price
     *
     * @param agent_Unit_Price the value for submit_await.Agent_Unit_Price
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setAgent_Unit_Price(BigDecimal agent_Unit_Price) {
        this.agent_Unit_Price = agent_Unit_Price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Agent_Taxes
     *
     * @return the value of submit_await.Agent_Taxes
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public BigDecimal getAgent_Taxes() {
        return agent_Taxes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Agent_Taxes
     *
     * @param agent_Taxes the value for submit_await.Agent_Taxes
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setAgent_Taxes(BigDecimal agent_Taxes) {
        this.agent_Taxes = agent_Taxes;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Enterprise_User_Unit_Price
     *
     * @return the value of submit_await.Enterprise_User_Unit_Price
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public BigDecimal getEnterprise_User_Unit_Price() {
        return enterprise_User_Unit_Price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Enterprise_User_Unit_Price
     *
     * @param enterprise_User_Unit_Price the value for submit_await.Enterprise_User_Unit_Price
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setEnterprise_User_Unit_Price(BigDecimal enterprise_User_Unit_Price) {
        this.enterprise_User_Unit_Price = enterprise_User_Unit_Price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Agent_Profits
     *
     * @return the value of submit_await.Agent_Profits
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public BigDecimal getAgent_Profits() {
        return agent_Profits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Agent_Profits
     *
     * @param agent_Profits the value for submit_await.Agent_Profits
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setAgent_Profits(BigDecimal agent_Profits) {
        this.agent_Profits = agent_Profits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Profits
     *
     * @return the value of submit_await.Profits
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public BigDecimal getProfits() {
        return profits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Profits
     *
     * @param profits the value for submit_await.Profits
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setProfits(BigDecimal profits) {
        this.profits = profits;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Input_Log_Date
     *
     * @return the value of submit_await.Input_Log_Date
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public Date getInput_Log_Date() {
        return input_Log_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Input_Log_Date
     *
     * @param input_Log_Date the value for submit_await.Input_Log_Date
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setInput_Log_Date(Date input_Log_Date) {
        this.input_Log_Date = input_Log_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Description
     *
     * @return the value of submit_await.Description
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Description
     *
     * @param description the value for submit_await.Description
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Remark
     *
     * @return the value of submit_await.Remark
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Remark
     *
     * @param remark the value for submit_await.Remark
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setRemark(String remark) {
        this.remark = remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column submit_await.Create_Date
     *
     * @return the value of submit_await.Create_Date
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public Date getCreate_Date() {
        return create_Date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column submit_await.Create_Date
     *
     * @param create_Date the value for submit_await.Create_Date
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    public void setCreate_Date(Date create_Date) {
        this.create_Date = create_Date;
    }
}