package com.hero.wireless.web.dao.send;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.send.AutoReplySms;
import com.hero.wireless.web.entity.send.AutoReplySmsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IAutoReplySmsDAO<T extends AutoReplySms> extends IDao<AutoReplySms, AutoReplySmsExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reply_sms
     *
     * @mbg.generated Sun Sep 15 02:39:28 CST 2019
     */
    int countByExample(AutoReplySmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reply_sms
     *
     * @mbg.generated Sun Sep 15 02:39:28 CST 2019
     */
    int deleteByExample(AutoReplySmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reply_sms
     *
     * @mbg.generated Sun Sep 15 02:39:28 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reply_sms
     *
     * @mbg.generated Sun Sep 15 02:39:28 CST 2019
     */
    int insert(AutoReplySms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reply_sms
     *
     * @mbg.generated Sun Sep 15 02:39:28 CST 2019
     */
    int insertList(List<AutoReplySms> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reply_sms
     *
     * @mbg.generated Sun Sep 15 02:39:28 CST 2019
     */
    int insertSelective(AutoReplySms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reply_sms
     *
     * @mbg.generated Sun Sep 15 02:39:28 CST 2019
     */
    List<AutoReplySms> selectByExample(AutoReplySmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reply_sms
     *
     * @mbg.generated Sun Sep 15 02:39:28 CST 2019
     */
    AutoReplySms selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reply_sms
     *
     * @mbg.generated Sun Sep 15 02:39:28 CST 2019
     */
    int updateByExampleSelective(@Param("record") AutoReplySms record, @Param("example") AutoReplySmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reply_sms
     *
     * @mbg.generated Sun Sep 15 02:39:28 CST 2019
     */
    int updateByExample(@Param("record") AutoReplySms record, @Param("example") AutoReplySmsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reply_sms
     *
     * @mbg.generated Sun Sep 15 02:39:28 CST 2019
     */
    int updateByPrimaryKeySelective(AutoReplySms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table auto_reply_sms
     *
     * @mbg.generated Sun Sep 15 02:39:28 CST 2019
     */
    int updateByPrimaryKey(AutoReplySms record);
}