package com.hero.wireless.web.dao.send;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.send.Inbox;
import com.hero.wireless.web.entity.send.InboxExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IInboxDAO<T extends Inbox> extends IDao<Inbox, InboxExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbg.generated Thu May 14 16:56:20 CST 2020
     */
    int countByExample(InboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbg.generated Thu May 14 16:56:20 CST 2020
     */
    int deleteByExample(InboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbg.generated Thu May 14 16:56:20 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbg.generated Thu May 14 16:56:20 CST 2020
     */
    int insert(Inbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbg.generated Thu May 14 16:56:20 CST 2020
     */
    int insertList(List<Inbox> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbg.generated Thu May 14 16:56:20 CST 2020
     */
    int insertSelective(Inbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbg.generated Thu May 14 16:56:20 CST 2020
     */
    List<Inbox> selectByExample(InboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbg.generated Thu May 14 16:56:20 CST 2020
     */
    Inbox selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbg.generated Thu May 14 16:56:20 CST 2020
     */
    int updateByExampleSelective(@Param("record") Inbox record, @Param("example") InboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbg.generated Thu May 14 16:56:20 CST 2020
     */
    int updateByExample(@Param("record") Inbox record, @Param("example") InboxExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbg.generated Thu May 14 16:56:20 CST 2020
     */
    int updateByPrimaryKeySelective(Inbox record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table inbox
     *
     * @mbg.generated Thu May 14 16:56:20 CST 2020
     */
    int updateByPrimaryKey(Inbox record);
}