package com.hero.wireless.web.dao.send;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.send.InputLog;
import com.hero.wireless.web.entity.send.InputLogExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IInputLogDAO<T extends InputLog> extends IDao<InputLog, InputLogExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input_log
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    int countByExample(InputLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input_log
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    int deleteByExample(InputLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input_log
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input_log
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    int insert(InputLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input_log
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    int insertList(List<InputLog> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input_log
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    int insertSelective(InputLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input_log
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    List<InputLog> selectByExample(InputLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input_log
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    InputLog selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input_log
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") InputLog record, @Param("example") InputLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input_log
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    int updateByExample(@Param("record") InputLog record, @Param("example") InputLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input_log
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    int updateByPrimaryKeySelective(InputLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input_log
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    int updateByPrimaryKey(InputLog record);
}