package com.hero.wireless.web.dao.send;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.send.Input;
import com.hero.wireless.web.entity.send.InputExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IInputDAO<T extends Input> extends IDao<Input, InputExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    int countByExample(InputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    int deleteByExample(InputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    int insert(Input record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    int insertList(List<Input> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    int insertSelective(Input record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    List<Input> selectByExample(InputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    Input selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    int updateByExampleSelective(@Param("record") Input record, @Param("example") InputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    int updateByExample(@Param("record") Input record, @Param("example") InputExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    int updateByPrimaryKeySelective(Input record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table input
     *
     * @mbg.generated Sun Sep 27 14:53:50 CST 2020
     */
    int updateByPrimaryKey(Input record);
}