package com.hero.wireless.web.dao.send;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.send.ReportExtra;
import com.hero.wireless.web.entity.send.ReportExtraExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IReportExtraDAO<T extends ReportExtra> extends IDao<ReportExtra, ReportExtraExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_extra
     *
     * @mbg.generated Thu Dec 24 14:15:16 CST 2020
     */
    int countByExample(ReportExtraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_extra
     *
     * @mbg.generated Thu Dec 24 14:15:16 CST 2020
     */
    int deleteByExample(ReportExtraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_extra
     *
     * @mbg.generated Thu Dec 24 14:15:16 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_extra
     *
     * @mbg.generated Thu Dec 24 14:15:16 CST 2020
     */
    int insert(ReportExtra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_extra
     *
     * @mbg.generated Thu Dec 24 14:15:16 CST 2020
     */
    int insertList(List<ReportExtra> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_extra
     *
     * @mbg.generated Thu Dec 24 14:15:16 CST 2020
     */
    int insertSelective(ReportExtra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_extra
     *
     * @mbg.generated Thu Dec 24 14:15:16 CST 2020
     */
    List<ReportExtra> selectByExample(ReportExtraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_extra
     *
     * @mbg.generated Thu Dec 24 14:15:16 CST 2020
     */
    ReportExtra selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_extra
     *
     * @mbg.generated Thu Dec 24 14:15:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") ReportExtra record, @Param("example") ReportExtraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_extra
     *
     * @mbg.generated Thu Dec 24 14:15:16 CST 2020
     */
    int updateByExample(@Param("record") ReportExtra record, @Param("example") ReportExtraExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_extra
     *
     * @mbg.generated Thu Dec 24 14:15:16 CST 2020
     */
    int updateByPrimaryKeySelective(ReportExtra record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_extra
     *
     * @mbg.generated Thu Dec 24 14:15:16 CST 2020
     */
    int updateByPrimaryKey(ReportExtra record);
}