package com.hero.wireless.web.dao.send;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.send.ReportNotify;
import com.hero.wireless.web.entity.send.ReportNotifyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IReportNotifyDAO<T extends ReportNotify> extends IDao<ReportNotify, ReportNotifyExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_notify
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    int countByExample(ReportNotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_notify
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    int deleteByExample(ReportNotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_notify
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_notify
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    int insert(ReportNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_notify
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    int insertList(List<ReportNotify> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_notify
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    int insertSelective(ReportNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_notify
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    List<ReportNotify> selectByExample(ReportNotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_notify
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    ReportNotify selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_notify
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    int updateByExampleSelective(@Param("record") ReportNotify record, @Param("example") ReportNotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_notify
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    int updateByExample(@Param("record") ReportNotify record, @Param("example") ReportNotifyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_notify
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    int updateByPrimaryKeySelective(ReportNotify record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table report_notify
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    int updateByPrimaryKey(ReportNotify record);
}