package com.hero.wireless.web.dao.send;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.send.SubmitExpired;
import com.hero.wireless.web.entity.send.SubmitExpiredExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ISubmitExpiredDAO<T extends SubmitExpired> extends IDao<SubmitExpired, SubmitExpiredExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_expired
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    int countByExample(SubmitExpiredExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_expired
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    int deleteByExample(SubmitExpiredExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_expired
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_expired
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    int insert(SubmitExpired record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_expired
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    int insertList(List<SubmitExpired> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_expired
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    int insertSelective(SubmitExpired record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_expired
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    List<SubmitExpired> selectByExample(SubmitExpiredExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_expired
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    SubmitExpired selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_expired
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    int updateByExampleSelective(@Param("record") SubmitExpired record, @Param("example") SubmitExpiredExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_expired
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    int updateByExample(@Param("record") SubmitExpired record, @Param("example") SubmitExpiredExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_expired
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    int updateByPrimaryKeySelective(SubmitExpired record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_expired
     *
     * @mbg.generated Thu Jan 07 20:02:42 CST 2021
     */
    int updateByPrimaryKey(SubmitExpired record);
}