package com.hero.wireless.web.dao.send;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.send.SubmitAwait;
import com.hero.wireless.web.entity.send.SubmitAwaitExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ISubmitAwaitDAO<T extends SubmitAwait> extends IDao<SubmitAwait, SubmitAwaitExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_await
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    int countByExample(SubmitAwaitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_await
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    int deleteByExample(SubmitAwaitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_await
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_await
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    int insert(SubmitAwait record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_await
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    int insertList(List<SubmitAwait> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_await
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    int insertSelective(SubmitAwait record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_await
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    List<SubmitAwait> selectByExample(SubmitAwaitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_await
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    SubmitAwait selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_await
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    int updateByExampleSelective(@Param("record") SubmitAwait record, @Param("example") SubmitAwaitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_await
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    int updateByExample(@Param("record") SubmitAwait record, @Param("example") SubmitAwaitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_await
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    int updateByPrimaryKeySelective(SubmitAwait record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table submit_await
     *
     * @mbg.generated Fri Jun 04 17:24:16 CST 2021
     */
    int updateByPrimaryKey(SubmitAwait record);
}