package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.AdminUserRoles;
import com.hero.wireless.web.entity.business.AdminUserRolesExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IAdminUserRolesDAO<T extends AdminUserRoles> extends IDao<AdminUserRoles, AdminUserRolesExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int countByExample(AdminUserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int deleteByExample(AdminUserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insert(AdminUserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insertList(List<AdminUserRoles> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insertSelective(AdminUserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    List<AdminUserRoles> selectByExample(AdminUserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    AdminUserRoles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") AdminUserRoles record, @Param("example") AdminUserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByExample(@Param("record") AdminUserRoles record, @Param("example") AdminUserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByPrimaryKeySelective(AdminUserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByPrimaryKey(AdminUserRoles record);
}