package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.AdminRoleLimit;
import com.hero.wireless.web.entity.business.AdminRoleLimitExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IAdminRoleLimitDAO<T extends AdminRoleLimit> extends IDao<AdminRoleLimit, AdminRoleLimitExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int countByExample(AdminRoleLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int deleteByExample(AdminRoleLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insert(AdminRoleLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insertList(List<AdminRoleLimit> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insertSelective(AdminRoleLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    List<AdminRoleLimit> selectByExample(AdminRoleLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    AdminRoleLimit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") AdminRoleLimit record, @Param("example") AdminRoleLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByExample(@Param("record") AdminRoleLimit record, @Param("example") AdminRoleLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByPrimaryKeySelective(AdminRoleLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByPrimaryKey(AdminRoleLimit record);
}