package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.AdminLimit;
import com.hero.wireless.web.entity.business.AdminLimitExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IAdminLimitDAO<T extends AdminLimit> extends IDao<AdminLimit, AdminLimitExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int countByExample(AdminLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int deleteByExample(AdminLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insert(AdminLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insertList(List<AdminLimit> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insertSelective(AdminLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    List<AdminLimit> selectByExample(AdminLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    AdminLimit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") AdminLimit record, @Param("example") AdminLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByExample(@Param("record") AdminLimit record, @Param("example") AdminLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByPrimaryKeySelective(AdminLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table admin_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByPrimaryKey(AdminLimit record);
}