package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.ChargeOrder;
import com.hero.wireless.web.entity.business.ChargeOrderExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IChargeOrderDAO<T extends ChargeOrder> extends IDao<ChargeOrder, ChargeOrderExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Fri Oct 25 13:58:54 CST 2019
     */
    int countByExample(ChargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Fri Oct 25 13:58:54 CST 2019
     */
    int deleteByExample(ChargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Fri Oct 25 13:58:54 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Fri Oct 25 13:58:54 CST 2019
     */
    int insert(ChargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Fri Oct 25 13:58:54 CST 2019
     */
    int insertList(List<ChargeOrder> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Fri Oct 25 13:58:54 CST 2019
     */
    int insertSelective(ChargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Fri Oct 25 13:58:54 CST 2019
     */
    List<ChargeOrder> selectByExample(ChargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Fri Oct 25 13:58:54 CST 2019
     */
    ChargeOrder selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Fri Oct 25 13:58:54 CST 2019
     */
    int updateByExampleSelective(@Param("record") ChargeOrder record, @Param("example") ChargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Fri Oct 25 13:58:54 CST 2019
     */
    int updateByExample(@Param("record") ChargeOrder record, @Param("example") ChargeOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Fri Oct 25 13:58:54 CST 2019
     */
    int updateByPrimaryKeySelective(ChargeOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table charge_order
     *
     * @mbg.generated Fri Oct 25 13:58:54 CST 2019
     */
    int updateByPrimaryKey(ChargeOrder record);
}