package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.Channel;
import com.hero.wireless.web.entity.business.ChannelExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IChannelDAO<T extends Channel> extends IDao<Channel, ChannelExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Wed Oct 02 09:06:27 CST 2019
     */
    int countByExample(ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Wed Oct 02 09:06:27 CST 2019
     */
    int deleteByExample(ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Wed Oct 02 09:06:27 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Wed Oct 02 09:06:27 CST 2019
     */
    int insert(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Wed Oct 02 09:06:27 CST 2019
     */
    int insertList(List<Channel> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Wed Oct 02 09:06:27 CST 2019
     */
    int insertSelective(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Wed Oct 02 09:06:27 CST 2019
     */
    List<Channel> selectByExample(ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Wed Oct 02 09:06:27 CST 2019
     */
    Channel selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Wed Oct 02 09:06:27 CST 2019
     */
    int updateByExampleSelective(@Param("record") Channel record, @Param("example") ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Wed Oct 02 09:06:27 CST 2019
     */
    int updateByExample(@Param("record") Channel record, @Param("example") ChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Wed Oct 02 09:06:27 CST 2019
     */
    int updateByPrimaryKeySelective(Channel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table channel
     *
     * @mbg.generated Wed Oct 02 09:06:27 CST 2019
     */
    int updateByPrimaryKey(Channel record);
}