package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.CodeSort;
import com.hero.wireless.web.entity.business.CodeSortExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ICodeSortDAO<T extends CodeSort> extends IDao<CodeSort, CodeSortExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_sort
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int countByExample(CodeSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_sort
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int deleteByExample(CodeSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_sort
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_sort
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insert(CodeSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_sort
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insertList(List<CodeSort> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_sort
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insertSelective(CodeSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_sort
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    List<CodeSort> selectByExample(CodeSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_sort
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    CodeSort selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_sort
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") CodeSort record, @Param("example") CodeSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_sort
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByExample(@Param("record") CodeSort record, @Param("example") CodeSortExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_sort
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByPrimaryKeySelective(CodeSort record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table code_sort
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByPrimaryKey(CodeSort record);
}