package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.EnterpriseUserRoles;
import com.hero.wireless.web.entity.business.EnterpriseUserRolesExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IEnterpriseUserRolesDAO<T extends EnterpriseUserRoles> extends IDao<EnterpriseUserRoles, EnterpriseUserRolesExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int countByExample(EnterpriseUserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int deleteByExample(EnterpriseUserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insert(EnterpriseUserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insertList(List<EnterpriseUserRoles> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insertSelective(EnterpriseUserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    List<EnterpriseUserRoles> selectByExample(EnterpriseUserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    EnterpriseUserRoles selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") EnterpriseUserRoles record, @Param("example") EnterpriseUserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByExample(@Param("record") EnterpriseUserRoles record, @Param("example") EnterpriseUserRolesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByPrimaryKeySelective(EnterpriseUserRoles record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user_roles
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByPrimaryKey(EnterpriseUserRoles record);
}