package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.EnterpriseRoleLimit;
import com.hero.wireless.web.entity.business.EnterpriseRoleLimitExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IEnterpriseRoleLimitDAO<T extends EnterpriseRoleLimit> extends IDao<EnterpriseRoleLimit, EnterpriseRoleLimitExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int countByExample(EnterpriseRoleLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int deleteByExample(EnterpriseRoleLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insert(EnterpriseRoleLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insertList(List<EnterpriseRoleLimit> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insertSelective(EnterpriseRoleLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    List<EnterpriseRoleLimit> selectByExample(EnterpriseRoleLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    EnterpriseRoleLimit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") EnterpriseRoleLimit record, @Param("example") EnterpriseRoleLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByExample(@Param("record") EnterpriseRoleLimit record, @Param("example") EnterpriseRoleLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByPrimaryKeySelective(EnterpriseRoleLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByPrimaryKey(EnterpriseRoleLimit record);
}