package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.EnterpriseUser;
import com.hero.wireless.web.entity.business.EnterpriseUserExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IEnterpriseUserDAO<T extends EnterpriseUser> extends IDao<EnterpriseUser, EnterpriseUserExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user
     *
     * @mbg.generated Wed Dec 30 14:44:46 CST 2020
     */
    int countByExample(EnterpriseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user
     *
     * @mbg.generated Wed Dec 30 14:44:46 CST 2020
     */
    int deleteByExample(EnterpriseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user
     *
     * @mbg.generated Wed Dec 30 14:44:46 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user
     *
     * @mbg.generated Wed Dec 30 14:44:46 CST 2020
     */
    int insert(EnterpriseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user
     *
     * @mbg.generated Wed Dec 30 14:44:46 CST 2020
     */
    int insertList(List<EnterpriseUser> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user
     *
     * @mbg.generated Wed Dec 30 14:44:46 CST 2020
     */
    int insertSelective(EnterpriseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user
     *
     * @mbg.generated Wed Dec 30 14:44:46 CST 2020
     */
    List<EnterpriseUser> selectByExample(EnterpriseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user
     *
     * @mbg.generated Wed Dec 30 14:44:46 CST 2020
     */
    EnterpriseUser selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user
     *
     * @mbg.generated Wed Dec 30 14:44:46 CST 2020
     */
    int updateByExampleSelective(@Param("record") EnterpriseUser record, @Param("example") EnterpriseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user
     *
     * @mbg.generated Wed Dec 30 14:44:46 CST 2020
     */
    int updateByExample(@Param("record") EnterpriseUser record, @Param("example") EnterpriseUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user
     *
     * @mbg.generated Wed Dec 30 14:44:46 CST 2020
     */
    int updateByPrimaryKeySelective(EnterpriseUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_user
     *
     * @mbg.generated Wed Dec 30 14:44:46 CST 2020
     */
    int updateByPrimaryKey(EnterpriseUser record);
}