package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.EnterpriseRole;
import com.hero.wireless.web.entity.business.EnterpriseRoleExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IEnterpriseRoleDAO<T extends EnterpriseRole> extends IDao<EnterpriseRole, EnterpriseRoleExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int countByExample(EnterpriseRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int deleteByExample(EnterpriseRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insert(EnterpriseRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insertList(List<EnterpriseRole> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insertSelective(EnterpriseRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    List<EnterpriseRole> selectByExample(EnterpriseRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    EnterpriseRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") EnterpriseRole record, @Param("example") EnterpriseRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByExample(@Param("record") EnterpriseRole record, @Param("example") EnterpriseRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByPrimaryKeySelective(EnterpriseRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_role
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByPrimaryKey(EnterpriseRole record);
}