package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.EnterpriseLimit;
import com.hero.wireless.web.entity.business.EnterpriseLimitExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IEnterpriseLimitDAO<T extends EnterpriseLimit> extends IDao<EnterpriseLimit, EnterpriseLimitExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int countByExample(EnterpriseLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int deleteByExample(EnterpriseLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insert(EnterpriseLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insertList(List<EnterpriseLimit> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insertSelective(EnterpriseLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    List<EnterpriseLimit> selectByExample(EnterpriseLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    EnterpriseLimit selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") EnterpriseLimit record, @Param("example") EnterpriseLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByExample(@Param("record") EnterpriseLimit record, @Param("example") EnterpriseLimitExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByPrimaryKeySelective(EnterpriseLimit record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_limit
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByPrimaryKey(EnterpriseLimit record);
}