package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.ExportFile;
import com.hero.wireless.web.entity.business.ExportFileExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IExportFileDAO<T extends ExportFile> extends IDao<ExportFile, ExportFileExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbg.generated Sat Sep 14 11:02:14 CST 2019
     */
    int countByExample(ExportFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbg.generated Sat Sep 14 11:02:14 CST 2019
     */
    int deleteByExample(ExportFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbg.generated Sat Sep 14 11:02:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbg.generated Sat Sep 14 11:02:14 CST 2019
     */
    int insert(ExportFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbg.generated Sat Sep 14 11:02:14 CST 2019
     */
    int insertList(List<ExportFile> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbg.generated Sat Sep 14 11:02:14 CST 2019
     */
    int insertSelective(ExportFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbg.generated Sat Sep 14 11:02:14 CST 2019
     */
    List<ExportFile> selectByExample(ExportFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbg.generated Sat Sep 14 11:02:14 CST 2019
     */
    ExportFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbg.generated Sat Sep 14 11:02:14 CST 2019
     */
    int updateByExampleSelective(@Param("record") ExportFile record, @Param("example") ExportFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbg.generated Sat Sep 14 11:02:14 CST 2019
     */
    int updateByExample(@Param("record") ExportFile record, @Param("example") ExportFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbg.generated Sat Sep 14 11:02:14 CST 2019
     */
    int updateByPrimaryKeySelective(ExportFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table export_file
     *
     * @mbg.generated Sat Sep 14 11:02:14 CST 2019
     */
    int updateByPrimaryKey(ExportFile record);
}