package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.InterceptStrategy;
import com.hero.wireless.web.entity.business.InterceptStrategyExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IInterceptStrategyDAO<T extends InterceptStrategy> extends IDao<InterceptStrategy, InterceptStrategyExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intercept_strategy
     *
     * @mbg.generated Mon Jan 13 10:00:09 CST 2020
     */
    int countByExample(InterceptStrategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intercept_strategy
     *
     * @mbg.generated Mon Jan 13 10:00:09 CST 2020
     */
    int deleteByExample(InterceptStrategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intercept_strategy
     *
     * @mbg.generated Mon Jan 13 10:00:09 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intercept_strategy
     *
     * @mbg.generated Mon Jan 13 10:00:09 CST 2020
     */
    int insert(InterceptStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intercept_strategy
     *
     * @mbg.generated Mon Jan 13 10:00:09 CST 2020
     */
    int insertList(List<InterceptStrategy> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intercept_strategy
     *
     * @mbg.generated Mon Jan 13 10:00:09 CST 2020
     */
    int insertSelective(InterceptStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intercept_strategy
     *
     * @mbg.generated Mon Jan 13 10:00:09 CST 2020
     */
    List<InterceptStrategy> selectByExample(InterceptStrategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intercept_strategy
     *
     * @mbg.generated Mon Jan 13 10:00:09 CST 2020
     */
    InterceptStrategy selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intercept_strategy
     *
     * @mbg.generated Mon Jan 13 10:00:09 CST 2020
     */
    int updateByExampleSelective(@Param("record") InterceptStrategy record, @Param("example") InterceptStrategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intercept_strategy
     *
     * @mbg.generated Mon Jan 13 10:00:09 CST 2020
     */
    int updateByExample(@Param("record") InterceptStrategy record, @Param("example") InterceptStrategyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intercept_strategy
     *
     * @mbg.generated Mon Jan 13 10:00:09 CST 2020
     */
    int updateByPrimaryKeySelective(InterceptStrategy record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table intercept_strategy
     *
     * @mbg.generated Mon Jan 13 10:00:09 CST 2020
     */
    int updateByPrimaryKey(InterceptStrategy record);
}