package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.MmsTemplate;
import com.hero.wireless.web.entity.business.MmsTemplateExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IMmsTemplateDAO<T extends MmsTemplate> extends IDao<MmsTemplate, MmsTemplateExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_template
     *
     * @mbg.generated Fri Dec 27 09:09:57 CST 2019
     */
    int countByExample(MmsTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_template
     *
     * @mbg.generated Fri Dec 27 09:09:57 CST 2019
     */
    int deleteByExample(MmsTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_template
     *
     * @mbg.generated Fri Dec 27 09:09:57 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_template
     *
     * @mbg.generated Fri Dec 27 09:09:57 CST 2019
     */
    int insert(MmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_template
     *
     * @mbg.generated Fri Dec 27 09:09:57 CST 2019
     */
    int insertList(List<MmsTemplate> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_template
     *
     * @mbg.generated Fri Dec 27 09:09:57 CST 2019
     */
    int insertSelective(MmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_template
     *
     * @mbg.generated Fri Dec 27 09:09:57 CST 2019
     */
    List<MmsTemplate> selectByExample(MmsTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_template
     *
     * @mbg.generated Fri Dec 27 09:09:57 CST 2019
     */
    MmsTemplate selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_template
     *
     * @mbg.generated Fri Dec 27 09:09:57 CST 2019
     */
    int updateByExampleSelective(@Param("record") MmsTemplate record, @Param("example") MmsTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_template
     *
     * @mbg.generated Fri Dec 27 09:09:57 CST 2019
     */
    int updateByExample(@Param("record") MmsTemplate record, @Param("example") MmsTemplateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_template
     *
     * @mbg.generated Fri Dec 27 09:09:57 CST 2019
     */
    int updateByPrimaryKeySelective(MmsTemplate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mms_template
     *
     * @mbg.generated Fri Dec 27 09:09:57 CST 2019
     */
    int updateByPrimaryKey(MmsTemplate record);
}