package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.PlatformSmsStatistics;
import com.hero.wireless.web.entity.business.PlatformSmsStatisticsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IPlatformSmsStatisticsDAO<T extends PlatformSmsStatistics> extends IDao<PlatformSmsStatistics, PlatformSmsStatisticsExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    int countByExample(PlatformSmsStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    int deleteByExample(PlatformSmsStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    int insert(PlatformSmsStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    int insertList(List<PlatformSmsStatistics> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    int insertSelective(PlatformSmsStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    List<PlatformSmsStatistics> selectByExample(PlatformSmsStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    PlatformSmsStatistics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    int updateByExampleSelective(@Param("record") PlatformSmsStatistics record, @Param("example") PlatformSmsStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    int updateByExample(@Param("record") PlatformSmsStatistics record, @Param("example") PlatformSmsStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    int updateByPrimaryKeySelective(PlatformSmsStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table platform_sms_statistics
     *
     * @mbg.generated Wed Jun 10 18:52:20 CST 2020
     */
    int updateByPrimaryKey(PlatformSmsStatistics record);
}