package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.ProductChannelsDiversion;
import com.hero.wireless.web.entity.business.ProductChannelsDiversionExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IProductChannelsDiversionDAO<T extends ProductChannelsDiversion> extends IDao<ProductChannelsDiversion, ProductChannelsDiversionExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels_diversion
     *
     * @mbg.generated Sun Feb 09 11:02:54 CST 2020
     */
    int countByExample(ProductChannelsDiversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels_diversion
     *
     * @mbg.generated Sun Feb 09 11:02:54 CST 2020
     */
    int deleteByExample(ProductChannelsDiversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels_diversion
     *
     * @mbg.generated Sun Feb 09 11:02:54 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels_diversion
     *
     * @mbg.generated Sun Feb 09 11:02:54 CST 2020
     */
    int insert(ProductChannelsDiversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels_diversion
     *
     * @mbg.generated Sun Feb 09 11:02:54 CST 2020
     */
    int insertList(List<ProductChannelsDiversion> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels_diversion
     *
     * @mbg.generated Sun Feb 09 11:02:54 CST 2020
     */
    int insertSelective(ProductChannelsDiversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels_diversion
     *
     * @mbg.generated Sun Feb 09 11:02:54 CST 2020
     */
    List<ProductChannelsDiversion> selectByExample(ProductChannelsDiversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels_diversion
     *
     * @mbg.generated Sun Feb 09 11:02:54 CST 2020
     */
    ProductChannelsDiversion selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels_diversion
     *
     * @mbg.generated Sun Feb 09 11:02:54 CST 2020
     */
    int updateByExampleSelective(@Param("record") ProductChannelsDiversion record, @Param("example") ProductChannelsDiversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels_diversion
     *
     * @mbg.generated Sun Feb 09 11:02:54 CST 2020
     */
    int updateByExample(@Param("record") ProductChannelsDiversion record, @Param("example") ProductChannelsDiversionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels_diversion
     *
     * @mbg.generated Sun Feb 09 11:02:54 CST 2020
     */
    int updateByPrimaryKeySelective(ProductChannelsDiversion record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels_diversion
     *
     * @mbg.generated Sun Feb 09 11:02:54 CST 2020
     */
    int updateByPrimaryKey(ProductChannelsDiversion record);
}