package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.Properties;
import com.hero.wireless.web.entity.business.PropertiesExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IPropertiesDAO<T extends Properties> extends IDao<Properties, PropertiesExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbg.generated Fri Apr 03 10:22:01 CST 2020
     */
    int countByExample(PropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbg.generated Fri Apr 03 10:22:01 CST 2020
     */
    int deleteByExample(PropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbg.generated Fri Apr 03 10:22:01 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbg.generated Fri Apr 03 10:22:01 CST 2020
     */
    int insert(Properties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbg.generated Fri Apr 03 10:22:01 CST 2020
     */
    int insertList(List<Properties> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbg.generated Fri Apr 03 10:22:01 CST 2020
     */
    int insertSelective(Properties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbg.generated Fri Apr 03 10:22:01 CST 2020
     */
    List<Properties> selectByExample(PropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbg.generated Fri Apr 03 10:22:01 CST 2020
     */
    Properties selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbg.generated Fri Apr 03 10:22:01 CST 2020
     */
    int updateByExampleSelective(@Param("record") Properties record, @Param("example") PropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbg.generated Fri Apr 03 10:22:01 CST 2020
     */
    int updateByExample(@Param("record") Properties record, @Param("example") PropertiesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbg.generated Fri Apr 03 10:22:01 CST 2020
     */
    int updateByPrimaryKeySelective(Properties record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table properties
     *
     * @mbg.generated Fri Apr 03 10:22:01 CST 2020
     */
    int updateByPrimaryKey(Properties record);
}