package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.ProductChannels;
import com.hero.wireless.web.entity.business.ProductChannelsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IProductChannelsDAO<T extends ProductChannels> extends IDao<ProductChannels, ProductChannelsExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels
     *
     * @mbg.generated Sun Feb 09 11:00:34 CST 2020
     */
    int countByExample(ProductChannelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels
     *
     * @mbg.generated Sun Feb 09 11:00:34 CST 2020
     */
    int deleteByExample(ProductChannelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels
     *
     * @mbg.generated Sun Feb 09 11:00:34 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels
     *
     * @mbg.generated Sun Feb 09 11:00:34 CST 2020
     */
    int insert(ProductChannels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels
     *
     * @mbg.generated Sun Feb 09 11:00:34 CST 2020
     */
    int insertList(List<ProductChannels> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels
     *
     * @mbg.generated Sun Feb 09 11:00:34 CST 2020
     */
    int insertSelective(ProductChannels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels
     *
     * @mbg.generated Sun Feb 09 11:00:34 CST 2020
     */
    List<ProductChannels> selectByExample(ProductChannelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels
     *
     * @mbg.generated Sun Feb 09 11:00:34 CST 2020
     */
    ProductChannels selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels
     *
     * @mbg.generated Sun Feb 09 11:00:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") ProductChannels record, @Param("example") ProductChannelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels
     *
     * @mbg.generated Sun Feb 09 11:00:34 CST 2020
     */
    int updateByExample(@Param("record") ProductChannels record, @Param("example") ProductChannelsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels
     *
     * @mbg.generated Sun Feb 09 11:00:34 CST 2020
     */
    int updateByPrimaryKeySelective(ProductChannels record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_channels
     *
     * @mbg.generated Sun Feb 09 11:00:34 CST 2020
     */
    int updateByPrimaryKey(ProductChannels record);
}