package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.SensitiveWord;
import com.hero.wireless.web.entity.business.SensitiveWordExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ISensitiveWordDAO<T extends SensitiveWord> extends IDao<SensitiveWord, SensitiveWordExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbg.generated Mon Sep 30 15:38:24 CST 2019
     */
    int countByExample(SensitiveWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbg.generated Mon Sep 30 15:38:24 CST 2019
     */
    int deleteByExample(SensitiveWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbg.generated Mon Sep 30 15:38:24 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbg.generated Mon Sep 30 15:38:24 CST 2019
     */
    int insert(SensitiveWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbg.generated Mon Sep 30 15:38:24 CST 2019
     */
    int insertList(List<SensitiveWord> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbg.generated Mon Sep 30 15:38:24 CST 2019
     */
    int insertSelective(SensitiveWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbg.generated Mon Sep 30 15:38:24 CST 2019
     */
    List<SensitiveWord> selectByExample(SensitiveWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbg.generated Mon Sep 30 15:38:24 CST 2019
     */
    SensitiveWord selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbg.generated Mon Sep 30 15:38:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") SensitiveWord record, @Param("example") SensitiveWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbg.generated Mon Sep 30 15:38:24 CST 2019
     */
    int updateByExample(@Param("record") SensitiveWord record, @Param("example") SensitiveWordExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbg.generated Mon Sep 30 15:38:24 CST 2019
     */
    int updateByPrimaryKeySelective(SensitiveWord record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sensitive_word
     *
     * @mbg.generated Mon Sep 30 15:38:24 CST 2019
     */
    int updateByPrimaryKey(SensitiveWord record);
}