package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.SmsRoute;
import com.hero.wireless.web.entity.business.SmsRouteExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ISmsRouteDAO<T extends SmsRoute> extends IDao<SmsRoute, SmsRouteExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_route
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int countByExample(SmsRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_route
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int deleteByExample(SmsRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_route
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_route
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insert(SmsRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_route
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insertList(List<SmsRoute> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_route
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int insertSelective(SmsRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_route
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    List<SmsRoute> selectByExample(SmsRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_route
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    SmsRoute selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_route
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByExampleSelective(@Param("record") SmsRoute record, @Param("example") SmsRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_route
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByExample(@Param("record") SmsRoute record, @Param("example") SmsRouteExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_route
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByPrimaryKeySelective(SmsRoute record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_route
     *
     * @mbg.generated Sat Sep 14 11:02:15 CST 2019
     */
    int updateByPrimaryKey(SmsRoute record);
}