package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.SmsStatistics;
import com.hero.wireless.web.entity.business.SmsStatisticsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ISmsStatisticsDAO<T extends SmsStatistics> extends IDao<SmsStatistics, SmsStatisticsExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    int countByExample(SmsStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    int deleteByExample(SmsStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    int insert(SmsStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    int insertList(List<SmsStatistics> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    int insertSelective(SmsStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    List<SmsStatistics> selectByExample(SmsStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    SmsStatistics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    int updateByExampleSelective(@Param("record") SmsStatistics record, @Param("example") SmsStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    int updateByExample(@Param("record") SmsStatistics record, @Param("example") SmsStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    int updateByPrimaryKeySelective(SmsStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_statistics
     *
     * @mbg.generated Fri Jun 19 11:46:42 CST 2020
     */
    int updateByPrimaryKey(SmsStatistics record);
}