package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.SmsRealTimeStatistics;
import com.hero.wireless.web.entity.business.SmsRealTimeStatisticsExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface ISmsRealTimeStatisticsDAO<T extends SmsRealTimeStatistics> extends IDao<SmsRealTimeStatistics, SmsRealTimeStatisticsExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_real_time_statistics
     *
     * @mbg.generated Thu Jun 18 14:42:02 CST 2020
     */
    int countByExample(SmsRealTimeStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_real_time_statistics
     *
     * @mbg.generated Thu Jun 18 14:42:02 CST 2020
     */
    int deleteByExample(SmsRealTimeStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_real_time_statistics
     *
     * @mbg.generated Thu Jun 18 14:42:02 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_real_time_statistics
     *
     * @mbg.generated Thu Jun 18 14:42:02 CST 2020
     */
    int insert(SmsRealTimeStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_real_time_statistics
     *
     * @mbg.generated Thu Jun 18 14:42:02 CST 2020
     */
    int insertList(List<SmsRealTimeStatistics> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_real_time_statistics
     *
     * @mbg.generated Thu Jun 18 14:42:02 CST 2020
     */
    int insertSelective(SmsRealTimeStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_real_time_statistics
     *
     * @mbg.generated Thu Jun 18 14:42:02 CST 2020
     */
    List<SmsRealTimeStatistics> selectByExample(SmsRealTimeStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_real_time_statistics
     *
     * @mbg.generated Thu Jun 18 14:42:02 CST 2020
     */
    SmsRealTimeStatistics selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_real_time_statistics
     *
     * @mbg.generated Thu Jun 18 14:42:02 CST 2020
     */
    int updateByExampleSelective(@Param("record") SmsRealTimeStatistics record, @Param("example") SmsRealTimeStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_real_time_statistics
     *
     * @mbg.generated Thu Jun 18 14:42:02 CST 2020
     */
    int updateByExample(@Param("record") SmsRealTimeStatistics record, @Param("example") SmsRealTimeStatisticsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_real_time_statistics
     *
     * @mbg.generated Thu Jun 18 14:42:02 CST 2020
     */
    int updateByPrimaryKeySelective(SmsRealTimeStatistics record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_real_time_statistics
     *
     * @mbg.generated Thu Jun 18 14:42:02 CST 2020
     */
    int updateByPrimaryKey(SmsRealTimeStatistics record);
}