package com.hero.wireless.web.dao.business;

import com.hero.wireless.web.dao.base.IDao;
import com.hero.wireless.web.entity.business.WhiteList;
import com.hero.wireless.web.entity.business.WhiteListExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface IWhiteListDAO<T extends WhiteList> extends IDao<WhiteList, WhiteListExample> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list
     *
     * @mbg.generated Tue Jun 16 19:01:36 CST 2020
     */
    int countByExample(WhiteListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list
     *
     * @mbg.generated Tue Jun 16 19:01:36 CST 2020
     */
    int deleteByExample(WhiteListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list
     *
     * @mbg.generated Tue Jun 16 19:01:36 CST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list
     *
     * @mbg.generated Tue Jun 16 19:01:36 CST 2020
     */
    int insert(WhiteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list
     *
     * @mbg.generated Tue Jun 16 19:01:36 CST 2020
     */
    int insertList(List<WhiteList> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list
     *
     * @mbg.generated Tue Jun 16 19:01:36 CST 2020
     */
    int insertSelective(WhiteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list
     *
     * @mbg.generated Tue Jun 16 19:01:36 CST 2020
     */
    List<WhiteList> selectByExample(WhiteListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list
     *
     * @mbg.generated Tue Jun 16 19:01:36 CST 2020
     */
    WhiteList selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list
     *
     * @mbg.generated Tue Jun 16 19:01:36 CST 2020
     */
    int updateByExampleSelective(@Param("record") WhiteList record, @Param("example") WhiteListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list
     *
     * @mbg.generated Tue Jun 16 19:01:36 CST 2020
     */
    int updateByExample(@Param("record") WhiteList record, @Param("example") WhiteListExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list
     *
     * @mbg.generated Tue Jun 16 19:01:36 CST 2020
     */
    int updateByPrimaryKeySelective(WhiteList record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table white_list
     *
     * @mbg.generated Tue Jun 16 19:01:36 CST 2020
     */
    int updateByPrimaryKey(WhiteList record);
}